package com.et59.cus.domain.dao;

import com.et59.cus.domain.entity.BsAddress;
import com.et59.cus.domain.entity.BsAddressExample;
import java.util.List;

public interface BsAddressDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_address
	 * @abatorgenerated
	 */
	void insert(BsAddress record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_address
	 * @abatorgenerated
	 */
	int updateByPrimaryKey(BsAddress record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_address
	 * @abatorgenerated
	 */
	int updateByPrimaryKeySelective(BsAddress record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_address
	 * @abatorgenerated
	 */
	List<BsAddress> selectByExample(BsAddressExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_address
	 * @abatorgenerated
	 */
	BsAddress selectByPrimaryKey(Long id);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_address
	 * @abatorgenerated
	 */
	int deleteByExample(BsAddressExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_address
	 * @abatorgenerated
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_address
	 * @abatorgenerated
	 */
	int countByExample(BsAddressExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_address
	 * @abatorgenerated
	 */
	int updateByExampleSelective(BsAddress record, BsAddressExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_address
	 * @abatorgenerated
	 */
	int updateByExample(BsAddress record, BsAddressExample example);
}