package com.et59.cus.domain.dao;

import com.et59.cus.domain.entity.BsAddress;
import com.et59.cus.domain.entity.BsAddressExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class BsAddressDAOImpl extends SqlMapClientDaoSupport implements BsAddressDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_address
	 * @abatorgenerated
	 */
	public BsAddressDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_address
	 * @abatorgenerated
	 */
	public void insert(BsAddress record) {
		getSqlMapClientTemplate().insert("bs_address.abatorgenerated_insert",
				record);
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_address
	 * @abatorgenerated
	 */
	public int updateByPrimaryKey(BsAddress record) {
		int rows = getSqlMapClientTemplate().update(
				"bs_address.abatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_address
	 * @abatorgenerated
	 */
	public int updateByPrimaryKeySelective(BsAddress record) {
		int rows = getSqlMapClientTemplate().update(
				"bs_address.abatorgenerated_updateByPrimaryKeySelective",
				record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_address
	 * @abatorgenerated
	 */
	@SuppressWarnings("unchecked")
	public List<BsAddress> selectByExample(BsAddressExample example) {
		List<BsAddress> list = (List<BsAddress>) getSqlMapClientTemplate()
				.queryForList("bs_address.abatorgenerated_selectByExample",
						example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_address
	 * @abatorgenerated
	 */
	public BsAddress selectByPrimaryKey(Long id) {
		BsAddress key = new BsAddress();
		key.setId(id);
		BsAddress record = (BsAddress) getSqlMapClientTemplate()
				.queryForObject(
						"bs_address.abatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_address
	 * @abatorgenerated
	 */
	public int deleteByExample(BsAddressExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"bs_address.abatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_address
	 * @abatorgenerated
	 */
	public int deleteByPrimaryKey(Long id) {
		BsAddress key = new BsAddress();
		key.setId(id);
		int rows = getSqlMapClientTemplate().delete(
				"bs_address.abatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_address
	 * @abatorgenerated
	 */
	public int countByExample(BsAddressExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"bs_address.abatorgenerated_countByExample", example);
		return count;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_address
	 * @abatorgenerated
	 */
	public int updateByExampleSelective(BsAddress record,
			BsAddressExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"bs_address.abatorgenerated_updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_address
	 * @abatorgenerated
	 */
	public int updateByExample(BsAddress record, BsAddressExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"bs_address.abatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This class was generated by Abator for iBATIS. This class corresponds to the database table bs_address
	 * @abatorgenerated
	 */
	private static class UpdateByExampleParms extends BsAddressExample {
		private Object record;

		public UpdateByExampleParms(Object record, BsAddressExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}