package com.et59.cus.domain.dao;

import com.et59.cus.domain.entity.BsEmail;
import com.et59.cus.domain.entity.BsEmailExample;
import java.util.List;

public interface BsEmailDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_email
	 * @abatorgenerated
	 */
	void insert(BsEmail record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_email
	 * @abatorgenerated
	 */
	int updateByPrimaryKey(BsEmail record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_email
	 * @abatorgenerated
	 */
	int updateByPrimaryKeySelective(BsEmail record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_email
	 * @abatorgenerated
	 */
	List<BsEmail> selectByExample(BsEmailExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_email
	 * @abatorgenerated
	 */
	BsEmail selectByPrimaryKey(Long id);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_email
	 * @abatorgenerated
	 */
	int deleteByExample(BsEmailExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_email
	 * @abatorgenerated
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_email
	 * @abatorgenerated
	 */
	int countByExample(BsEmailExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_email
	 * @abatorgenerated
	 */
	int updateByExampleSelective(BsEmail record, BsEmailExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_email
	 * @abatorgenerated
	 */
	int updateByExample(BsEmail record, BsEmailExample example);
}