package com.et59.cus.domain.dao;

import com.et59.cus.domain.entity.BsEmail;
import com.et59.cus.domain.entity.BsEmailExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class BsEmailDAOImpl extends SqlMapClientDaoSupport implements BsEmailDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_email
	 * @abatorgenerated
	 */
	public BsEmailDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_email
	 * @abatorgenerated
	 */
	public void insert(BsEmail record) {
		getSqlMapClientTemplate().insert("bs_email.abatorgenerated_insert",
				record);
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_email
	 * @abatorgenerated
	 */
	public int updateByPrimaryKey(BsEmail record) {
		int rows = getSqlMapClientTemplate().update(
				"bs_email.abatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_email
	 * @abatorgenerated
	 */
	public int updateByPrimaryKeySelective(BsEmail record) {
		int rows = getSqlMapClientTemplate().update(
				"bs_email.abatorgenerated_updateByPrimaryKeySelective", record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_email
	 * @abatorgenerated
	 */
	@SuppressWarnings("unchecked")
	public List<BsEmail> selectByExample(BsEmailExample example) {
		List<BsEmail> list = (List<BsEmail>) getSqlMapClientTemplate()
				.queryForList("bs_email.abatorgenerated_selectByExample",
						example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_email
	 * @abatorgenerated
	 */
	public BsEmail selectByPrimaryKey(Long id) {
		BsEmail key = new BsEmail();
		key.setId(id);
		BsEmail record = (BsEmail) getSqlMapClientTemplate().queryForObject(
				"bs_email.abatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_email
	 * @abatorgenerated
	 */
	public int deleteByExample(BsEmailExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"bs_email.abatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_email
	 * @abatorgenerated
	 */
	public int deleteByPrimaryKey(Long id) {
		BsEmail key = new BsEmail();
		key.setId(id);
		int rows = getSqlMapClientTemplate().delete(
				"bs_email.abatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_email
	 * @abatorgenerated
	 */
	public int countByExample(BsEmailExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"bs_email.abatorgenerated_countByExample", example);
		return count;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_email
	 * @abatorgenerated
	 */
	public int updateByExampleSelective(BsEmail record, BsEmailExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"bs_email.abatorgenerated_updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_email
	 * @abatorgenerated
	 */
	public int updateByExample(BsEmail record, BsEmailExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"bs_email.abatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This class was generated by Abator for iBATIS. This class corresponds to the database table bs_email
	 * @abatorgenerated
	 */
	private static class UpdateByExampleParms extends BsEmailExample {
		private Object record;

		public UpdateByExampleParms(Object record, BsEmailExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}