package com.et59.cus.domain.dao;

import com.et59.cus.domain.entity.BsLeavemessage;
import com.et59.cus.domain.entity.BsLeavemessageExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class BsLeavemessageDAOImpl extends SqlMapClientDaoSupport implements BsLeavemessageDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_leavemessage
	 * @abatorgenerated
	 */
	public BsLeavemessageDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_leavemessage
	 * @abatorgenerated
	 */
	public void insert(BsLeavemessage record) {
		getSqlMapClientTemplate().insert(
				"bs_leavemessage.abatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_leavemessage
	 * @abatorgenerated
	 */
	public int updateByPrimaryKey(BsLeavemessage record) {
		int rows = getSqlMapClientTemplate().update(
				"bs_leavemessage.abatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_leavemessage
	 * @abatorgenerated
	 */
	public int updateByPrimaryKeySelective(BsLeavemessage record) {
		int rows = getSqlMapClientTemplate().update(
				"bs_leavemessage.abatorgenerated_updateByPrimaryKeySelective",
				record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_leavemessage
	 * @abatorgenerated
	 */
	@SuppressWarnings("unchecked")
	public List<BsLeavemessage> selectByExample(BsLeavemessageExample example) {
		List<BsLeavemessage> list = (List<BsLeavemessage>) getSqlMapClientTemplate()
				.queryForList(
						"bs_leavemessage.abatorgenerated_selectByExample",
						example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_leavemessage
	 * @abatorgenerated
	 */
	public BsLeavemessage selectByPrimaryKey(Long id) {
		BsLeavemessage key = new BsLeavemessage();
		key.setId(id);
		BsLeavemessage record = (BsLeavemessage) getSqlMapClientTemplate()
				.queryForObject(
						"bs_leavemessage.abatorgenerated_selectByPrimaryKey",
						key);
		return record;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_leavemessage
	 * @abatorgenerated
	 */
	public int deleteByExample(BsLeavemessageExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"bs_leavemessage.abatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_leavemessage
	 * @abatorgenerated
	 */
	public int deleteByPrimaryKey(Long id) {
		BsLeavemessage key = new BsLeavemessage();
		key.setId(id);
		int rows = getSqlMapClientTemplate().delete(
				"bs_leavemessage.abatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_leavemessage
	 * @abatorgenerated
	 */
	public int countByExample(BsLeavemessageExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"bs_leavemessage.abatorgenerated_countByExample", example);
		return count;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_leavemessage
	 * @abatorgenerated
	 */
	public int updateByExampleSelective(BsLeavemessage record,
			BsLeavemessageExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"bs_leavemessage.abatorgenerated_updateByExampleSelective",
				parms);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_leavemessage
	 * @abatorgenerated
	 */
	public int updateByExample(BsLeavemessage record,
			BsLeavemessageExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"bs_leavemessage.abatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This class was generated by Abator for iBATIS. This class corresponds to the database table bs_leavemessage
	 * @abatorgenerated
	 */
	private static class UpdateByExampleParms extends BsLeavemessageExample {
		private Object record;

		public UpdateByExampleParms(Object record, BsLeavemessageExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}