package com.et59.cus.domain.dao;

import java.util.HashMap;
import java.util.List;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import com.et59.cus.domain.entity.BsMenu;
import com.et59.cus.domain.entity.BsMenuExample;

/**
 * @author Administrator
 *
 */
public class BsMenuDAOImpl extends SqlMapClientDaoSupport implements BsMenuDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table bs_menu
	 * 
	 * @abatorgenerated
	 */
	public BsMenuDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table bs_menu
	 * 
	 * @abatorgenerated
	 */
	public void insert(BsMenu record) {
		getSqlMapClientTemplate().insert("bs_menu.abatorgenerated_insert",
				record);
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table bs_menu
	 * 
	 * @abatorgenerated
	 */
	public int updateByPrimaryKey(BsMenu record) {
		int rows = getSqlMapClientTemplate().update(
				"bs_menu.abatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table bs_menu
	 * 
	 * @abatorgenerated
	 */
	public int updateByPrimaryKeySelective(BsMenu record) {
		int rows = getSqlMapClientTemplate().update(
				"bs_menu.abatorgenerated_updateByPrimaryKeySelective", record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table bs_menu
	 * 
	 * @abatorgenerated
	 */
	@SuppressWarnings("unchecked")
	public List<BsMenu> selectByExample(BsMenuExample example) {
		List<BsMenu> list = (List<BsMenu>) getSqlMapClientTemplate()
				.queryForList("bs_menu.abatorgenerated_selectByExample",
						example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table bs_menu
	 * 
	 * @abatorgenerated
	 */
	public BsMenu selectByPrimaryKey(Long id) {
		BsMenu key = new BsMenu();
		key.setId(id);
		BsMenu record = (BsMenu) getSqlMapClientTemplate().queryForObject(
				"bs_menu.abatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table bs_menu
	 * 
	 * @abatorgenerated
	 */
	public int deleteByExample(BsMenuExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"bs_menu.abatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table bs_menu
	 * 
	 * @abatorgenerated
	 */
	public int deleteByPrimaryKey(Long id) {
		BsMenu key = new BsMenu();
		key.setId(id);
		int rows = getSqlMapClientTemplate().delete(
				"bs_menu.abatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table bs_menu
	 * 
	 * @abatorgenerated
	 */
	public int countByExample(BsMenuExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"bs_menu.abatorgenerated_countByExample", example);
		return count;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table bs_menu
	 * 
	 * @abatorgenerated
	 */
	public int updateByExampleSelective(BsMenu record, BsMenuExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"bs_menu.abatorgenerated_updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table bs_menu
	 * 
	 * @abatorgenerated
	 */
	public int updateByExample(BsMenu record, BsMenuExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"bs_menu.abatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This class was generated by Abator for iBATIS. This class corresponds to
	 * the database table bs_menu
	 * 
	 * @abatorgenerated
	 */
	private static class UpdateByExampleParms extends BsMenuExample {
		private Object record;

		public UpdateByExampleParms(Object record, BsMenuExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}

	
	/* 
	 * 根据用户获取菜单数
	 */
	public int countByExampleByUserid(HashMap map) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"bs_menu.abatorgenerated_countByExampleByUserid", map);
		return count;
	}
	
	
	/**
	 * 根据用户获取菜单
	 */
	@SuppressWarnings("unchecked")
	public List<BsMenu> selectByExampleByUserid(BsMenuExample example,HashMap map) {
		List<BsMenu> list = (List<BsMenu>) getSqlMapClientTemplate()
				.queryForList("bs_menu.selectMenuByUserId",
						map);
		return list;
	}
}