package com.et59.cus.domain.dao;

import java.util.List;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import com.et59.cus.domain.entity.BsOrder;
import com.et59.cus.domain.entity.BsOrderExample;

public class BsOrderDAOImpl extends SqlMapClientDaoSupport implements BsOrderDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_order
	 * @abatorgenerated
	 */
	public BsOrderDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_order
	 * @abatorgenerated
	 */
	public void insert(BsOrder record) {
		getSqlMapClientTemplate().insert("bs_order.abatorgenerated_insert",
				record);
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_order
	 * @abatorgenerated
	 */
	public int updateByPrimaryKey(BsOrder record) {
		int rows = getSqlMapClientTemplate().update(
				"bs_order.abatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_order
	 * @abatorgenerated
	 */
	public int updateByPrimaryKeySelective(BsOrder record) {
		int rows = getSqlMapClientTemplate().update(
				"bs_order.abatorgenerated_updateByPrimaryKeySelective", record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_order
	 * @abatorgenerated
	 */
	@SuppressWarnings("unchecked")
	public List<BsOrder> selectByExample(BsOrderExample example) {
		List<BsOrder> list = (List<BsOrder>) getSqlMapClientTemplate()
				.queryForList("bs_order.abatorgenerated_selectByExample",
						example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_order
	 * @abatorgenerated
	 */
	public BsOrder selectByPrimaryKey(Integer id) {
		BsOrder key = new BsOrder();
		key.setId(id);
		BsOrder record = (BsOrder) getSqlMapClientTemplate().queryForObject(
				"bs_order.abatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_order
	 * @abatorgenerated
	 */
	public int deleteByExample(BsOrderExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"bs_order.abatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_order
	 * @abatorgenerated
	 */
	public int deleteByPrimaryKey(Integer id) {
		BsOrder key = new BsOrder();
		key.setId(id);
		int rows = getSqlMapClientTemplate().delete(
				"bs_order.abatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_order
	 * @abatorgenerated
	 */
	public int countByExample(BsOrderExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"bs_order.abatorgenerated_countByExample", example);
		return count;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_order
	 * @abatorgenerated
	 */
	public int updateByExampleSelective(BsOrder record, BsOrderExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"bs_order.abatorgenerated_updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_order
	 * @abatorgenerated
	 */
	public int updateByExample(BsOrder record, BsOrderExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"bs_order.abatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This class was generated by Abator for iBATIS. This class corresponds to the database table bs_order
	 * @abatorgenerated
	 */
	private static class UpdateByExampleParms extends BsOrderExample {
		private Object record;

		public UpdateByExampleParms(Object record, BsOrderExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}