package com.et59.cus.domain.dao;

import com.et59.cus.domain.entity.BsPagestatic;
import com.et59.cus.domain.entity.BsPagestaticExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class BsPagestaticDAOImpl extends SqlMapClientDaoSupport implements BsPagestaticDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_pagestatic
	 * @abatorgenerated
	 */
	public BsPagestaticDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_pagestatic
	 * @abatorgenerated
	 */
	public void insert(BsPagestatic record) {
		getSqlMapClientTemplate().insert(
				"bs_pagestatic.abatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_pagestatic
	 * @abatorgenerated
	 */
	public int updateByPrimaryKey(BsPagestatic record) {
		int rows = getSqlMapClientTemplate().update(
				"bs_pagestatic.abatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_pagestatic
	 * @abatorgenerated
	 */
	public int updateByPrimaryKeySelective(BsPagestatic record) {
		int rows = getSqlMapClientTemplate().update(
				"bs_pagestatic.abatorgenerated_updateByPrimaryKeySelective",
				record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_pagestatic
	 * @abatorgenerated
	 */
	@SuppressWarnings("unchecked")
	public List<BsPagestatic> selectByExample(BsPagestaticExample example) {
		List<BsPagestatic> list = (List<BsPagestatic>) getSqlMapClientTemplate()
				.queryForList("bs_pagestatic.abatorgenerated_selectByExample",
						example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_pagestatic
	 * @abatorgenerated
	 */
	public BsPagestatic selectByPrimaryKey(Long id) {
		BsPagestatic key = new BsPagestatic();
		key.setId(id);
		BsPagestatic record = (BsPagestatic) getSqlMapClientTemplate()
				.queryForObject(
						"bs_pagestatic.abatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_pagestatic
	 * @abatorgenerated
	 */
	public int deleteByExample(BsPagestaticExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"bs_pagestatic.abatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_pagestatic
	 * @abatorgenerated
	 */
	public int deleteByPrimaryKey(Long id) {
		BsPagestatic key = new BsPagestatic();
		key.setId(id);
		int rows = getSqlMapClientTemplate().delete(
				"bs_pagestatic.abatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_pagestatic
	 * @abatorgenerated
	 */
	public int countByExample(BsPagestaticExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"bs_pagestatic.abatorgenerated_countByExample", example);
		return count;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_pagestatic
	 * @abatorgenerated
	 */
	public int updateByExampleSelective(BsPagestatic record,
			BsPagestaticExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate()
				.update("bs_pagestatic.abatorgenerated_updateByExampleSelective",
						parms);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_pagestatic
	 * @abatorgenerated
	 */
	public int updateByExample(BsPagestatic record, BsPagestaticExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"bs_pagestatic.abatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This class was generated by Abator for iBATIS. This class corresponds to the database table bs_pagestatic
	 * @abatorgenerated
	 */
	private static class UpdateByExampleParms extends BsPagestaticExample {
		private Object record;

		public UpdateByExampleParms(Object record, BsPagestaticExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}