package com.et59.cus.domain.dao;

import java.util.List;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import com.et59.cus.domain.entity.BsProduct;
import com.et59.cus.domain.entity.BsProductExample;

public class BsProductDAOImpl extends SqlMapClientDaoSupport implements BsProductDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_product
	 * @abatorgenerated
	 */
	public BsProductDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_product
	 * @abatorgenerated
	 */
	public void insert(BsProduct record) {
		getSqlMapClientTemplate().insert("bs_product.abatorgenerated_insert",
				record);
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_product
	 * @abatorgenerated
	 */
	public int updateByPrimaryKey(BsProduct record) {
		int rows = getSqlMapClientTemplate().update(
				"bs_product.abatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_product
	 * @abatorgenerated
	 */
	public int updateByPrimaryKeySelective(BsProduct record) {
		int rows = getSqlMapClientTemplate().update(
				"bs_product.abatorgenerated_updateByPrimaryKeySelective",
				record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_product
	 * @abatorgenerated
	 */
	@SuppressWarnings("unchecked")
	public List<BsProduct> selectByExample(BsProductExample example) {
		List<BsProduct> list = (List<BsProduct>) getSqlMapClientTemplate()
				.queryForList("bs_product.abatorgenerated_selectByExample",
						example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_product
	 * @abatorgenerated
	 */
	public BsProduct selectByPrimaryKey(Integer id) {
		BsProduct key = new BsProduct();
		key.setId(id);
		BsProduct record = (BsProduct) getSqlMapClientTemplate()
				.queryForObject(
						"bs_product.abatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_product
	 * @abatorgenerated
	 */
	public int deleteByExample(BsProductExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"bs_product.abatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_product
	 * @abatorgenerated
	 */
	public int deleteByPrimaryKey(Integer id) {
		BsProduct key = new BsProduct();
		key.setId(id);
		int rows = getSqlMapClientTemplate().delete(
				"bs_product.abatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_product
	 * @abatorgenerated
	 */
	public int countByExample(BsProductExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"bs_product.abatorgenerated_countByExample", example);
		return count;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_product
	 * @abatorgenerated
	 */
	public int updateByExampleSelective(BsProduct record,
			BsProductExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"bs_product.abatorgenerated_updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_product
	 * @abatorgenerated
	 */
	public int updateByExample(BsProduct record, BsProductExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"bs_product.abatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This class was generated by Abator for iBATIS. This class corresponds to the database table bs_product
	 * @abatorgenerated
	 */
	private static class UpdateByExampleParms extends BsProductExample {
		private Object record;

		public UpdateByExampleParms(Object record, BsProductExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}