package com.et59.cus.domain.dao;

import java.util.List;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import com.et59.cus.domain.entity.BsProductcategory;
import com.et59.cus.domain.entity.BsProductcategoryExample;

public class BsProductcategoryDAOImpl extends SqlMapClientDaoSupport implements BsProductcategoryDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_productcategory
	 * @abatorgenerated
	 */
	public BsProductcategoryDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_productcategory
	 * @abatorgenerated
	 */
	public void insert(BsProductcategory record) {
		getSqlMapClientTemplate().insert(
				"bs_productcategory.abatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_productcategory
	 * @abatorgenerated
	 */
	public int updateByPrimaryKey(BsProductcategory record) {
		int rows = getSqlMapClientTemplate()
				.update("bs_productcategory.abatorgenerated_updateByPrimaryKey",
						record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_productcategory
	 * @abatorgenerated
	 */
	public int updateByPrimaryKeySelective(BsProductcategory record) {
		int rows = getSqlMapClientTemplate()
				.update("bs_productcategory.abatorgenerated_updateByPrimaryKeySelective",
						record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_productcategory
	 * @abatorgenerated
	 */
	@SuppressWarnings("unchecked")
	public List<BsProductcategory> selectByExample(
			BsProductcategoryExample example) {
		List<BsProductcategory> list = (List<BsProductcategory>) getSqlMapClientTemplate()
				.queryForList(
						"bs_productcategory.abatorgenerated_selectByExample",
						example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_productcategory
	 * @abatorgenerated
	 */
	public BsProductcategory selectByPrimaryKey(Integer id) {
		BsProductcategory key = new BsProductcategory();
		key.setId(id);
		BsProductcategory record = (BsProductcategory) getSqlMapClientTemplate()
				.queryForObject(
						"bs_productcategory.abatorgenerated_selectByPrimaryKey",
						key);
		return record;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_productcategory
	 * @abatorgenerated
	 */
	public int deleteByExample(BsProductcategoryExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"bs_productcategory.abatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_productcategory
	 * @abatorgenerated
	 */
	public int deleteByPrimaryKey(Integer id) {
		BsProductcategory key = new BsProductcategory();
		key.setId(id);
		int rows = getSqlMapClientTemplate().delete(
				"bs_productcategory.abatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_productcategory
	 * @abatorgenerated
	 */
	public int countByExample(BsProductcategoryExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"bs_productcategory.abatorgenerated_countByExample", example);
		return count;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_productcategory
	 * @abatorgenerated
	 */
	public int updateByExampleSelective(BsProductcategory record,
			BsProductcategoryExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"bs_productcategory.abatorgenerated_updateByExampleSelective",
				parms);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_productcategory
	 * @abatorgenerated
	 */
	public int updateByExample(BsProductcategory record,
			BsProductcategoryExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"bs_productcategory.abatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This class was generated by Abator for iBATIS. This class corresponds to the database table bs_productcategory
	 * @abatorgenerated
	 */
	private static class UpdateByExampleParms extends BsProductcategoryExample {
		private Object record;

		public UpdateByExampleParms(Object record,
				BsProductcategoryExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}