package com.et59.cus.domain.dao;

import com.et59.cus.domain.entity.BsResource;
import com.et59.cus.domain.entity.BsResourceExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class BsResourceDAOImpl extends SqlMapClientDaoSupport implements BsResourceDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_resource
	 * @abatorgenerated
	 */
	public BsResourceDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_resource
	 * @abatorgenerated
	 */
	public void insert(BsResource record) {
		getSqlMapClientTemplate().insert("bs_resource.abatorgenerated_insert",
				record);
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_resource
	 * @abatorgenerated
	 */
	public int updateByPrimaryKey(BsResource record) {
		int rows = getSqlMapClientTemplate().update(
				"bs_resource.abatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_resource
	 * @abatorgenerated
	 */
	public int updateByPrimaryKeySelective(BsResource record) {
		int rows = getSqlMapClientTemplate().update(
				"bs_resource.abatorgenerated_updateByPrimaryKeySelective",
				record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_resource
	 * @abatorgenerated
	 */
	@SuppressWarnings("unchecked")
	public List<BsResource> selectByExample(BsResourceExample example) {
		List<BsResource> list = (List<BsResource>) getSqlMapClientTemplate()
				.queryForList("bs_resource.abatorgenerated_selectByExample",
						example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_resource
	 * @abatorgenerated
	 */
	public BsResource selectByPrimaryKey(Integer id) {
		BsResource key = new BsResource();
		key.setId(id);
		BsResource record = (BsResource) getSqlMapClientTemplate()
				.queryForObject(
						"bs_resource.abatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_resource
	 * @abatorgenerated
	 */
	public int deleteByExample(BsResourceExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"bs_resource.abatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_resource
	 * @abatorgenerated
	 */
	public int deleteByPrimaryKey(Integer id) {
		BsResource key = new BsResource();
		key.setId(id);
		int rows = getSqlMapClientTemplate().delete(
				"bs_resource.abatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_resource
	 * @abatorgenerated
	 */
	public int countByExample(BsResourceExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"bs_resource.abatorgenerated_countByExample", example);
		return count;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_resource
	 * @abatorgenerated
	 */
	public int updateByExampleSelective(BsResource record,
			BsResourceExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"bs_resource.abatorgenerated_updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_resource
	 * @abatorgenerated
	 */
	public int updateByExample(BsResource record, BsResourceExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"bs_resource.abatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This class was generated by Abator for iBATIS. This class corresponds to the database table bs_resource
	 * @abatorgenerated
	 */
	private static class UpdateByExampleParms extends BsResourceExample {
		private Object record;

		public UpdateByExampleParms(Object record, BsResourceExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}