package com.et59.cus.domain.dao;

import com.et59.cus.domain.entity.BsRoleResource;
import com.et59.cus.domain.entity.BsRoleResourceExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class BsRoleResourceDAOImpl extends SqlMapClientDaoSupport implements BsRoleResourceDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_role_resource
	 * @abatorgenerated
	 */
	public BsRoleResourceDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_role_resource
	 * @abatorgenerated
	 */
	public void insert(BsRoleResource record) {
		getSqlMapClientTemplate().insert(
				"bs_role_resource.abatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_role_resource
	 * @abatorgenerated
	 */
	public int updateByPrimaryKey(BsRoleResource record) {
		int rows = getSqlMapClientTemplate().update(
				"bs_role_resource.abatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_role_resource
	 * @abatorgenerated
	 */
	public int updateByPrimaryKeySelective(BsRoleResource record) {
		int rows = getSqlMapClientTemplate().update(
				"bs_role_resource.abatorgenerated_updateByPrimaryKeySelective",
				record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_role_resource
	 * @abatorgenerated
	 */
	@SuppressWarnings("unchecked")
	public List<BsRoleResource> selectByExample(BsRoleResourceExample example) {
		List<BsRoleResource> list = (List<BsRoleResource>) getSqlMapClientTemplate()
				.queryForList(
						"bs_role_resource.abatorgenerated_selectByExample",
						example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_role_resource
	 * @abatorgenerated
	 */
	public BsRoleResource selectByPrimaryKey(Integer id) {
		BsRoleResource key = new BsRoleResource();
		key.setId(id);
		BsRoleResource record = (BsRoleResource) getSqlMapClientTemplate()
				.queryForObject(
						"bs_role_resource.abatorgenerated_selectByPrimaryKey",
						key);
		return record;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_role_resource
	 * @abatorgenerated
	 */
	public int deleteByExample(BsRoleResourceExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"bs_role_resource.abatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_role_resource
	 * @abatorgenerated
	 */
	public int deleteByPrimaryKey(Integer id) {
		BsRoleResource key = new BsRoleResource();
		key.setId(id);
		int rows = getSqlMapClientTemplate().delete(
				"bs_role_resource.abatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_role_resource
	 * @abatorgenerated
	 */
	public int countByExample(BsRoleResourceExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"bs_role_resource.abatorgenerated_countByExample", example);
		return count;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_role_resource
	 * @abatorgenerated
	 */
	public int updateByExampleSelective(BsRoleResource record,
			BsRoleResourceExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"bs_role_resource.abatorgenerated_updateByExampleSelective",
				parms);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_role_resource
	 * @abatorgenerated
	 */
	public int updateByExample(BsRoleResource record,
			BsRoleResourceExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"bs_role_resource.abatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This class was generated by Abator for iBATIS. This class corresponds to the database table bs_role_resource
	 * @abatorgenerated
	 */
	private static class UpdateByExampleParms extends BsRoleResourceExample {
		private Object record;

		public UpdateByExampleParms(Object record, BsRoleResourceExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}