package com.et59.cus.domain.dao;

import com.et59.cus.domain.entity.BsRole;
import com.et59.cus.domain.entity.BsRoleExample;
import java.util.List;

public interface BsRoleDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_role
	 * @abatorgenerated
	 */
	void insert(BsRole record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_role
	 * @abatorgenerated
	 */
	int updateByPrimaryKey(BsRole record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_role
	 * @abatorgenerated
	 */
	int updateByPrimaryKeySelective(BsRole record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_role
	 * @abatorgenerated
	 */
	List<BsRole> selectByExample(BsRoleExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_role
	 * @abatorgenerated
	 */
	BsRole selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_role
	 * @abatorgenerated
	 */
	int deleteByExample(BsRoleExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_role
	 * @abatorgenerated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_role
	 * @abatorgenerated
	 */
	int countByExample(BsRoleExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_role
	 * @abatorgenerated
	 */
	int updateByExampleSelective(BsRole record, BsRoleExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_role
	 * @abatorgenerated
	 */
	int updateByExample(BsRole record, BsRoleExample example);
}