package com.et59.cus.domain.dao;

import java.util.List;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import com.et59.cus.domain.entity.BsSupplier;
import com.et59.cus.domain.entity.BsSupplierExample;

public class BsSupplierDAOImpl extends SqlMapClientDaoSupport implements BsSupplierDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_supplier
	 * @abatorgenerated
	 */
	public BsSupplierDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_supplier
	 * @abatorgenerated
	 */
	public void insert(BsSupplier record) {
		getSqlMapClientTemplate().insert("bs_supplier.abatorgenerated_insert",
				record);
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_supplier
	 * @abatorgenerated
	 */
	public int updateByPrimaryKey(BsSupplier record) {
		int rows = getSqlMapClientTemplate().update(
				"bs_supplier.abatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_supplier
	 * @abatorgenerated
	 */
	public int updateByPrimaryKeySelective(BsSupplier record) {
		int rows = getSqlMapClientTemplate().update(
				"bs_supplier.abatorgenerated_updateByPrimaryKeySelective",
				record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_supplier
	 * @abatorgenerated
	 */
	@SuppressWarnings("unchecked")
	public List<BsSupplier> selectByExample(BsSupplierExample example) {
		List<BsSupplier> list = (List<BsSupplier>) getSqlMapClientTemplate()
				.queryForList("bs_supplier.abatorgenerated_selectByExample",
						example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_supplier
	 * @abatorgenerated
	 */
	public BsSupplier selectByPrimaryKey(Integer id) {
		BsSupplier key = new BsSupplier();
		key.setId(id);
		BsSupplier record = (BsSupplier) getSqlMapClientTemplate()
				.queryForObject(
						"bs_supplier.abatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_supplier
	 * @abatorgenerated
	 */
	public int deleteByExample(BsSupplierExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"bs_supplier.abatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_supplier
	 * @abatorgenerated
	 */
	public int deleteByPrimaryKey(Integer id) {
		BsSupplier key = new BsSupplier();
		key.setId(id);
		int rows = getSqlMapClientTemplate().delete(
				"bs_supplier.abatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_supplier
	 * @abatorgenerated
	 */
	public int countByExample(BsSupplierExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"bs_supplier.abatorgenerated_countByExample", example);
		return count;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_supplier
	 * @abatorgenerated
	 */
	public int updateByExampleSelective(BsSupplier record,
			BsSupplierExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"bs_supplier.abatorgenerated_updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_supplier
	 * @abatorgenerated
	 */
	public int updateByExample(BsSupplier record, BsSupplierExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"bs_supplier.abatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This class was generated by Abator for iBATIS. This class corresponds to the database table bs_supplier
	 * @abatorgenerated
	 */
	private static class UpdateByExampleParms extends BsSupplierExample {
		private Object record;

		public UpdateByExampleParms(Object record, BsSupplierExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}