package com.et59.cus.domain.dao;

import com.et59.cus.domain.entity.BsSystem;
import com.et59.cus.domain.entity.BsSystemExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class BsSystemDAOImpl extends SqlMapClientDaoSupport implements BsSystemDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_system
	 * @abatorgenerated
	 */
	public BsSystemDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_system
	 * @abatorgenerated
	 */
	public void insert(BsSystem record) {
		getSqlMapClientTemplate().insert("bs_system.abatorgenerated_insert",
				record);
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_system
	 * @abatorgenerated
	 */
	public int updateByPrimaryKey(BsSystem record) {
		int rows = getSqlMapClientTemplate().update(
				"bs_system.abatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_system
	 * @abatorgenerated
	 */
	public int updateByPrimaryKeySelective(BsSystem record) {
		int rows = getSqlMapClientTemplate()
				.update("bs_system.abatorgenerated_updateByPrimaryKeySelective",
						record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_system
	 * @abatorgenerated
	 */
	@SuppressWarnings("unchecked")
	public List<BsSystem> selectByExample(BsSystemExample example) {
		List<BsSystem> list = (List<BsSystem>) getSqlMapClientTemplate()
				.queryForList("bs_system.abatorgenerated_selectByExample",
						example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_system
	 * @abatorgenerated
	 */
	public BsSystem selectByPrimaryKey(Long id) {
		BsSystem key = new BsSystem();
		key.setId(id);
		BsSystem record = (BsSystem) getSqlMapClientTemplate().queryForObject(
				"bs_system.abatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_system
	 * @abatorgenerated
	 */
	public int deleteByExample(BsSystemExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"bs_system.abatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_system
	 * @abatorgenerated
	 */
	public int deleteByPrimaryKey(Long id) {
		BsSystem key = new BsSystem();
		key.setId(id);
		int rows = getSqlMapClientTemplate().delete(
				"bs_system.abatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_system
	 * @abatorgenerated
	 */
	public int countByExample(BsSystemExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"bs_system.abatorgenerated_countByExample", example);
		return count;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_system
	 * @abatorgenerated
	 */
	public int updateByExampleSelective(BsSystem record, BsSystemExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"bs_system.abatorgenerated_updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_system
	 * @abatorgenerated
	 */
	public int updateByExample(BsSystem record, BsSystemExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"bs_system.abatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This class was generated by Abator for iBATIS. This class corresponds to the database table bs_system
	 * @abatorgenerated
	 */
	private static class UpdateByExampleParms extends BsSystemExample {
		private Object record;

		public UpdateByExampleParms(Object record, BsSystemExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}