package com.et59.cus.domain.dao;

import java.util.List;

import com.et59.cus.domain.entity.BsUser;
import com.et59.cus.domain.entity.BsUserExample;

public interface BsUserDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_user
	 * @abatorgenerated
	 */
	void insert(BsUser record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_user
	 * @abatorgenerated
	 */
	int updateByPrimaryKey(BsUser record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_user
	 * @abatorgenerated
	 */
	int updateByPrimaryKeySelective(BsUser record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_user
	 * @abatorgenerated
	 */
	List<BsUser> selectByExample(BsUserExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_user
	 * @abatorgenerated
	 */
	BsUser selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_user
	 * @abatorgenerated
	 */
	int deleteByExample(BsUserExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_user
	 * @abatorgenerated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_user
	 * @abatorgenerated
	 */
	int countByExample(BsUserExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_user
	 * @abatorgenerated
	 */
	int updateByExampleSelective(BsUser record, BsUserExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_user
	 * @abatorgenerated
	 */
	int updateByExample(BsUser record, BsUserExample example);
}