package com.et59.cus.domain.dao;

import java.util.List;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import com.et59.cus.domain.entity.BsUser;
import com.et59.cus.domain.entity.BsUserExample;

public class BsUserDAOImpl extends SqlMapClientDaoSupport implements BsUserDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_user
	 * @abatorgenerated
	 */
	public BsUserDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_user
	 * @abatorgenerated
	 */
	public void insert(BsUser record) {
		getSqlMapClientTemplate().insert("bs_user.abatorgenerated_insert",
				record);
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_user
	 * @abatorgenerated
	 */
	public int updateByPrimaryKey(BsUser record) {
		int rows = getSqlMapClientTemplate().update(
				"bs_user.abatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_user
	 * @abatorgenerated
	 */
	public int updateByPrimaryKeySelective(BsUser record) {
		int rows = getSqlMapClientTemplate().update(
				"bs_user.abatorgenerated_updateByPrimaryKeySelective", record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_user
	 * @abatorgenerated
	 */
	@SuppressWarnings("unchecked")
	public List<BsUser> selectByExample(BsUserExample example) {
		List<BsUser> list = (List<BsUser>) getSqlMapClientTemplate()
				.queryForList("bs_user.abatorgenerated_selectByExample",
						example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_user
	 * @abatorgenerated
	 */
	public BsUser selectByPrimaryKey(Integer id) {
		BsUser key = new BsUser();
		key.setId(id);
		BsUser record = (BsUser) getSqlMapClientTemplate().queryForObject(
				"bs_user.abatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_user
	 * @abatorgenerated
	 */
	public int deleteByExample(BsUserExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"bs_user.abatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_user
	 * @abatorgenerated
	 */
	public int deleteByPrimaryKey(Integer id) {
		BsUser key = new BsUser();
		key.setId(id);
		int rows = getSqlMapClientTemplate().delete(
				"bs_user.abatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_user
	 * @abatorgenerated
	 */
	public int countByExample(BsUserExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"bs_user.abatorgenerated_countByExample", example);
		return count;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_user
	 * @abatorgenerated
	 */
	public int updateByExampleSelective(BsUser record, BsUserExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"bs_user.abatorgenerated_updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_user
	 * @abatorgenerated
	 */
	public int updateByExample(BsUser record, BsUserExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"bs_user.abatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This class was generated by Abator for iBATIS. This class corresponds to the database table bs_user
	 * @abatorgenerated
	 */
	private static class UpdateByExampleParms extends BsUserExample {
		private Object record;

		public UpdateByExampleParms(Object record, BsUserExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}