package com.et59.cus.domain.dao;

import java.util.List;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import com.et59.cus.domain.entity.BsUserservice;
import com.et59.cus.domain.entity.BsUserserviceExample;

public class BsUserserviceDAOImpl extends SqlMapClientDaoSupport implements BsUserserviceDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_userservice
	 * @abatorgenerated
	 */
	public BsUserserviceDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_userservice
	 * @abatorgenerated
	 */
	public void insert(BsUserservice record) {
		getSqlMapClientTemplate().insert(
				"bs_userservice.abatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_userservice
	 * @abatorgenerated
	 */
	public int updateByPrimaryKey(BsUserservice record) {
		int rows = getSqlMapClientTemplate().update(
				"bs_userservice.abatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_userservice
	 * @abatorgenerated
	 */
	public int updateByPrimaryKeySelective(BsUserservice record) {
		int rows = getSqlMapClientTemplate().update(
				"bs_userservice.abatorgenerated_updateByPrimaryKeySelective",
				record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_userservice
	 * @abatorgenerated
	 */
	@SuppressWarnings("unchecked")
	public List<BsUserservice> selectByExample(BsUserserviceExample example) {
		List<BsUserservice> list = (List<BsUserservice>) getSqlMapClientTemplate()
				.queryForList("bs_userservice.abatorgenerated_selectByExample",
						example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_userservice
	 * @abatorgenerated
	 */
	public BsUserservice selectByPrimaryKey(Integer id) {
		BsUserservice key = new BsUserservice();
		key.setId(id);
		BsUserservice record = (BsUserservice) getSqlMapClientTemplate()
				.queryForObject(
						"bs_userservice.abatorgenerated_selectByPrimaryKey",
						key);
		return record;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_userservice
	 * @abatorgenerated
	 */
	public int deleteByExample(BsUserserviceExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"bs_userservice.abatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_userservice
	 * @abatorgenerated
	 */
	public int deleteByPrimaryKey(Integer id) {
		BsUserservice key = new BsUserservice();
		key.setId(id);
		int rows = getSqlMapClientTemplate().delete(
				"bs_userservice.abatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_userservice
	 * @abatorgenerated
	 */
	public int countByExample(BsUserserviceExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"bs_userservice.abatorgenerated_countByExample", example);
		return count;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_userservice
	 * @abatorgenerated
	 */
	public int updateByExampleSelective(BsUserservice record,
			BsUserserviceExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"bs_userservice.abatorgenerated_updateByExampleSelective",
				parms);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_userservice
	 * @abatorgenerated
	 */
	public int updateByExample(BsUserservice record,
			BsUserserviceExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"bs_userservice.abatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This class was generated by Abator for iBATIS. This class corresponds to the database table bs_userservice
	 * @abatorgenerated
	 */
	private static class UpdateByExampleParms extends BsUserserviceExample {
		private Object record;

		public UpdateByExampleParms(Object record, BsUserserviceExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}