package com.et59.cus.domain.dao;

import com.et59.cus.domain.entity.OpenOauth;
import com.et59.cus.domain.entity.OpenOauthExample;
import java.util.List;

public interface OpenOauthDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table open_oauth
	 * @abatorgenerated
	 */
	void insert(OpenOauth record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table open_oauth
	 * @abatorgenerated
	 */
	int updateByPrimaryKey(OpenOauth record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table open_oauth
	 * @abatorgenerated
	 */
	int updateByPrimaryKeySelective(OpenOauth record);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table open_oauth
	 * @abatorgenerated
	 */
	List<OpenOauth> selectByExample(OpenOauthExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table open_oauth
	 * @abatorgenerated
	 */
	OpenOauth selectByPrimaryKey(Long id);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table open_oauth
	 * @abatorgenerated
	 */
	int deleteByExample(OpenOauthExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table open_oauth
	 * @abatorgenerated
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table open_oauth
	 * @abatorgenerated
	 */
	int countByExample(OpenOauthExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table open_oauth
	 * @abatorgenerated
	 */
	int updateByExampleSelective(OpenOauth record, OpenOauthExample example);

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table open_oauth
	 * @abatorgenerated
	 */
	int updateByExample(OpenOauth record, OpenOauthExample example);
}