package com.et59.cus.domain.dao;

import com.et59.cus.domain.entity.OpenLog;
import com.et59.cus.domain.entity.OpenLogExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class OpenLogDAOImpl extends SqlMapClientDaoSupport implements OpenLogDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table open_log
	 * @abatorgenerated
	 */
	public OpenLogDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table open_log
	 * @abatorgenerated
	 */
	public void insert(OpenLog record) {
		getSqlMapClientTemplate().insert("open_log.abatorgenerated_insert",
				record);
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table open_log
	 * @abatorgenerated
	 */
	public int updateByPrimaryKey(OpenLog record) {
		int rows = getSqlMapClientTemplate().update(
				"open_log.abatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table open_log
	 * @abatorgenerated
	 */
	public int updateByPrimaryKeySelective(OpenLog record) {
		int rows = getSqlMapClientTemplate().update(
				"open_log.abatorgenerated_updateByPrimaryKeySelective", record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table open_log
	 * @abatorgenerated
	 */
	@SuppressWarnings("unchecked")
	public List<OpenLog> selectByExample(OpenLogExample example) {
		List<OpenLog> list = (List<OpenLog>) getSqlMapClientTemplate()
				.queryForList("open_log.abatorgenerated_selectByExample",
						example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table open_log
	 * @abatorgenerated
	 */
	public OpenLog selectByPrimaryKey(Long id) {
		OpenLog key = new OpenLog();
		key.setId(id);
		OpenLog record = (OpenLog) getSqlMapClientTemplate().queryForObject(
				"open_log.abatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table open_log
	 * @abatorgenerated
	 */
	public int deleteByExample(OpenLogExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"open_log.abatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table open_log
	 * @abatorgenerated
	 */
	public int deleteByPrimaryKey(Long id) {
		OpenLog key = new OpenLog();
		key.setId(id);
		int rows = getSqlMapClientTemplate().delete(
				"open_log.abatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table open_log
	 * @abatorgenerated
	 */
	public int countByExample(OpenLogExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"open_log.abatorgenerated_countByExample", example);
		return count;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table open_log
	 * @abatorgenerated
	 */
	public int updateByExampleSelective(OpenLog record, OpenLogExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"open_log.abatorgenerated_updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table open_log
	 * @abatorgenerated
	 */
	public int updateByExample(OpenLog record, OpenLogExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"open_log.abatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This class was generated by Abator for iBATIS. This class corresponds to the database table open_log
	 * @abatorgenerated
	 */
	private static class UpdateByExampleParms extends OpenLogExample {
		private Object record;

		public UpdateByExampleParms(Object record, OpenLogExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}