package com.et59.cus.domain.dao;

import com.et59.cus.domain.entity.OpenOauth;
import com.et59.cus.domain.entity.OpenOauthExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class OpenOauthDAOImpl extends SqlMapClientDaoSupport implements OpenOauthDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table open_oauth
	 * @abatorgenerated
	 */
	public OpenOauthDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table open_oauth
	 * @abatorgenerated
	 */
	public void insert(OpenOauth record) {
		getSqlMapClientTemplate().insert("open_oauth.abatorgenerated_insert",
				record);
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table open_oauth
	 * @abatorgenerated
	 */
	public int updateByPrimaryKey(OpenOauth record) {
		int rows = getSqlMapClientTemplate().update(
				"open_oauth.abatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table open_oauth
	 * @abatorgenerated
	 */
	public int updateByPrimaryKeySelective(OpenOauth record) {
		int rows = getSqlMapClientTemplate().update(
				"open_oauth.abatorgenerated_updateByPrimaryKeySelective",
				record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table open_oauth
	 * @abatorgenerated
	 */
	@SuppressWarnings("unchecked")
	public List<OpenOauth> selectByExample(OpenOauthExample example) {
		List<OpenOauth> list = (List<OpenOauth>) getSqlMapClientTemplate()
				.queryForList("open_oauth.abatorgenerated_selectByExample",
						example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table open_oauth
	 * @abatorgenerated
	 */
	public OpenOauth selectByPrimaryKey(Long id) {
		OpenOauth key = new OpenOauth();
		key.setId(id);
		OpenOauth record = (OpenOauth) getSqlMapClientTemplate()
				.queryForObject(
						"open_oauth.abatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table open_oauth
	 * @abatorgenerated
	 */
	public int deleteByExample(OpenOauthExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"open_oauth.abatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table open_oauth
	 * @abatorgenerated
	 */
	public int deleteByPrimaryKey(Long id) {
		OpenOauth key = new OpenOauth();
		key.setId(id);
		int rows = getSqlMapClientTemplate().delete(
				"open_oauth.abatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table open_oauth
	 * @abatorgenerated
	 */
	public int countByExample(OpenOauthExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"open_oauth.abatorgenerated_countByExample", example);
		return count;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table open_oauth
	 * @abatorgenerated
	 */
	public int updateByExampleSelective(OpenOauth record,
			OpenOauthExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"open_oauth.abatorgenerated_updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table open_oauth
	 * @abatorgenerated
	 */
	public int updateByExample(OpenOauth record, OpenOauthExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"open_oauth.abatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This class was generated by Abator for iBATIS. This class corresponds to the database table open_oauth
	 * @abatorgenerated
	 */
	private static class UpdateByExampleParms extends OpenOauthExample {
		private Object record;

		public UpdateByExampleParms(Object record, OpenOauthExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}