package com.et59.cus.domain.dao;

import com.et59.cus.domain.entity.OpenApp;
import com.et59.cus.domain.entity.OpenAppExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class OpenAppDAOImpl extends SqlMapClientDaoSupport implements OpenAppDAO {

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table open_app
	 * @abatorgenerated
	 */
	public OpenAppDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table open_app
	 * @abatorgenerated
	 */
	public void insert(OpenApp record) {
		getSqlMapClientTemplate().insert("open_app.abatorgenerated_insert",
				record);
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table open_app
	 * @abatorgenerated
	 */
	public int updateByPrimaryKey(OpenApp record) {
		int rows = getSqlMapClientTemplate().update(
				"open_app.abatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table open_app
	 * @abatorgenerated
	 */
	public int updateByPrimaryKeySelective(OpenApp record) {
		int rows = getSqlMapClientTemplate().update(
				"open_app.abatorgenerated_updateByPrimaryKeySelective", record);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table open_app
	 * @abatorgenerated
	 */
	@SuppressWarnings("unchecked")
	public List<OpenApp> selectByExample(OpenAppExample example) {
		List<OpenApp> list = (List<OpenApp>) getSqlMapClientTemplate()
				.queryForList("open_app.abatorgenerated_selectByExample",
						example);
		return list;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table open_app
	 * @abatorgenerated
	 */
	public OpenApp selectByPrimaryKey(Long id) {
		OpenApp key = new OpenApp();
		key.setId(id);
		OpenApp record = (OpenApp) getSqlMapClientTemplate().queryForObject(
				"open_app.abatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table open_app
	 * @abatorgenerated
	 */
	public int deleteByExample(OpenAppExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"open_app.abatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table open_app
	 * @abatorgenerated
	 */
	public int deleteByPrimaryKey(Long id) {
		OpenApp key = new OpenApp();
		key.setId(id);
		int rows = getSqlMapClientTemplate().delete(
				"open_app.abatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table open_app
	 * @abatorgenerated
	 */
	public int countByExample(OpenAppExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"open_app.abatorgenerated_countByExample", example);
		return count;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table open_app
	 * @abatorgenerated
	 */
	public int updateByExampleSelective(OpenApp record, OpenAppExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"open_app.abatorgenerated_updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table open_app
	 * @abatorgenerated
	 */
	public int updateByExample(OpenApp record, OpenAppExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"open_app.abatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This class was generated by Abator for iBATIS. This class corresponds to the database table open_app
	 * @abatorgenerated
	 */
	private static class UpdateByExampleParms extends OpenAppExample {
		private Object record;

		public UpdateByExampleParms(Object record, OpenAppExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}