package com.et59.cus.domain.dao;

import com.et59.cus.domain.entity.TCollege;
import com.et59.cus.domain.entity.TCollegeExample;
import java.util.List;

public interface TCollegeDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_college
	 * @ibatorgenerated  Wed Jan 07 10:29:04 CST 2015
	 */
	int countByExample(TCollegeExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_college
	 * @ibatorgenerated  Wed Jan 07 10:29:04 CST 2015
	 */
	int deleteByExample(TCollegeExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_college
	 * @ibatorgenerated  Wed Jan 07 10:29:04 CST 2015
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_college
	 * @ibatorgenerated  Wed Jan 07 10:29:04 CST 2015
	 */
	void insert(TCollege record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_college
	 * @ibatorgenerated  Wed Jan 07 10:29:04 CST 2015
	 */
	void insertSelective(TCollege record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_college
	 * @ibatorgenerated  Wed Jan 07 10:29:04 CST 2015
	 */
	List selectByExample(TCollegeExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_college
	 * @ibatorgenerated  Wed Jan 07 10:29:04 CST 2015
	 */
	TCollege selectByPrimaryKey(Long id);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_college
	 * @ibatorgenerated  Wed Jan 07 10:29:04 CST 2015
	 */
	int updateByExampleSelective(TCollege record, TCollegeExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_college
	 * @ibatorgenerated  Wed Jan 07 10:29:04 CST 2015
	 */
	int updateByExample(TCollege record, TCollegeExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_college
	 * @ibatorgenerated  Wed Jan 07 10:29:04 CST 2015
	 */
	int updateByPrimaryKeySelective(TCollege record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_college
	 * @ibatorgenerated  Wed Jan 07 10:29:04 CST 2015
	 */
	int updateByPrimaryKey(TCollege record);
}