package com.et59.cus.domain.dao;

import com.et59.cus.domain.entity.TCollege;
import com.et59.cus.domain.entity.TCollegeExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class TCollegeDAOImpl extends SqlMapClientDaoSupport implements TCollegeDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_college
	 * @ibatorgenerated  Wed Jan 07 10:29:04 CST 2015
	 */
	public TCollegeDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_college
	 * @ibatorgenerated  Wed Jan 07 10:29:04 CST 2015
	 */
	public int countByExample(TCollegeExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"t_college.ibatorgenerated_countByExample", example);
		return count.intValue();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_college
	 * @ibatorgenerated  Wed Jan 07 10:29:04 CST 2015
	 */
	public int deleteByExample(TCollegeExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"t_college.ibatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_college
	 * @ibatorgenerated  Wed Jan 07 10:29:04 CST 2015
	 */
	public int deleteByPrimaryKey(Long id) {
		TCollege key = new TCollege();
		key.setId(id);
		int rows = getSqlMapClientTemplate().delete(
				"t_college.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_college
	 * @ibatorgenerated  Wed Jan 07 10:29:04 CST 2015
	 */
	public void insert(TCollege record) {
		getSqlMapClientTemplate().insert("t_college.ibatorgenerated_insert",
				record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_college
	 * @ibatorgenerated  Wed Jan 07 10:29:04 CST 2015
	 */
	public void insertSelective(TCollege record) {
		getSqlMapClientTemplate().insert(
				"t_college.ibatorgenerated_insertSelective", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_college
	 * @ibatorgenerated  Wed Jan 07 10:29:04 CST 2015
	 */
	public List selectByExample(TCollegeExample example) {
		List list = getSqlMapClientTemplate().queryForList(
				"t_college.ibatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_college
	 * @ibatorgenerated  Wed Jan 07 10:29:04 CST 2015
	 */
	public TCollege selectByPrimaryKey(Long id) {
		TCollege key = new TCollege();
		key.setId(id);
		TCollege record = (TCollege) getSqlMapClientTemplate().queryForObject(
				"t_college.ibatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_college
	 * @ibatorgenerated  Wed Jan 07 10:29:04 CST 2015
	 */
	public int updateByExampleSelective(TCollege record, TCollegeExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"t_college.ibatorgenerated_updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_college
	 * @ibatorgenerated  Wed Jan 07 10:29:04 CST 2015
	 */
	public int updateByExample(TCollege record, TCollegeExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"t_college.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_college
	 * @ibatorgenerated  Wed Jan 07 10:29:04 CST 2015
	 */
	public int updateByPrimaryKeySelective(TCollege record) {
		int rows = getSqlMapClientTemplate()
				.update("t_college.ibatorgenerated_updateByPrimaryKeySelective",
						record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_college
	 * @ibatorgenerated  Wed Jan 07 10:29:04 CST 2015
	 */
	public int updateByPrimaryKey(TCollege record) {
		int rows = getSqlMapClientTemplate().update(
				"t_college.ibatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table t_college
	 * @ibatorgenerated  Wed Jan 07 10:29:04 CST 2015
	 */
	private static class UpdateByExampleParms extends TCollegeExample {
		private Object record;

		public UpdateByExampleParms(Object record, TCollegeExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}