package com.et59.cus.domain.dao;

import com.et59.cus.domain.entity.TDepartment;
import com.et59.cus.domain.entity.TDepartmentExample;
import com.et59.cus.domain.entity.TDepartmentWithBLOBs;
import java.util.List;

public interface TDepartmentDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_department
	 * @ibatorgenerated  Thu Mar 26 17:53:45 CST 2015
	 */
	int countByExample(TDepartmentExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_department
	 * @ibatorgenerated  Thu Mar 26 17:53:45 CST 2015
	 */
	int deleteByExample(TDepartmentExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_department
	 * @ibatorgenerated  Thu Mar 26 17:53:45 CST 2015
	 */
	int deleteByPrimaryKey(Long departmentid);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_department
	 * @ibatorgenerated  Thu Mar 26 17:53:45 CST 2015
	 */
	void insert(TDepartmentWithBLOBs record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_department
	 * @ibatorgenerated  Thu Mar 26 17:53:45 CST 2015
	 */
	void insertSelective(TDepartmentWithBLOBs record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_department
	 * @ibatorgenerated  Thu Mar 26 17:53:45 CST 2015
	 */
	List selectByExampleWithBLOBs(TDepartmentExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_department
	 * @ibatorgenerated  Thu Mar 26 17:53:45 CST 2015
	 */
	List selectByExampleWithoutBLOBs(TDepartmentExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_department
	 * @ibatorgenerated  Thu Mar 26 17:53:45 CST 2015
	 */
	TDepartmentWithBLOBs selectByPrimaryKey(Long departmentid);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_department
	 * @ibatorgenerated  Thu Mar 26 17:53:45 CST 2015
	 */
	int updateByExampleSelective(TDepartmentWithBLOBs record,
			TDepartmentExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_department
	 * @ibatorgenerated  Thu Mar 26 17:53:45 CST 2015
	 */
	int updateByExample(TDepartmentWithBLOBs record, TDepartmentExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_department
	 * @ibatorgenerated  Thu Mar 26 17:53:45 CST 2015
	 */
	int updateByExample(TDepartment record, TDepartmentExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_department
	 * @ibatorgenerated  Thu Mar 26 17:53:45 CST 2015
	 */
	int updateByPrimaryKeySelective(TDepartmentWithBLOBs record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_department
	 * @ibatorgenerated  Thu Mar 26 17:53:45 CST 2015
	 */
	int updateByPrimaryKey(TDepartmentWithBLOBs record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_department
	 * @ibatorgenerated  Thu Mar 26 17:53:45 CST 2015
	 */
	int updateByPrimaryKey(TDepartment record);
}