package com.et59.cus.domain.dao;

import com.et59.cus.domain.entity.TDepartment;
import com.et59.cus.domain.entity.TDepartmentExample;
import com.et59.cus.domain.entity.TDepartmentWithBLOBs;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class TDepartmentDAOImpl extends SqlMapClientDaoSupport implements TDepartmentDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_department
	 * @ibatorgenerated  Thu Mar 26 17:53:45 CST 2015
	 */
	public TDepartmentDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_department
	 * @ibatorgenerated  Thu Mar 26 17:53:45 CST 2015
	 */
	public int countByExample(TDepartmentExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"t_department.ibatorgenerated_countByExample", example);
		return count.intValue();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_department
	 * @ibatorgenerated  Thu Mar 26 17:53:45 CST 2015
	 */
	public int deleteByExample(TDepartmentExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"t_department.ibatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_department
	 * @ibatorgenerated  Thu Mar 26 17:53:45 CST 2015
	 */
	public int deleteByPrimaryKey(Long departmentid) {
		TDepartment key = new TDepartment();
		key.setDepartmentid(departmentid);
		int rows = getSqlMapClientTemplate().delete(
				"t_department.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_department
	 * @ibatorgenerated  Thu Mar 26 17:53:45 CST 2015
	 */
	public void insert(TDepartmentWithBLOBs record) {
		getSqlMapClientTemplate().insert("t_department.ibatorgenerated_insert",
				record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_department
	 * @ibatorgenerated  Thu Mar 26 17:53:45 CST 2015
	 */
	public void insertSelective(TDepartmentWithBLOBs record) {
		getSqlMapClientTemplate().insert(
				"t_department.ibatorgenerated_insertSelective", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_department
	 * @ibatorgenerated  Thu Mar 26 17:53:45 CST 2015
	 */
	public List selectByExampleWithBLOBs(TDepartmentExample example) {
		List list = getSqlMapClientTemplate().queryForList(
				"t_department.ibatorgenerated_selectByExampleWithBLOBs",
				example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_department
	 * @ibatorgenerated  Thu Mar 26 17:53:45 CST 2015
	 */
	public List selectByExampleWithoutBLOBs(TDepartmentExample example) {
		List list = getSqlMapClientTemplate().queryForList(
				"t_department.ibatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_department
	 * @ibatorgenerated  Thu Mar 26 17:53:45 CST 2015
	 */
	public TDepartmentWithBLOBs selectByPrimaryKey(Long departmentid) {
		TDepartment key = new TDepartment();
		key.setDepartmentid(departmentid);
		TDepartmentWithBLOBs record = (TDepartmentWithBLOBs) getSqlMapClientTemplate()
				.queryForObject(
						"t_department.ibatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_department
	 * @ibatorgenerated  Thu Mar 26 17:53:45 CST 2015
	 */
	public int updateByExampleSelective(TDepartmentWithBLOBs record,
			TDepartmentExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"t_department.ibatorgenerated_updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_department
	 * @ibatorgenerated  Thu Mar 26 17:53:45 CST 2015
	 */
	public int updateByExample(TDepartmentWithBLOBs record,
			TDepartmentExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"t_department.ibatorgenerated_updateByExampleWithBLOBs", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_department
	 * @ibatorgenerated  Thu Mar 26 17:53:45 CST 2015
	 */
	public int updateByExample(TDepartment record, TDepartmentExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"t_department.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_department
	 * @ibatorgenerated  Thu Mar 26 17:53:45 CST 2015
	 */
	public int updateByPrimaryKeySelective(TDepartmentWithBLOBs record) {
		int rows = getSqlMapClientTemplate().update(
				"t_department.ibatorgenerated_updateByPrimaryKeySelective",
				record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_department
	 * @ibatorgenerated  Thu Mar 26 17:53:45 CST 2015
	 */
	public int updateByPrimaryKey(TDepartmentWithBLOBs record) {
		int rows = getSqlMapClientTemplate().update(
				"t_department.ibatorgenerated_updateByPrimaryKeyWithBLOBs",
				record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_department
	 * @ibatorgenerated  Thu Mar 26 17:53:45 CST 2015
	 */
	public int updateByPrimaryKey(TDepartment record) {
		int rows = getSqlMapClientTemplate().update(
				"t_department.ibatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table t_department
	 * @ibatorgenerated  Thu Mar 26 17:53:45 CST 2015
	 */
	private static class UpdateByExampleParms extends TDepartmentExample {
		private Object record;

		public UpdateByExampleParms(Object record, TDepartmentExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}