package com.et59.cus.domain.dao;

import com.et59.cus.domain.entity.TDictionary;
import com.et59.cus.domain.entity.TDictionaryExample;
import java.util.List;

public interface TDictionaryDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_dictionary
	 * @ibatorgenerated  Sun Feb 22 22:16:26 CST 2015
	 */
	int countByExample(TDictionaryExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_dictionary
	 * @ibatorgenerated  Sun Feb 22 22:16:26 CST 2015
	 */
	int deleteByExample(TDictionaryExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_dictionary
	 * @ibatorgenerated  Sun Feb 22 22:16:26 CST 2015
	 */
	int deleteByPrimaryKey(Integer dictionaryid);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_dictionary
	 * @ibatorgenerated  Sun Feb 22 22:16:26 CST 2015
	 */
	void insert(TDictionary record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_dictionary
	 * @ibatorgenerated  Sun Feb 22 22:16:26 CST 2015
	 */
	void insertSelective(TDictionary record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_dictionary
	 * @ibatorgenerated  Sun Feb 22 22:16:26 CST 2015
	 */
	List selectByExample(TDictionaryExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_dictionary
	 * @ibatorgenerated  Sun Feb 22 22:16:26 CST 2015
	 */
	TDictionary selectByPrimaryKey(Integer dictionaryid);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_dictionary
	 * @ibatorgenerated  Sun Feb 22 22:16:26 CST 2015
	 */
	int updateByExampleSelective(TDictionary record, TDictionaryExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_dictionary
	 * @ibatorgenerated  Sun Feb 22 22:16:26 CST 2015
	 */
	int updateByExample(TDictionary record, TDictionaryExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_dictionary
	 * @ibatorgenerated  Sun Feb 22 22:16:26 CST 2015
	 */
	int updateByPrimaryKeySelective(TDictionary record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_dictionary
	 * @ibatorgenerated  Sun Feb 22 22:16:26 CST 2015
	 */
	int updateByPrimaryKey(TDictionary record);
}