package com.et59.cus.domain.dao;

import java.util.List;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import com.et59.cus.domain.entity.TDownload;
import com.et59.cus.domain.entity.TDownloadExample;

public class TDownloadDAOImpl extends SqlMapClientDaoSupport implements
		TDownloadDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table t_download
	 * 
	 * @ibatorgenerated Thu Mar 05 17:12:45 CST 2015
	 */
	public TDownloadDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table t_download
	 * 
	 * @ibatorgenerated Thu Mar 05 17:12:45 CST 2015
	 */
	public int countByExample(TDownloadExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"t_download.ibatorgenerated_countByExample", example);
		return count.intValue();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table t_download
	 * 
	 * @ibatorgenerated Thu Mar 05 17:12:45 CST 2015
	 */
	public int deleteByExample(TDownloadExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"t_download.ibatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table t_download
	 * 
	 * @ibatorgenerated Thu Mar 05 17:12:45 CST 2015
	 */
	public int deleteByPrimaryKey(Long downloadid) {
		TDownload key = new TDownload();
		key.setDownloadid(downloadid);
		int rows = getSqlMapClientTemplate().delete(
				"t_download.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table t_download
	 * 
	 * @ibatorgenerated Thu Mar 05 17:12:45 CST 2015
	 */
	public Long insert(TDownload record) {
		return (Long) getSqlMapClientTemplate().insert(
				"t_download.ibatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table t_download
	 * 
	 * @ibatorgenerated Thu Mar 05 17:12:45 CST 2015
	 */
	public void insertSelective(TDownload record) {
		getSqlMapClientTemplate().insert(
				"t_download.ibatorgenerated_insertSelective", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table t_download
	 * 
	 * @ibatorgenerated Thu Mar 05 17:12:45 CST 2015
	 */
	public List selectByExample(TDownloadExample example) {
		List list = getSqlMapClientTemplate().queryForList(
				"t_download.ibatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table t_download
	 * 
	 * @ibatorgenerated Thu Mar 05 17:12:45 CST 2015
	 */
	public TDownload selectByPrimaryKey(Long downloadid) {
		TDownload key = new TDownload();
		key.setDownloadid(downloadid);
		TDownload record = (TDownload) getSqlMapClientTemplate()
				.queryForObject(
						"t_download.ibatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table t_download
	 * 
	 * @ibatorgenerated Thu Mar 05 17:12:45 CST 2015
	 */
	public int updateByExampleSelective(TDownload record,
			TDownloadExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"t_download.ibatorgenerated_updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table t_download
	 * 
	 * @ibatorgenerated Thu Mar 05 17:12:45 CST 2015
	 */
	public int updateByExample(TDownload record, TDownloadExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"t_download.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table t_download
	 * 
	 * @ibatorgenerated Thu Mar 05 17:12:45 CST 2015
	 */
	public int updateByPrimaryKeySelective(TDownload record) {
		int rows = getSqlMapClientTemplate().update(
				"t_download.ibatorgenerated_updateByPrimaryKeySelective",
				record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table t_download
	 * 
	 * @ibatorgenerated Thu Mar 05 17:12:45 CST 2015
	 */
	public int updateByPrimaryKey(TDownload record) {
		int rows = getSqlMapClientTemplate().update(
				"t_download.ibatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds
	 * to the database table t_download
	 * 
	 * @ibatorgenerated Thu Mar 05 17:12:45 CST 2015
	 */
	private static class UpdateByExampleParms extends TDownloadExample {
		private Object record;

		public UpdateByExampleParms(Object record, TDownloadExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}