package com.et59.cus.domain.dao;

import java.util.List;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import com.et59.cus.domain.entity.TPaper;
import com.et59.cus.domain.entity.TPaperExample;

public class TPaperDAOImpl extends SqlMapClientDaoSupport implements TPaperDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table t_paper
	 *
	 * @ibatorgenerated Mon Feb 16 17:46:03 CST 2015
	 */
	public TPaperDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table t_paper
	 *
	 * @ibatorgenerated Mon Feb 16 17:46:03 CST 2015
	 */
	public int countByExample(TPaperExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"t_paper.ibatorgenerated_countByExample", example);
		return count.intValue();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table t_paper
	 *
	 * @ibatorgenerated Mon Feb 16 17:46:03 CST 2015
	 */
	public int deleteByExample(TPaperExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"t_paper.ibatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table t_paper
	 *
	 * @ibatorgenerated Mon Feb 16 17:46:03 CST 2015
	 */
	public int deleteByPrimaryKey(Long paperid) {
		TPaper key = new TPaper();
		key.setPaperid(paperid);
		int rows = getSqlMapClientTemplate().delete(
				"t_paper.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table t_paper
	 *
	 * @ibatorgenerated Mon Feb 16 17:46:03 CST 2015
	 */
	public void insertSelective(TPaper record) {
		getSqlMapClientTemplate().insert(
				"t_paper.ibatorgenerated_insertSelective", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table t_paper
	 *
	 * @ibatorgenerated Mon Feb 16 17:46:03 CST 2015
	 */
	public List selectByExample(TPaperExample example) {
		List list = getSqlMapClientTemplate().queryForList(
				"t_paper.ibatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table t_paper
	 *
	 * @ibatorgenerated Mon Feb 16 17:46:03 CST 2015
	 */
	public TPaper selectByPrimaryKey(Long paperid) {
		TPaper key = new TPaper();
		key.setPaperid(paperid);
		TPaper record = (TPaper) getSqlMapClientTemplate().queryForObject(
				"t_paper.ibatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table t_paper
	 *
	 * @ibatorgenerated Mon Feb 16 17:46:03 CST 2015
	 */
	public int updateByExampleSelective(TPaper record, TPaperExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"t_paper.ibatorgenerated_updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table t_paper
	 *
	 * @ibatorgenerated Mon Feb 16 17:46:03 CST 2015
	 */
	public int updateByExample(TPaper record, TPaperExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"t_paper.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table t_paper
	 *
	 * @ibatorgenerated Mon Feb 16 17:46:03 CST 2015
	 */
	public int updateByPrimaryKeySelective(TPaper record) {
		int rows = getSqlMapClientTemplate().update(
				"t_paper.ibatorgenerated_updateByPrimaryKeySelective", record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table t_paper
	 *
	 * @ibatorgenerated Mon Feb 16 17:46:03 CST 2015
	 */
	public int updateByPrimaryKey(TPaper record) {
		int rows = getSqlMapClientTemplate().update(
				"t_paper.ibatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds
	 * to the database table t_paper
	 *
	 * @ibatorgenerated Mon Feb 16 17:46:03 CST 2015
	 */
	private static class UpdateByExampleParms extends TPaperExample {
		private Object record;

		public UpdateByExampleParms(Object record, TPaperExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}

	// WLT
	public Long insert(TPaper record) {
		return (Long) getSqlMapClientTemplate().insert(
				"t_paper.ibatorgenerated_insert", record);
	}

}