package com.et59.cus.domain.dao;

import java.util.List;

import com.et59.cus.domain.entity.TPaper;
import com.et59.cus.domain.entity.TPaperExample;

public interface TPaperDAO {
	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table t_paper
	 *
	 * @ibatorgenerated Mon Feb 16 17:46:03 CST 2015
	 */
	int countByExample(TPaperExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table t_paper
	 *
	 * @ibatorgenerated Mon Feb 16 17:46:03 CST 2015
	 */
	int deleteByExample(TPaperExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table t_paper
	 *
	 * @ibatorgenerated Mon Feb 16 17:46:03 CST 2015
	 */
	int deleteByPrimaryKey(Long paperid);

	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table t_paper
	 *
	 * @ibatorgenerated Mon Feb 16 17:46:03 CST 2015
	 */
	Long insert(TPaper record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table t_paper
	 *
	 * @ibatorgenerated Mon Feb 16 17:46:03 CST 2015
	 */
	void insertSelective(TPaper record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table t_paper
	 *
	 * @ibatorgenerated Mon Feb 16 17:46:03 CST 2015
	 */
	List selectByExample(TPaperExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table t_paper
	 *
	 * @ibatorgenerated Mon Feb 16 17:46:03 CST 2015
	 */
	TPaper selectByPrimaryKey(Long paperid);

	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table t_paper
	 *
	 * @ibatorgenerated Mon Feb 16 17:46:03 CST 2015
	 */
	int updateByExampleSelective(TPaper record, TPaperExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table t_paper
	 *
	 * @ibatorgenerated Mon Feb 16 17:46:03 CST 2015
	 */
	int updateByExample(TPaper record, TPaperExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table t_paper
	 *
	 * @ibatorgenerated Mon Feb 16 17:46:03 CST 2015
	 */
	int updateByPrimaryKeySelective(TPaper record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table t_paper
	 *
	 * @ibatorgenerated Mon Feb 16 17:46:03 CST 2015
	 */
	int updateByPrimaryKey(TPaper record);
}