package com.et59.cus.domain.dao;

import com.et59.cus.domain.entity.TRoleMenu;
import com.et59.cus.domain.entity.TRoleMenuExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class TRoleMenuDAOImpl extends SqlMapClientDaoSupport implements TRoleMenuDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_role_menu
     *
     * @ibatorgenerated Sun Feb 22 20:19:02 CST 2015
     */
    public TRoleMenuDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_role_menu
     *
     * @ibatorgenerated Sun Feb 22 20:19:02 CST 2015
     */
    public int countByExample(TRoleMenuExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("t_role_menu.ibatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_role_menu
     *
     * @ibatorgenerated Sun Feb 22 20:19:02 CST 2015
     */
    public int deleteByExample(TRoleMenuExample example) {
        int rows = getSqlMapClientTemplate().delete("t_role_menu.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_role_menu
     *
     * @ibatorgenerated Sun Feb 22 20:19:02 CST 2015
     */
    public int deleteByPrimaryKey(Integer id) {
        TRoleMenu key = new TRoleMenu();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("t_role_menu.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_role_menu
     *
     * @ibatorgenerated Sun Feb 22 20:19:02 CST 2015
     */
    public void insert(TRoleMenu record) {
        getSqlMapClientTemplate().insert("t_role_menu.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_role_menu
     *
     * @ibatorgenerated Sun Feb 22 20:19:02 CST 2015
     */
    public void insertSelective(TRoleMenu record) {
        getSqlMapClientTemplate().insert("t_role_menu.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_role_menu
     *
     * @ibatorgenerated Sun Feb 22 20:19:02 CST 2015
     */
    public List selectByExample(TRoleMenuExample example) {
        List list = getSqlMapClientTemplate().queryForList("t_role_menu.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_role_menu
     *
     * @ibatorgenerated Sun Feb 22 20:19:02 CST 2015
     */
    public TRoleMenu selectByPrimaryKey(Integer id) {
        TRoleMenu key = new TRoleMenu();
        key.setId(id);
        TRoleMenu record = (TRoleMenu) getSqlMapClientTemplate().queryForObject("t_role_menu.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_role_menu
     *
     * @ibatorgenerated Sun Feb 22 20:19:02 CST 2015
     */
    public int updateByExampleSelective(TRoleMenu record, TRoleMenuExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("t_role_menu.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_role_menu
     *
     * @ibatorgenerated Sun Feb 22 20:19:02 CST 2015
     */
    public int updateByExample(TRoleMenu record, TRoleMenuExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("t_role_menu.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_role_menu
     *
     * @ibatorgenerated Sun Feb 22 20:19:02 CST 2015
     */
    public int updateByPrimaryKeySelective(TRoleMenu record) {
        int rows = getSqlMapClientTemplate().update("t_role_menu.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_role_menu
     *
     * @ibatorgenerated Sun Feb 22 20:19:02 CST 2015
     */
    public int updateByPrimaryKey(TRoleMenu record) {
        int rows = getSqlMapClientTemplate().update("t_role_menu.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table t_role_menu
     *
     * @ibatorgenerated Sun Feb 22 20:19:02 CST 2015
     */
    private static class UpdateByExampleParms extends TRoleMenuExample {
        private Object record;

        public UpdateByExampleParms(Object record, TRoleMenuExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}