package com.et59.cus.domain.dao;

import com.et59.cus.domain.entity.TStudent;
import com.et59.cus.domain.entity.TStudentExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class TStudentDAOImpl extends SqlMapClientDaoSupport implements TStudentDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_student
     *
     * @ibatorgenerated Sat Jan 03 10:14:52 CST 2015
     */
    public TStudentDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_student
     *
     * @ibatorgenerated Sat Jan 03 10:14:52 CST 2015
     */
    public int countByExample(TStudentExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("t_student.ibatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_student
     *
     * @ibatorgenerated Sat Jan 03 10:14:52 CST 2015
     */
    public int deleteByExample(TStudentExample example) {
        int rows = getSqlMapClientTemplate().delete("t_student.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_student
     *
     * @ibatorgenerated Sat Jan 03 10:14:52 CST 2015
     */
    public int deleteByPrimaryKey(Long id) {
        TStudent key = new TStudent();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("t_student.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_student
     *
     * @ibatorgenerated Sat Jan 03 10:14:52 CST 2015
     */
    public void insert(TStudent record) {
        getSqlMapClientTemplate().insert("t_student.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_student
     *
     * @ibatorgenerated Sat Jan 03 10:14:52 CST 2015
     */
    public void insertSelective(TStudent record) {
        getSqlMapClientTemplate().insert("t_student.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_student
     *
     * @ibatorgenerated Sat Jan 03 10:14:52 CST 2015
     */
    public List selectByExample(TStudentExample example) {
        List list = getSqlMapClientTemplate().queryForList("t_student.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_student
     *
     * @ibatorgenerated Sat Jan 03 10:14:52 CST 2015
     */
    public TStudent selectByPrimaryKey(Long id) {
        TStudent key = new TStudent();
        key.setId(id);
        TStudent record = (TStudent) getSqlMapClientTemplate().queryForObject("t_student.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_student
     *
     * @ibatorgenerated Sat Jan 03 10:14:52 CST 2015
     */
    public int updateByExampleSelective(TStudent record, TStudentExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("t_student.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_student
     *
     * @ibatorgenerated Sat Jan 03 10:14:52 CST 2015
     */
    public int updateByExample(TStudent record, TStudentExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("t_student.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_student
     *
     * @ibatorgenerated Sat Jan 03 10:14:52 CST 2015
     */
    public int updateByPrimaryKeySelective(TStudent record) {
        int rows = getSqlMapClientTemplate().update("t_student.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_student
     *
     * @ibatorgenerated Sat Jan 03 10:14:52 CST 2015
     */
    public int updateByPrimaryKey(TStudent record) {
        int rows = getSqlMapClientTemplate().update("t_student.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table t_student
     *
     * @ibatorgenerated Sat Jan 03 10:14:52 CST 2015
     */
    private static class UpdateByExampleParms extends TStudentExample {
        private Object record;

        public UpdateByExampleParms(Object record, TStudentExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}