package com.et59.cus.domain.dao;

import com.et59.cus.domain.entity.TStudent;
import com.et59.cus.domain.entity.TStudentExample;
import java.util.List;

public interface TStudentDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_student
     *
     * @ibatorgenerated Sat Jan 03 10:14:52 CST 2015
     */
    int countByExample(TStudentExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_student
     *
     * @ibatorgenerated Sat Jan 03 10:14:52 CST 2015
     */
    int deleteByExample(TStudentExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_student
     *
     * @ibatorgenerated Sat Jan 03 10:14:52 CST 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_student
     *
     * @ibatorgenerated Sat Jan 03 10:14:52 CST 2015
     */
    void insert(TStudent record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_student
     *
     * @ibatorgenerated Sat Jan 03 10:14:52 CST 2015
     */
    void insertSelective(TStudent record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_student
     *
     * @ibatorgenerated Sat Jan 03 10:14:52 CST 2015
     */
    List selectByExample(TStudentExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_student
     *
     * @ibatorgenerated Sat Jan 03 10:14:52 CST 2015
     */
    TStudent selectByPrimaryKey(Long id);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_student
     *
     * @ibatorgenerated Sat Jan 03 10:14:52 CST 2015
     */
    int updateByExampleSelective(TStudent record, TStudentExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_student
     *
     * @ibatorgenerated Sat Jan 03 10:14:52 CST 2015
     */
    int updateByExample(TStudent record, TStudentExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_student
     *
     * @ibatorgenerated Sat Jan 03 10:14:52 CST 2015
     */
    int updateByPrimaryKeySelective(TStudent record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_student
     *
     * @ibatorgenerated Sat Jan 03 10:14:52 CST 2015
     */
    int updateByPrimaryKey(TStudent record);
}