package com.et59.cus.domain.dao;

import java.util.List;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import com.et59.cus.domain.entity.TSubject;
import com.et59.cus.domain.entity.TSubjectExample;

public class TSubjectDAOImpl extends SqlMapClientDaoSupport implements
		TSubjectDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table t_subject
	 * 
	 * @ibatorgenerated Tue Mar 24 13:38:11 CST 2015
	 */
	public TSubjectDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table t_subject
	 * 
	 * @ibatorgenerated Tue Mar 24 13:38:11 CST 2015
	 */
	public int countByExample(TSubjectExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"t_subject.ibatorgenerated_countByExample", example);
		return count.intValue();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table t_subject
	 * 
	 * @ibatorgenerated Tue Mar 24 13:38:11 CST 2015
	 */
	public int deleteByExample(TSubjectExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"t_subject.ibatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table t_subject
	 * 
	 * @ibatorgenerated Tue Mar 24 13:38:11 CST 2015
	 */
	public int deleteByPrimaryKey(Long subjectid) {
		TSubject key = new TSubject();
		key.setSubjectid(subjectid);
		int rows = getSqlMapClientTemplate().delete(
				"t_subject.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table t_subject
	 * 
	 * @ibatorgenerated Tue Mar 24 13:38:11 CST 2015
	 */
	public void insertSelective(TSubject record) {
		getSqlMapClientTemplate().insert(
				"t_subject.ibatorgenerated_insertSelective", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table t_subject
	 * 
	 * @ibatorgenerated Tue Mar 24 13:38:11 CST 2015
	 */
	public List selectByExample(TSubjectExample example) {
		List list = getSqlMapClientTemplate().queryForList(
				"t_subject.ibatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table t_subject
	 * 
	 * @ibatorgenerated Tue Mar 24 13:38:11 CST 2015
	 */
	public TSubject selectByPrimaryKey(Long subjectid) {
		TSubject key = new TSubject();
		key.setSubjectid(subjectid);
		TSubject record = (TSubject) getSqlMapClientTemplate().queryForObject(
				"t_subject.ibatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table t_subject
	 * 
	 * @ibatorgenerated Tue Mar 24 13:38:11 CST 2015
	 */
	public int updateByExampleSelective(TSubject record, TSubjectExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"t_subject.ibatorgenerated_updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table t_subject
	 * 
	 * @ibatorgenerated Tue Mar 24 13:38:11 CST 2015
	 */
	public int updateByExample(TSubject record, TSubjectExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"t_subject.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table t_subject
	 * 
	 * @ibatorgenerated Tue Mar 24 13:38:11 CST 2015
	 */
	public int updateByPrimaryKeySelective(TSubject record) {
		int rows = getSqlMapClientTemplate()
				.update("t_subject.ibatorgenerated_updateByPrimaryKeySelective",
						record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method
	 * corresponds to the database table t_subject
	 * 
	 * @ibatorgenerated Tue Mar 24 13:38:11 CST 2015
	 */
	public int updateByPrimaryKey(TSubject record) {
		int rows = getSqlMapClientTemplate().update(
				"t_subject.ibatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds
	 * to the database table t_subject
	 * 
	 * @ibatorgenerated Tue Mar 24 13:38:11 CST 2015
	 */
	private static class UpdateByExampleParms extends TSubjectExample {
		private Object record;

		public UpdateByExampleParms(Object record, TSubjectExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}

	// WLT
	public Long insert(TSubject record) {
		return (Long) getSqlMapClientTemplate().insert(
				"t_subject.ibatorgenerated_insert", record);
	}
}