package com.et59.cus.domain.dao;

import com.et59.cus.domain.entity.TTeacherPaperExample;
import com.et59.cus.domain.entity.TTeacherPaperKey;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class TTeacherPaperDAOImpl extends SqlMapClientDaoSupport implements TTeacherPaperDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_teacher_paper
     *
     * @ibatorgenerated Tue Mar 03 17:43:02 CST 2015
     */
    public TTeacherPaperDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_teacher_paper
     *
     * @ibatorgenerated Tue Mar 03 17:43:02 CST 2015
     */
    public int countByExample(TTeacherPaperExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("t_teacher_paper.ibatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_teacher_paper
     *
     * @ibatorgenerated Tue Mar 03 17:43:02 CST 2015
     */
    public int deleteByExample(TTeacherPaperExample example) {
        int rows = getSqlMapClientTemplate().delete("t_teacher_paper.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_teacher_paper
     *
     * @ibatorgenerated Tue Mar 03 17:43:02 CST 2015
     */
    public int deleteByPrimaryKey(TTeacherPaperKey key) {
        int rows = getSqlMapClientTemplate().delete("t_teacher_paper.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_teacher_paper
     *
     * @ibatorgenerated Tue Mar 03 17:43:02 CST 2015
     */
    public void insert(TTeacherPaperKey record) {
        getSqlMapClientTemplate().insert("t_teacher_paper.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_teacher_paper
     *
     * @ibatorgenerated Tue Mar 03 17:43:02 CST 2015
     */
    public void insertSelective(TTeacherPaperKey record) {
        getSqlMapClientTemplate().insert("t_teacher_paper.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_teacher_paper
     *
     * @ibatorgenerated Tue Mar 03 17:43:02 CST 2015
     */
    public List selectByExample(TTeacherPaperExample example) {
        List list = getSqlMapClientTemplate().queryForList("t_teacher_paper.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_teacher_paper
     *
     * @ibatorgenerated Tue Mar 03 17:43:02 CST 2015
     */
    public int updateByExampleSelective(TTeacherPaperKey record, TTeacherPaperExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("t_teacher_paper.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_teacher_paper
     *
     * @ibatorgenerated Tue Mar 03 17:43:02 CST 2015
     */
    public int updateByExample(TTeacherPaperKey record, TTeacherPaperExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("t_teacher_paper.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table t_teacher_paper
     *
     * @ibatorgenerated Tue Mar 03 17:43:02 CST 2015
     */
    private static class UpdateByExampleParms extends TTeacherPaperExample {
        private Object record;

        public UpdateByExampleParms(Object record, TTeacherPaperExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}