package com.et59.cus.domain.dao;

import com.et59.cus.domain.entity.TTeacherSubjectExample;
import com.et59.cus.domain.entity.TTeacherSubjectKey;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class TTeacherSubjectDAOImpl extends SqlMapClientDaoSupport implements TTeacherSubjectDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_teacher_subject
     *
     * @ibatorgenerated Tue Mar 03 17:43:02 CST 2015
     */
    public TTeacherSubjectDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_teacher_subject
     *
     * @ibatorgenerated Tue Mar 03 17:43:02 CST 2015
     */
    public int countByExample(TTeacherSubjectExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("t_teacher_subject.ibatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_teacher_subject
     *
     * @ibatorgenerated Tue Mar 03 17:43:02 CST 2015
     */
    public int deleteByExample(TTeacherSubjectExample example) {
        int rows = getSqlMapClientTemplate().delete("t_teacher_subject.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_teacher_subject
     *
     * @ibatorgenerated Tue Mar 03 17:43:02 CST 2015
     */
    public int deleteByPrimaryKey(TTeacherSubjectKey key) {
        int rows = getSqlMapClientTemplate().delete("t_teacher_subject.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_teacher_subject
     *
     * @ibatorgenerated Tue Mar 03 17:43:02 CST 2015
     */
    public void insert(TTeacherSubjectKey record) {
        getSqlMapClientTemplate().insert("t_teacher_subject.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_teacher_subject
     *
     * @ibatorgenerated Tue Mar 03 17:43:02 CST 2015
     */
    public void insertSelective(TTeacherSubjectKey record) {
        getSqlMapClientTemplate().insert("t_teacher_subject.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_teacher_subject
     *
     * @ibatorgenerated Tue Mar 03 17:43:02 CST 2015
     */
    public List selectByExample(TTeacherSubjectExample example) {
        List list = getSqlMapClientTemplate().queryForList("t_teacher_subject.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_teacher_subject
     *
     * @ibatorgenerated Tue Mar 03 17:43:02 CST 2015
     */
    public int updateByExampleSelective(TTeacherSubjectKey record, TTeacherSubjectExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("t_teacher_subject.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_teacher_subject
     *
     * @ibatorgenerated Tue Mar 03 17:43:02 CST 2015
     */
    public int updateByExample(TTeacherSubjectKey record, TTeacherSubjectExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("t_teacher_subject.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table t_teacher_subject
     *
     * @ibatorgenerated Tue Mar 03 17:43:02 CST 2015
     */
    private static class UpdateByExampleParms extends TTeacherSubjectExample {
        private Object record;

        public UpdateByExampleParms(Object record, TTeacherSubjectExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}