package com.et59.cus.domain.dao;

import com.et59.cus.domain.entity.TTeacherPrizeExample;
import com.et59.cus.domain.entity.TTeacherPrizeKey;
import java.util.List;

public interface TTeacherPrizeDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_teacher_prize
     *
     * @ibatorgenerated Tue Mar 03 17:43:02 CST 2015
     */
    int countByExample(TTeacherPrizeExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_teacher_prize
     *
     * @ibatorgenerated Tue Mar 03 17:43:02 CST 2015
     */
    int deleteByExample(TTeacherPrizeExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_teacher_prize
     *
     * @ibatorgenerated Tue Mar 03 17:43:02 CST 2015
     */
    int deleteByPrimaryKey(TTeacherPrizeKey key);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_teacher_prize
     *
     * @ibatorgenerated Tue Mar 03 17:43:02 CST 2015
     */
    void insert(TTeacherPrizeKey record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_teacher_prize
     *
     * @ibatorgenerated Tue Mar 03 17:43:02 CST 2015
     */
    void insertSelective(TTeacherPrizeKey record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_teacher_prize
     *
     * @ibatorgenerated Tue Mar 03 17:43:02 CST 2015
     */
    List selectByExample(TTeacherPrizeExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_teacher_prize
     *
     * @ibatorgenerated Tue Mar 03 17:43:02 CST 2015
     */
    int updateByExampleSelective(TTeacherPrizeKey record, TTeacherPrizeExample example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_teacher_prize
     *
     * @ibatorgenerated Tue Mar 03 17:43:02 CST 2015
     */
    int updateByExample(TTeacherPrizeKey record, TTeacherPrizeExample example);
}