package com.et59.cus.domain.dao;

import com.et59.cus.domain.entity.TTrainingplan;
import com.et59.cus.domain.entity.TTrainingplanExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class TTrainingplanDAOImpl extends SqlMapClientDaoSupport implements TTrainingplanDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_trainingplan
	 * @ibatorgenerated  Thu Mar 26 17:53:45 CST 2015
	 */
	public TTrainingplanDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_trainingplan
	 * @ibatorgenerated  Thu Mar 26 17:53:45 CST 2015
	 */
	public int countByExample(TTrainingplanExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"t_trainingplan.ibatorgenerated_countByExample", example);
		return count.intValue();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_trainingplan
	 * @ibatorgenerated  Thu Mar 26 17:53:45 CST 2015
	 */
	public int deleteByExample(TTrainingplanExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"t_trainingplan.ibatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_trainingplan
	 * @ibatorgenerated  Thu Mar 26 17:53:45 CST 2015
	 */
	public int deleteByPrimaryKey(Long trainingplanid) {
		TTrainingplan key = new TTrainingplan();
		key.setTrainingplanid(trainingplanid);
		int rows = getSqlMapClientTemplate().delete(
				"t_trainingplan.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_trainingplan
	 * @ibatorgenerated  Thu Mar 26 17:53:45 CST 2015
	 */
	public void insert(TTrainingplan record) {
		getSqlMapClientTemplate().insert(
				"t_trainingplan.ibatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_trainingplan
	 * @ibatorgenerated  Thu Mar 26 17:53:45 CST 2015
	 */
	public void insertSelective(TTrainingplan record) {
		getSqlMapClientTemplate().insert(
				"t_trainingplan.ibatorgenerated_insertSelective", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_trainingplan
	 * @ibatorgenerated  Thu Mar 26 17:53:45 CST 2015
	 */
	public List selectByExample(TTrainingplanExample example) {
		List list = getSqlMapClientTemplate().queryForList(
				"t_trainingplan.ibatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_trainingplan
	 * @ibatorgenerated  Thu Mar 26 17:53:45 CST 2015
	 */
	public TTrainingplan selectByPrimaryKey(Long trainingplanid) {
		TTrainingplan key = new TTrainingplan();
		key.setTrainingplanid(trainingplanid);
		TTrainingplan record = (TTrainingplan) getSqlMapClientTemplate()
				.queryForObject(
						"t_trainingplan.ibatorgenerated_selectByPrimaryKey",
						key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_trainingplan
	 * @ibatorgenerated  Thu Mar 26 17:53:45 CST 2015
	 */
	public int updateByExampleSelective(TTrainingplan record,
			TTrainingplanExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"t_trainingplan.ibatorgenerated_updateByExampleSelective",
				parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_trainingplan
	 * @ibatorgenerated  Thu Mar 26 17:53:45 CST 2015
	 */
	public int updateByExample(TTrainingplan record,
			TTrainingplanExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"t_trainingplan.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_trainingplan
	 * @ibatorgenerated  Thu Mar 26 17:53:45 CST 2015
	 */
	public int updateByPrimaryKeySelective(TTrainingplan record) {
		int rows = getSqlMapClientTemplate().update(
				"t_trainingplan.ibatorgenerated_updateByPrimaryKeySelective",
				record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_trainingplan
	 * @ibatorgenerated  Thu Mar 26 17:53:45 CST 2015
	 */
	public int updateByPrimaryKey(TTrainingplan record) {
		int rows = getSqlMapClientTemplate().update(
				"t_trainingplan.ibatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table t_trainingplan
	 * @ibatorgenerated  Thu Mar 26 17:53:45 CST 2015
	 */
	private static class UpdateByExampleParms extends TTrainingplanExample {
		private Object record;

		public UpdateByExampleParms(Object record, TTrainingplanExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}