//status
QUEUE_LIMIT_EXCEEDED_STATUS="文件数目超过队列长度！";
FILE_EXCEEDS_SIZE_LIMIT_STATUS="文件过大！";
QUEUE_ZERO_BYTE_FILE_STATUS="文件长度为0！";
INVALID_FILETYPE_STATUS="文件类型错误";
UNHANDLED_QUEUE_ERROR_STATUS="未知队列错误！";

UPLOAD_READY_STATUS="准备上传";
UPLOAD_SUCCESS_STATUS="上传成功";
UPLOAD_PROCESSING_STATUS="正在上传";
UPLOAD_HTTP_ERROR_STATUS="上传错误";
UPLOAD_FAILED_STATUS="上传失败";
IO_ERROR_STATUS="IO错误";
SECURITY_ERROR_STATUS="安全错误";
UPLOAD_LIMIT_EXCEEDED_STATUS="上传文件大小超过限制";
FILE_VALIDATION_FAILED_STATUS="文件验证错误";
FILE_CANCELLED_STATUS="文件取消";
UPLOAD_STOPPED_STATUS="文件上传停止";
UNHANDLED_ERROR_STATUS="未知文件上传错误";

//tips
QUEUE_LIMIT_EXCEEDED_TIPS="文件数目过多";
FILE_EXCEEDS_SIZE_LIMIT_TIPS="文件过大";
QUEUE_ZERO_BYTE_FILE_TIPS="空文件";
INVALID_FILETYPE_TIPS="文件类型不正确";
UNHANDLED_QUEUE_ERROR_TIPS="未知错误";

UPLOAD_READY_TIPS="";
UPLOAD_SUCCESS_TIPS="";
UPLOAD_PROCESSING_TIPS="";
UPLOAD_HTTP_ERROR_TIPS="联网错误";
UPLOAD_FAILED_TIPS="文件错误";
IO_ERROR_TIPS="IO错误";
SECURITY_ERROR_TIPS="安全错误";
UPLOAD_LIMIT_EXCEEDED_TIPS="空文件";
FILE_VALIDATION_FAILED_TIPS="文件验证错误";
FILE_CANCELLED_TIPS="文件被取消";
FILE_STOPPED_TIPS="文件上传停止";
UNHANDLED_ERROR_TIPS="未知错误";

//titles
CANCEL_TIPS="取消上传此文件";
POPUP_TITLE="文件上传进度";

//buttons
HIDE_UPLOADING_WINDOW="隐藏";
SHOW_UPLOADING_WINDOW="显示";


//alert
FILE="个文件";
FILES="个文件";
UPLOAD_COMPLETE="上传完成！";

//file_type
FILE_TYPE_IMAGE="图片文件";
FILE_TYPE_ALL="所有文件";