package com.et59.cus.domain.entity;

public class BsAddress {

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column bs_address.id
	 * @abatorgenerated
	 */
	private Long id;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column bs_address.consignee
	 * @abatorgenerated
	 */
	private String consignee;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column bs_address.address_detail
	 * @abatorgenerated
	 */
	private String addressDetail;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column bs_address.telephone
	 * @abatorgenerated
	 */
	private String telephone;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column bs_address.postcode
	 * @abatorgenerated
	 */
	private String postcode;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column bs_address.userid
	 * @abatorgenerated
	 */
	private String userid;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column bs_address.address_head
	 * @abatorgenerated
	 */
	private String addressHead;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column bs_address.isdefault
	 * @abatorgenerated
	 */
	private String isdefault;

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column bs_address.id
	 * @return  the value of bs_address.id
	 * @abatorgenerated
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column bs_address.id
	 * @param id  the value for bs_address.id
	 * @abatorgenerated
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column bs_address.consignee
	 * @return  the value of bs_address.consignee
	 * @abatorgenerated
	 */
	public String getConsignee() {
		return consignee;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column bs_address.consignee
	 * @param consignee  the value for bs_address.consignee
	 * @abatorgenerated
	 */
	public void setConsignee(String consignee) {
		this.consignee = consignee == null ? null : consignee.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column bs_address.address_detail
	 * @return  the value of bs_address.address_detail
	 * @abatorgenerated
	 */
	public String getAddressDetail() {
		return addressDetail;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column bs_address.address_detail
	 * @param addressDetail  the value for bs_address.address_detail
	 * @abatorgenerated
	 */
	public void setAddressDetail(String addressDetail) {
		this.addressDetail = addressDetail == null ? null : addressDetail
				.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column bs_address.telephone
	 * @return  the value of bs_address.telephone
	 * @abatorgenerated
	 */
	public String getTelephone() {
		return telephone;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column bs_address.telephone
	 * @param telephone  the value for bs_address.telephone
	 * @abatorgenerated
	 */
	public void setTelephone(String telephone) {
		this.telephone = telephone == null ? null : telephone.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column bs_address.postcode
	 * @return  the value of bs_address.postcode
	 * @abatorgenerated
	 */
	public String getPostcode() {
		return postcode;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column bs_address.postcode
	 * @param postcode  the value for bs_address.postcode
	 * @abatorgenerated
	 */
	public void setPostcode(String postcode) {
		this.postcode = postcode == null ? null : postcode.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column bs_address.userid
	 * @return  the value of bs_address.userid
	 * @abatorgenerated
	 */
	public String getUserid() {
		return userid;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column bs_address.userid
	 * @param userid  the value for bs_address.userid
	 * @abatorgenerated
	 */
	public void setUserid(String userid) {
		this.userid = userid == null ? null : userid.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column bs_address.address_head
	 * @return  the value of bs_address.address_head
	 * @abatorgenerated
	 */
	public String getAddressHead() {
		return addressHead;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column bs_address.address_head
	 * @param addressHead  the value for bs_address.address_head
	 * @abatorgenerated
	 */
	public void setAddressHead(String addressHead) {
		this.addressHead = addressHead == null ? null : addressHead.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column bs_address.isdefault
	 * @return  the value of bs_address.isdefault
	 * @abatorgenerated
	 */
	public String getIsdefault() {
		return isdefault;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column bs_address.isdefault
	 * @param isdefault  the value for bs_address.isdefault
	 * @abatorgenerated
	 */
	public void setIsdefault(String isdefault) {
		this.isdefault = isdefault == null ? null : isdefault.trim();
	}
}