package com.et59.cus.domain.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class BsArticleExample {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database table bs_article
	 * @ibatorgenerated  Thu Mar 05 16:23:33 CST 2015
	 */
	protected String orderByClause;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database table bs_article
	 * @ibatorgenerated  Thu Mar 05 16:23:33 CST 2015
	 */
	protected List oredCriteria;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table bs_article
	 * @ibatorgenerated  Thu Mar 05 16:23:33 CST 2015
	 */
	public BsArticleExample() {
		oredCriteria = new ArrayList();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table bs_article
	 * @ibatorgenerated  Thu Mar 05 16:23:33 CST 2015
	 */
	protected BsArticleExample(BsArticleExample example) {
		this.orderByClause = example.orderByClause;
		this.oredCriteria = example.oredCriteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table bs_article
	 * @ibatorgenerated  Thu Mar 05 16:23:33 CST 2015
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table bs_article
	 * @ibatorgenerated  Thu Mar 05 16:23:33 CST 2015
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table bs_article
	 * @ibatorgenerated  Thu Mar 05 16:23:33 CST 2015
	 */
	public List getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table bs_article
	 * @ibatorgenerated  Thu Mar 05 16:23:33 CST 2015
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table bs_article
	 * @ibatorgenerated  Thu Mar 05 16:23:33 CST 2015
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table bs_article
	 * @ibatorgenerated  Thu Mar 05 16:23:33 CST 2015
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table bs_article
	 * @ibatorgenerated  Thu Mar 05 16:23:33 CST 2015
	 */
	public void clear() {
		oredCriteria.clear();
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table bs_article
	 * @ibatorgenerated  Thu Mar 05 16:23:33 CST 2015
	 */
	public static class Criteria {
		protected List criteriaWithoutValue;
		protected List criteriaWithSingleValue;
		protected List criteriaWithListValue;
		protected List criteriaWithBetweenValue;

		protected Criteria() {
			super();
			criteriaWithoutValue = new ArrayList();
			criteriaWithSingleValue = new ArrayList();
			criteriaWithListValue = new ArrayList();
			criteriaWithBetweenValue = new ArrayList();
		}

		public boolean isValid() {
			return criteriaWithoutValue.size() > 0
					|| criteriaWithSingleValue.size() > 0
					|| criteriaWithListValue.size() > 0
					|| criteriaWithBetweenValue.size() > 0;
		}

		public List getCriteriaWithoutValue() {
			return criteriaWithoutValue;
		}

		public List getCriteriaWithSingleValue() {
			return criteriaWithSingleValue;
		}

		public List getCriteriaWithListValue() {
			return criteriaWithListValue;
		}

		public List getCriteriaWithBetweenValue() {
			return criteriaWithBetweenValue;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteriaWithoutValue.add(condition);
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("value", value);
			criteriaWithSingleValue.add(map);
		}

		protected void addCriterion(String condition, List values,
				String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property
						+ " cannot be null or empty");
			}
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("values", values);
			criteriaWithListValue.add(map);
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			List list = new ArrayList();
			list.add(value1);
			list.add(value2);
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("values", list);
			criteriaWithBetweenValue.add(map);
		}

		public Criteria andArticleidIsNull() {
			addCriterion("articleid is null");
			return this;
		}

		public Criteria andArticleidIsNotNull() {
			addCriterion("articleid is not null");
			return this;
		}

		public Criteria andArticleidEqualTo(Long value) {
			addCriterion("articleid =", value, "articleid");
			return this;
		}

		public Criteria andArticleidNotEqualTo(Long value) {
			addCriterion("articleid <>", value, "articleid");
			return this;
		}

		public Criteria andArticleidGreaterThan(Long value) {
			addCriterion("articleid >", value, "articleid");
			return this;
		}

		public Criteria andArticleidGreaterThanOrEqualTo(Long value) {
			addCriterion("articleid >=", value, "articleid");
			return this;
		}

		public Criteria andArticleidLessThan(Long value) {
			addCriterion("articleid <", value, "articleid");
			return this;
		}

		public Criteria andArticleidLessThanOrEqualTo(Long value) {
			addCriterion("articleid <=", value, "articleid");
			return this;
		}

		public Criteria andArticleidIn(List values) {
			addCriterion("articleid in", values, "articleid");
			return this;
		}

		public Criteria andArticleidNotIn(List values) {
			addCriterion("articleid not in", values, "articleid");
			return this;
		}

		public Criteria andArticleidBetween(Long value1, Long value2) {
			addCriterion("articleid between", value1, value2, "articleid");
			return this;
		}

		public Criteria andArticleidNotBetween(Long value1, Long value2) {
			addCriterion("articleid not between", value1, value2, "articleid");
			return this;
		}

		public Criteria andAuthorIsNull() {
			addCriterion("author is null");
			return this;
		}

		public Criteria andAuthorIsNotNull() {
			addCriterion("author is not null");
			return this;
		}

		public Criteria andAuthorEqualTo(String value) {
			addCriterion("author =", value, "author");
			return this;
		}

		public Criteria andAuthorNotEqualTo(String value) {
			addCriterion("author <>", value, "author");
			return this;
		}

		public Criteria andAuthorGreaterThan(String value) {
			addCriterion("author >", value, "author");
			return this;
		}

		public Criteria andAuthorGreaterThanOrEqualTo(String value) {
			addCriterion("author >=", value, "author");
			return this;
		}

		public Criteria andAuthorLessThan(String value) {
			addCriterion("author <", value, "author");
			return this;
		}

		public Criteria andAuthorLessThanOrEqualTo(String value) {
			addCriterion("author <=", value, "author");
			return this;
		}

		public Criteria andAuthorLike(String value) {
			addCriterion("author like", value, "author");
			return this;
		}

		public Criteria andAuthorNotLike(String value) {
			addCriterion("author not like", value, "author");
			return this;
		}

		public Criteria andAuthorIn(List values) {
			addCriterion("author in", values, "author");
			return this;
		}

		public Criteria andAuthorNotIn(List values) {
			addCriterion("author not in", values, "author");
			return this;
		}

		public Criteria andAuthorBetween(String value1, String value2) {
			addCriterion("author between", value1, value2, "author");
			return this;
		}

		public Criteria andAuthorNotBetween(String value1, String value2) {
			addCriterion("author not between", value1, value2, "author");
			return this;
		}

		public Criteria andCreatedateIsNull() {
			addCriterion("createdate is null");
			return this;
		}

		public Criteria andCreatedateIsNotNull() {
			addCriterion("createdate is not null");
			return this;
		}

		public Criteria andCreatedateEqualTo(String value) {
			addCriterion("createdate =", value, "createdate");
			return this;
		}

		public Criteria andCreatedateNotEqualTo(String value) {
			addCriterion("createdate <>", value, "createdate");
			return this;
		}

		public Criteria andCreatedateGreaterThan(String value) {
			addCriterion("createdate >", value, "createdate");
			return this;
		}

		public Criteria andCreatedateGreaterThanOrEqualTo(String value) {
			addCriterion("createdate >=", value, "createdate");
			return this;
		}

		public Criteria andCreatedateLessThan(String value) {
			addCriterion("createdate <", value, "createdate");
			return this;
		}

		public Criteria andCreatedateLessThanOrEqualTo(String value) {
			addCriterion("createdate <=", value, "createdate");
			return this;
		}

		public Criteria andCreatedateLike(String value) {
			addCriterion("createdate like", value, "createdate");
			return this;
		}

		public Criteria andCreatedateNotLike(String value) {
			addCriterion("createdate not like", value, "createdate");
			return this;
		}

		public Criteria andCreatedateIn(List values) {
			addCriterion("createdate in", values, "createdate");
			return this;
		}

		public Criteria andCreatedateNotIn(List values) {
			addCriterion("createdate not in", values, "createdate");
			return this;
		}

		public Criteria andCreatedateBetween(String value1, String value2) {
			addCriterion("createdate between", value1, value2, "createdate");
			return this;
		}

		public Criteria andCreatedateNotBetween(String value1, String value2) {
			addCriterion("createdate not between", value1, value2, "createdate");
			return this;
		}

		public Criteria andArticletypeIsNull() {
			addCriterion("articletype is null");
			return this;
		}

		public Criteria andArticletypeIsNotNull() {
			addCriterion("articletype is not null");
			return this;
		}

		public Criteria andArticletypeEqualTo(String value) {
			addCriterion("articletype =", value, "articletype");
			return this;
		}

		public Criteria andArticletypeNotEqualTo(String value) {
			addCriterion("articletype <>", value, "articletype");
			return this;
		}

		public Criteria andArticletypeGreaterThan(String value) {
			addCriterion("articletype >", value, "articletype");
			return this;
		}

		public Criteria andArticletypeGreaterThanOrEqualTo(String value) {
			addCriterion("articletype >=", value, "articletype");
			return this;
		}

		public Criteria andArticletypeLessThan(String value) {
			addCriterion("articletype <", value, "articletype");
			return this;
		}

		public Criteria andArticletypeLessThanOrEqualTo(String value) {
			addCriterion("articletype <=", value, "articletype");
			return this;
		}

		public Criteria andArticletypeLike(String value) {
			addCriterion("articletype like", value, "articletype");
			return this;
		}

		public Criteria andArticletypeNotLike(String value) {
			addCriterion("articletype not like", value, "articletype");
			return this;
		}

		public Criteria andArticletypeIn(List values) {
			addCriterion("articletype in", values, "articletype");
			return this;
		}

		public Criteria andArticletypeNotIn(List values) {
			addCriterion("articletype not in", values, "articletype");
			return this;
		}

		public Criteria andArticletypeBetween(String value1, String value2) {
			addCriterion("articletype between", value1, value2, "articletype");
			return this;
		}

		public Criteria andArticletypeNotBetween(String value1, String value2) {
			addCriterion("articletype not between", value1, value2,
					"articletype");
			return this;
		}

		public Criteria andArticlesummaryIsNull() {
			addCriterion("articlesummary is null");
			return this;
		}

		public Criteria andArticlesummaryIsNotNull() {
			addCriterion("articlesummary is not null");
			return this;
		}

		public Criteria andArticlesummaryEqualTo(String value) {
			addCriterion("articlesummary =", value, "articlesummary");
			return this;
		}

		public Criteria andArticlesummaryNotEqualTo(String value) {
			addCriterion("articlesummary <>", value, "articlesummary");
			return this;
		}

		public Criteria andArticlesummaryGreaterThan(String value) {
			addCriterion("articlesummary >", value, "articlesummary");
			return this;
		}

		public Criteria andArticlesummaryGreaterThanOrEqualTo(String value) {
			addCriterion("articlesummary >=", value, "articlesummary");
			return this;
		}

		public Criteria andArticlesummaryLessThan(String value) {
			addCriterion("articlesummary <", value, "articlesummary");
			return this;
		}

		public Criteria andArticlesummaryLessThanOrEqualTo(String value) {
			addCriterion("articlesummary <=", value, "articlesummary");
			return this;
		}

		public Criteria andArticlesummaryLike(String value) {
			addCriterion("articlesummary like", value, "articlesummary");
			return this;
		}

		public Criteria andArticlesummaryNotLike(String value) {
			addCriterion("articlesummary not like", value, "articlesummary");
			return this;
		}

		public Criteria andArticlesummaryIn(List values) {
			addCriterion("articlesummary in", values, "articlesummary");
			return this;
		}

		public Criteria andArticlesummaryNotIn(List values) {
			addCriterion("articlesummary not in", values, "articlesummary");
			return this;
		}

		public Criteria andArticlesummaryBetween(String value1, String value2) {
			addCriterion("articlesummary between", value1, value2,
					"articlesummary");
			return this;
		}

		public Criteria andArticlesummaryNotBetween(String value1, String value2) {
			addCriterion("articlesummary not between", value1, value2,
					"articlesummary");
			return this;
		}

		public Criteria andContentIsNull() {
			addCriterion("content is null");
			return this;
		}

		public Criteria andContentIsNotNull() {
			addCriterion("content is not null");
			return this;
		}

		public Criteria andContentEqualTo(String value) {
			addCriterion("content =", value, "content");
			return this;
		}

		public Criteria andContentNotEqualTo(String value) {
			addCriterion("content <>", value, "content");
			return this;
		}

		public Criteria andContentGreaterThan(String value) {
			addCriterion("content >", value, "content");
			return this;
		}

		public Criteria andContentGreaterThanOrEqualTo(String value) {
			addCriterion("content >=", value, "content");
			return this;
		}

		public Criteria andContentLessThan(String value) {
			addCriterion("content <", value, "content");
			return this;
		}

		public Criteria andContentLessThanOrEqualTo(String value) {
			addCriterion("content <=", value, "content");
			return this;
		}

		public Criteria andContentLike(String value) {
			addCriterion("content like", value, "content");
			return this;
		}

		public Criteria andContentNotLike(String value) {
			addCriterion("content not like", value, "content");
			return this;
		}

		public Criteria andContentIn(List values) {
			addCriterion("content in", values, "content");
			return this;
		}

		public Criteria andContentNotIn(List values) {
			addCriterion("content not in", values, "content");
			return this;
		}

		public Criteria andContentBetween(String value1, String value2) {
			addCriterion("content between", value1, value2, "content");
			return this;
		}

		public Criteria andContentNotBetween(String value1, String value2) {
			addCriterion("content not between", value1, value2, "content");
			return this;
		}

		public Criteria andUpdatedateIsNull() {
			addCriterion("updatedate is null");
			return this;
		}

		public Criteria andUpdatedateIsNotNull() {
			addCriterion("updatedate is not null");
			return this;
		}

		public Criteria andUpdatedateEqualTo(String value) {
			addCriterion("updatedate =", value, "updatedate");
			return this;
		}

		public Criteria andUpdatedateNotEqualTo(String value) {
			addCriterion("updatedate <>", value, "updatedate");
			return this;
		}

		public Criteria andUpdatedateGreaterThan(String value) {
			addCriterion("updatedate >", value, "updatedate");
			return this;
		}

		public Criteria andUpdatedateGreaterThanOrEqualTo(String value) {
			addCriterion("updatedate >=", value, "updatedate");
			return this;
		}

		public Criteria andUpdatedateLessThan(String value) {
			addCriterion("updatedate <", value, "updatedate");
			return this;
		}

		public Criteria andUpdatedateLessThanOrEqualTo(String value) {
			addCriterion("updatedate <=", value, "updatedate");
			return this;
		}

		public Criteria andUpdatedateLike(String value) {
			addCriterion("updatedate like", value, "updatedate");
			return this;
		}

		public Criteria andUpdatedateNotLike(String value) {
			addCriterion("updatedate not like", value, "updatedate");
			return this;
		}

		public Criteria andUpdatedateIn(List values) {
			addCriterion("updatedate in", values, "updatedate");
			return this;
		}

		public Criteria andUpdatedateNotIn(List values) {
			addCriterion("updatedate not in", values, "updatedate");
			return this;
		}

		public Criteria andUpdatedateBetween(String value1, String value2) {
			addCriterion("updatedate between", value1, value2, "updatedate");
			return this;
		}

		public Criteria andUpdatedateNotBetween(String value1, String value2) {
			addCriterion("updatedate not between", value1, value2, "updatedate");
			return this;
		}

		public Criteria andArticletitleIsNull() {
			addCriterion("articletitle is null");
			return this;
		}

		public Criteria andArticletitleIsNotNull() {
			addCriterion("articletitle is not null");
			return this;
		}

		public Criteria andArticletitleEqualTo(String value) {
			addCriterion("articletitle =", value, "articletitle");
			return this;
		}

		public Criteria andArticletitleNotEqualTo(String value) {
			addCriterion("articletitle <>", value, "articletitle");
			return this;
		}

		public Criteria andArticletitleGreaterThan(String value) {
			addCriterion("articletitle >", value, "articletitle");
			return this;
		}

		public Criteria andArticletitleGreaterThanOrEqualTo(String value) {
			addCriterion("articletitle >=", value, "articletitle");
			return this;
		}

		public Criteria andArticletitleLessThan(String value) {
			addCriterion("articletitle <", value, "articletitle");
			return this;
		}

		public Criteria andArticletitleLessThanOrEqualTo(String value) {
			addCriterion("articletitle <=", value, "articletitle");
			return this;
		}

		public Criteria andArticletitleLike(String value) {
			addCriterion("articletitle like", value, "articletitle");
			return this;
		}

		public Criteria andArticletitleNotLike(String value) {
			addCriterion("articletitle not like", value, "articletitle");
			return this;
		}

		public Criteria andArticletitleIn(List values) {
			addCriterion("articletitle in", values, "articletitle");
			return this;
		}

		public Criteria andArticletitleNotIn(List values) {
			addCriterion("articletitle not in", values, "articletitle");
			return this;
		}

		public Criteria andArticletitleBetween(String value1, String value2) {
			addCriterion("articletitle between", value1, value2, "articletitle");
			return this;
		}

		public Criteria andArticletitleNotBetween(String value1, String value2) {
			addCriterion("articletitle not between", value1, value2,
					"articletitle");
			return this;
		}

		public Criteria andNoticetargetIsNull() {
			addCriterion("noticetarget is null");
			return this;
		}

		public Criteria andNoticetargetIsNotNull() {
			addCriterion("noticetarget is not null");
			return this;
		}

		public Criteria andNoticetargetEqualTo(String value) {
			addCriterion("noticetarget =", value, "noticetarget");
			return this;
		}

		public Criteria andNoticetargetNotEqualTo(String value) {
			addCriterion("noticetarget <>", value, "noticetarget");
			return this;
		}

		public Criteria andNoticetargetGreaterThan(String value) {
			addCriterion("noticetarget >", value, "noticetarget");
			return this;
		}

		public Criteria andNoticetargetGreaterThanOrEqualTo(String value) {
			addCriterion("noticetarget >=", value, "noticetarget");
			return this;
		}

		public Criteria andNoticetargetLessThan(String value) {
			addCriterion("noticetarget <", value, "noticetarget");
			return this;
		}

		public Criteria andNoticetargetLessThanOrEqualTo(String value) {
			addCriterion("noticetarget <=", value, "noticetarget");
			return this;
		}

		public Criteria andNoticetargetLike(String value) {
			addCriterion("noticetarget like", value, "noticetarget");
			return this;
		}

		public Criteria andNoticetargetNotLike(String value) {
			addCriterion("noticetarget not like", value, "noticetarget");
			return this;
		}

		public Criteria andNoticetargetIn(List values) {
			addCriterion("noticetarget in", values, "noticetarget");
			return this;
		}

		public Criteria andNoticetargetNotIn(List values) {
			addCriterion("noticetarget not in", values, "noticetarget");
			return this;
		}

		public Criteria andNoticetargetBetween(String value1, String value2) {
			addCriterion("noticetarget between", value1, value2, "noticetarget");
			return this;
		}

		public Criteria andNoticetargetNotBetween(String value1, String value2) {
			addCriterion("noticetarget not between", value1, value2,
					"noticetarget");
			return this;
		}

		public Criteria andNoticeendtimeIsNull() {
			addCriterion("noticeendtime is null");
			return this;
		}

		public Criteria andNoticeendtimeIsNotNull() {
			addCriterion("noticeendtime is not null");
			return this;
		}

		public Criteria andNoticeendtimeEqualTo(String value) {
			addCriterion("noticeendtime =", value, "noticeendtime");
			return this;
		}

		public Criteria andNoticeendtimeNotEqualTo(String value) {
			addCriterion("noticeendtime <>", value, "noticeendtime");
			return this;
		}

		public Criteria andNoticeendtimeGreaterThan(String value) {
			addCriterion("noticeendtime >", value, "noticeendtime");
			return this;
		}

		public Criteria andNoticeendtimeGreaterThanOrEqualTo(String value) {
			addCriterion("noticeendtime >=", value, "noticeendtime");
			return this;
		}

		public Criteria andNoticeendtimeLessThan(String value) {
			addCriterion("noticeendtime <", value, "noticeendtime");
			return this;
		}

		public Criteria andNoticeendtimeLessThanOrEqualTo(String value) {
			addCriterion("noticeendtime <=", value, "noticeendtime");
			return this;
		}

		public Criteria andNoticeendtimeLike(String value) {
			addCriterion("noticeendtime like", value, "noticeendtime");
			return this;
		}

		public Criteria andNoticeendtimeNotLike(String value) {
			addCriterion("noticeendtime not like", value, "noticeendtime");
			return this;
		}

		public Criteria andNoticeendtimeIn(List values) {
			addCriterion("noticeendtime in", values, "noticeendtime");
			return this;
		}

		public Criteria andNoticeendtimeNotIn(List values) {
			addCriterion("noticeendtime not in", values, "noticeendtime");
			return this;
		}

		public Criteria andNoticeendtimeBetween(String value1, String value2) {
			addCriterion("noticeendtime between", value1, value2,
					"noticeendtime");
			return this;
		}

		public Criteria andNoticeendtimeNotBetween(String value1, String value2) {
			addCriterion("noticeendtime not between", value1, value2,
					"noticeendtime");
			return this;
		}

		public Criteria andNewspicIsNull() {
			addCriterion("newspic is null");
			return this;
		}

		public Criteria andNewspicIsNotNull() {
			addCriterion("newspic is not null");
			return this;
		}

		public Criteria andNewspicEqualTo(String value) {
			addCriterion("newspic =", value, "newspic");
			return this;
		}

		public Criteria andNewspicNotEqualTo(String value) {
			addCriterion("newspic <>", value, "newspic");
			return this;
		}

		public Criteria andNewspicGreaterThan(String value) {
			addCriterion("newspic >", value, "newspic");
			return this;
		}

		public Criteria andNewspicGreaterThanOrEqualTo(String value) {
			addCriterion("newspic >=", value, "newspic");
			return this;
		}

		public Criteria andNewspicLessThan(String value) {
			addCriterion("newspic <", value, "newspic");
			return this;
		}

		public Criteria andNewspicLessThanOrEqualTo(String value) {
			addCriterion("newspic <=", value, "newspic");
			return this;
		}

		public Criteria andNewspicLike(String value) {
			addCriterion("newspic like", value, "newspic");
			return this;
		}

		public Criteria andNewspicNotLike(String value) {
			addCriterion("newspic not like", value, "newspic");
			return this;
		}

		public Criteria andNewspicIn(List values) {
			addCriterion("newspic in", values, "newspic");
			return this;
		}

		public Criteria andNewspicNotIn(List values) {
			addCriterion("newspic not in", values, "newspic");
			return this;
		}

		public Criteria andNewspicBetween(String value1, String value2) {
			addCriterion("newspic between", value1, value2, "newspic");
			return this;
		}

		public Criteria andNewspicNotBetween(String value1, String value2) {
			addCriterion("newspic not between", value1, value2, "newspic");
			return this;
		}

		public Criteria andNewsisshowIsNull() {
			addCriterion("newsisshow is null");
			return this;
		}

		public Criteria andNewsisshowIsNotNull() {
			addCriterion("newsisshow is not null");
			return this;
		}

		public Criteria andNewsisshowEqualTo(String value) {
			addCriterion("newsisshow =", value, "newsisshow");
			return this;
		}

		public Criteria andNewsisshowNotEqualTo(String value) {
			addCriterion("newsisshow <>", value, "newsisshow");
			return this;
		}

		public Criteria andNewsisshowGreaterThan(String value) {
			addCriterion("newsisshow >", value, "newsisshow");
			return this;
		}

		public Criteria andNewsisshowGreaterThanOrEqualTo(String value) {
			addCriterion("newsisshow >=", value, "newsisshow");
			return this;
		}

		public Criteria andNewsisshowLessThan(String value) {
			addCriterion("newsisshow <", value, "newsisshow");
			return this;
		}

		public Criteria andNewsisshowLessThanOrEqualTo(String value) {
			addCriterion("newsisshow <=", value, "newsisshow");
			return this;
		}

		public Criteria andNewsisshowLike(String value) {
			addCriterion("newsisshow like", value, "newsisshow");
			return this;
		}

		public Criteria andNewsisshowNotLike(String value) {
			addCriterion("newsisshow not like", value, "newsisshow");
			return this;
		}

		public Criteria andNewsisshowIn(List values) {
			addCriterion("newsisshow in", values, "newsisshow");
			return this;
		}

		public Criteria andNewsisshowNotIn(List values) {
			addCriterion("newsisshow not in", values, "newsisshow");
			return this;
		}

		public Criteria andNewsisshowBetween(String value1, String value2) {
			addCriterion("newsisshow between", value1, value2, "newsisshow");
			return this;
		}

		public Criteria andNewsisshowNotBetween(String value1, String value2) {
			addCriterion("newsisshow not between", value1, value2, "newsisshow");
			return this;
		}

		public Criteria andDownloadidIsNull() {
			addCriterion("downloadid is null");
			return this;
		}

		public Criteria andDownloadidIsNotNull() {
			addCriterion("downloadid is not null");
			return this;
		}

		public Criteria andDownloadidEqualTo(Long value) {
			addCriterion("downloadid =", value, "downloadid");
			return this;
		}

		public Criteria andDownloadidNotEqualTo(Long value) {
			addCriterion("downloadid <>", value, "downloadid");
			return this;
		}

		public Criteria andDownloadidGreaterThan(Long value) {
			addCriterion("downloadid >", value, "downloadid");
			return this;
		}

		public Criteria andDownloadidGreaterThanOrEqualTo(Long value) {
			addCriterion("downloadid >=", value, "downloadid");
			return this;
		}

		public Criteria andDownloadidLessThan(Long value) {
			addCriterion("downloadid <", value, "downloadid");
			return this;
		}

		public Criteria andDownloadidLessThanOrEqualTo(Long value) {
			addCriterion("downloadid <=", value, "downloadid");
			return this;
		}

		public Criteria andDownloadidIn(List values) {
			addCriterion("downloadid in", values, "downloadid");
			return this;
		}

		public Criteria andDownloadidNotIn(List values) {
			addCriterion("downloadid not in", values, "downloadid");
			return this;
		}

		public Criteria andDownloadidBetween(Long value1, Long value2) {
			addCriterion("downloadid between", value1, value2, "downloadid");
			return this;
		}

		public Criteria andDownloadidNotBetween(Long value1, Long value2) {
			addCriterion("downloadid not between", value1, value2, "downloadid");
			return this;
		}
	}
}