package com.et59.cus.domain.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class BsEmailExample {

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database table bs_email
	 * @abatorgenerated
	 */
	protected String orderByClause;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database table bs_email
	 * @abatorgenerated
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_email
	 * @abatorgenerated
	 */
	public BsEmailExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_email
	 * @abatorgenerated
	 */
	protected BsEmailExample(BsEmailExample example) {
		this.orderByClause = example.orderByClause;
		this.oredCriteria = example.oredCriteria;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_email
	 * @abatorgenerated
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_email
	 * @abatorgenerated
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_email
	 * @abatorgenerated
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_email
	 * @abatorgenerated
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_email
	 * @abatorgenerated
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_email
	 * @abatorgenerated
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_email
	 * @abatorgenerated
	 */
	public void clear() {
		oredCriteria.clear();
	}

	/**
	 * This class was generated by Abator for iBATIS. This class corresponds to the database table bs_email
	 * @abatorgenerated
	 */
	public static class Criteria {
		protected List<String> criteriaWithoutValue;
		protected List<Map<String, Object>> criteriaWithSingleValue;
		protected List<Map<String, Object>> criteriaWithListValue;
		protected List<Map<String, Object>> criteriaWithBetweenValue;

		protected Criteria() {
			super();
			criteriaWithoutValue = new ArrayList<String>();
			criteriaWithSingleValue = new ArrayList<Map<String, Object>>();
			criteriaWithListValue = new ArrayList<Map<String, Object>>();
			criteriaWithBetweenValue = new ArrayList<Map<String, Object>>();
		}

		public boolean isValid() {
			return criteriaWithoutValue.size() > 0
					|| criteriaWithSingleValue.size() > 0
					|| criteriaWithListValue.size() > 0
					|| criteriaWithBetweenValue.size() > 0;
		}

		public List<String> getCriteriaWithoutValue() {
			return criteriaWithoutValue;
		}

		public List<Map<String, Object>> getCriteriaWithSingleValue() {
			return criteriaWithSingleValue;
		}

		public List<Map<String, Object>> getCriteriaWithListValue() {
			return criteriaWithListValue;
		}

		public List<Map<String, Object>> getCriteriaWithBetweenValue() {
			return criteriaWithBetweenValue;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteriaWithoutValue.add(condition);
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			Map<String, Object> map = new HashMap<String, Object>();
			map.put("condition", condition);
			map.put("value", value);
			criteriaWithSingleValue.add(map);
		}

		protected void addCriterion(String condition,
				List<? extends Object> values, String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property
						+ " cannot be null or empty");
			}
			Map<String, Object> map = new HashMap<String, Object>();
			map.put("condition", condition);
			map.put("values", values);
			criteriaWithListValue.add(map);
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			List<Object> list = new ArrayList<Object>();
			list.add(value1);
			list.add(value2);
			Map<String, Object> map = new HashMap<String, Object>();
			map.put("condition", condition);
			map.put("values", list);
			criteriaWithBetweenValue.add(map);
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return this;
		}

		public Criteria andIdEqualTo(Long value) {
			addCriterion("id =", value, "id");
			return this;
		}

		public Criteria andIdNotEqualTo(Long value) {
			addCriterion("id <>", value, "id");
			return this;
		}

		public Criteria andIdGreaterThan(Long value) {
			addCriterion("id >", value, "id");
			return this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Long value) {
			addCriterion("id >=", value, "id");
			return this;
		}

		public Criteria andIdLessThan(Long value) {
			addCriterion("id <", value, "id");
			return this;
		}

		public Criteria andIdLessThanOrEqualTo(Long value) {
			addCriterion("id <=", value, "id");
			return this;
		}

		public Criteria andIdIn(List<Long> values) {
			addCriterion("id in", values, "id");
			return this;
		}

		public Criteria andIdNotIn(List<Long> values) {
			addCriterion("id not in", values, "id");
			return this;
		}

		public Criteria andIdBetween(Long value1, Long value2) {
			addCriterion("id between", value1, value2, "id");
			return this;
		}

		public Criteria andIdNotBetween(Long value1, Long value2) {
			addCriterion("id not between", value1, value2, "id");
			return this;
		}

		public Criteria andMailcontentIsNull() {
			addCriterion("mailcontent is null");
			return this;
		}

		public Criteria andMailcontentIsNotNull() {
			addCriterion("mailcontent is not null");
			return this;
		}

		public Criteria andMailcontentEqualTo(String value) {
			addCriterion("mailcontent =", value, "mailcontent");
			return this;
		}

		public Criteria andMailcontentNotEqualTo(String value) {
			addCriterion("mailcontent <>", value, "mailcontent");
			return this;
		}

		public Criteria andMailcontentGreaterThan(String value) {
			addCriterion("mailcontent >", value, "mailcontent");
			return this;
		}

		public Criteria andMailcontentGreaterThanOrEqualTo(String value) {
			addCriterion("mailcontent >=", value, "mailcontent");
			return this;
		}

		public Criteria andMailcontentLessThan(String value) {
			addCriterion("mailcontent <", value, "mailcontent");
			return this;
		}

		public Criteria andMailcontentLessThanOrEqualTo(String value) {
			addCriterion("mailcontent <=", value, "mailcontent");
			return this;
		}

		public Criteria andMailcontentLike(String value) {
			addCriterion("mailcontent like", value, "mailcontent");
			return this;
		}

		public Criteria andMailcontentNotLike(String value) {
			addCriterion("mailcontent not like", value, "mailcontent");
			return this;
		}

		public Criteria andMailcontentIn(List<String> values) {
			addCriterion("mailcontent in", values, "mailcontent");
			return this;
		}

		public Criteria andMailcontentNotIn(List<String> values) {
			addCriterion("mailcontent not in", values, "mailcontent");
			return this;
		}

		public Criteria andMailcontentBetween(String value1, String value2) {
			addCriterion("mailcontent between", value1, value2, "mailcontent");
			return this;
		}

		public Criteria andMailcontentNotBetween(String value1, String value2) {
			addCriterion("mailcontent not between", value1, value2,
					"mailcontent");
			return this;
		}

		public Criteria andMailtoIsNull() {
			addCriterion("mailto is null");
			return this;
		}

		public Criteria andMailtoIsNotNull() {
			addCriterion("mailto is not null");
			return this;
		}

		public Criteria andMailtoEqualTo(String value) {
			addCriterion("mailto =", value, "mailto");
			return this;
		}

		public Criteria andMailtoNotEqualTo(String value) {
			addCriterion("mailto <>", value, "mailto");
			return this;
		}

		public Criteria andMailtoGreaterThan(String value) {
			addCriterion("mailto >", value, "mailto");
			return this;
		}

		public Criteria andMailtoGreaterThanOrEqualTo(String value) {
			addCriterion("mailto >=", value, "mailto");
			return this;
		}

		public Criteria andMailtoLessThan(String value) {
			addCriterion("mailto <", value, "mailto");
			return this;
		}

		public Criteria andMailtoLessThanOrEqualTo(String value) {
			addCriterion("mailto <=", value, "mailto");
			return this;
		}

		public Criteria andMailtoLike(String value) {
			addCriterion("mailto like", value, "mailto");
			return this;
		}

		public Criteria andMailtoNotLike(String value) {
			addCriterion("mailto not like", value, "mailto");
			return this;
		}

		public Criteria andMailtoIn(List<String> values) {
			addCriterion("mailto in", values, "mailto");
			return this;
		}

		public Criteria andMailtoNotIn(List<String> values) {
			addCriterion("mailto not in", values, "mailto");
			return this;
		}

		public Criteria andMailtoBetween(String value1, String value2) {
			addCriterion("mailto between", value1, value2, "mailto");
			return this;
		}

		public Criteria andMailtoNotBetween(String value1, String value2) {
			addCriterion("mailto not between", value1, value2, "mailto");
			return this;
		}

		public Criteria andCreatetimeIsNull() {
			addCriterion("createtime is null");
			return this;
		}

		public Criteria andCreatetimeIsNotNull() {
			addCriterion("createtime is not null");
			return this;
		}

		public Criteria andCreatetimeEqualTo(Date value) {
			addCriterion("createtime =", value, "createtime");
			return this;
		}

		public Criteria andCreatetimeNotEqualTo(Date value) {
			addCriterion("createtime <>", value, "createtime");
			return this;
		}

		public Criteria andCreatetimeGreaterThan(Date value) {
			addCriterion("createtime >", value, "createtime");
			return this;
		}

		public Criteria andCreatetimeGreaterThanOrEqualTo(Date value) {
			addCriterion("createtime >=", value, "createtime");
			return this;
		}

		public Criteria andCreatetimeLessThan(Date value) {
			addCriterion("createtime <", value, "createtime");
			return this;
		}

		public Criteria andCreatetimeLessThanOrEqualTo(Date value) {
			addCriterion("createtime <=", value, "createtime");
			return this;
		}

		public Criteria andCreatetimeIn(List<Date> values) {
			addCriterion("createtime in", values, "createtime");
			return this;
		}

		public Criteria andCreatetimeNotIn(List<Date> values) {
			addCriterion("createtime not in", values, "createtime");
			return this;
		}

		public Criteria andCreatetimeBetween(Date value1, Date value2) {
			addCriterion("createtime between", value1, value2, "createtime");
			return this;
		}

		public Criteria andCreatetimeNotBetween(Date value1, Date value2) {
			addCriterion("createtime not between", value1, value2, "createtime");
			return this;
		}

		public Criteria andCodeIsNull() {
			addCriterion("code is null");
			return this;
		}

		public Criteria andCodeIsNotNull() {
			addCriterion("code is not null");
			return this;
		}

		public Criteria andCodeEqualTo(String value) {
			addCriterion("code =", value, "code");
			return this;
		}

		public Criteria andCodeNotEqualTo(String value) {
			addCriterion("code <>", value, "code");
			return this;
		}

		public Criteria andCodeGreaterThan(String value) {
			addCriterion("code >", value, "code");
			return this;
		}

		public Criteria andCodeGreaterThanOrEqualTo(String value) {
			addCriterion("code >=", value, "code");
			return this;
		}

		public Criteria andCodeLessThan(String value) {
			addCriterion("code <", value, "code");
			return this;
		}

		public Criteria andCodeLessThanOrEqualTo(String value) {
			addCriterion("code <=", value, "code");
			return this;
		}

		public Criteria andCodeLike(String value) {
			addCriterion("code like", value, "code");
			return this;
		}

		public Criteria andCodeNotLike(String value) {
			addCriterion("code not like", value, "code");
			return this;
		}

		public Criteria andCodeIn(List<String> values) {
			addCriterion("code in", values, "code");
			return this;
		}

		public Criteria andCodeNotIn(List<String> values) {
			addCriterion("code not in", values, "code");
			return this;
		}

		public Criteria andCodeBetween(String value1, String value2) {
			addCriterion("code between", value1, value2, "code");
			return this;
		}

		public Criteria andCodeNotBetween(String value1, String value2) {
			addCriterion("code not between", value1, value2, "code");
			return this;
		}

		public Criteria andIsactiveIsNull() {
			addCriterion("isActive is null");
			return this;
		}

		public Criteria andIsactiveIsNotNull() {
			addCriterion("isActive is not null");
			return this;
		}

		public Criteria andIsactiveEqualTo(String value) {
			addCriterion("isActive =", value, "isactive");
			return this;
		}

		public Criteria andIsactiveNotEqualTo(String value) {
			addCriterion("isActive <>", value, "isactive");
			return this;
		}

		public Criteria andIsactiveGreaterThan(String value) {
			addCriterion("isActive >", value, "isactive");
			return this;
		}

		public Criteria andIsactiveGreaterThanOrEqualTo(String value) {
			addCriterion("isActive >=", value, "isactive");
			return this;
		}

		public Criteria andIsactiveLessThan(String value) {
			addCriterion("isActive <", value, "isactive");
			return this;
		}

		public Criteria andIsactiveLessThanOrEqualTo(String value) {
			addCriterion("isActive <=", value, "isactive");
			return this;
		}

		public Criteria andIsactiveLike(String value) {
			addCriterion("isActive like", value, "isactive");
			return this;
		}

		public Criteria andIsactiveNotLike(String value) {
			addCriterion("isActive not like", value, "isactive");
			return this;
		}

		public Criteria andIsactiveIn(List<String> values) {
			addCriterion("isActive in", values, "isactive");
			return this;
		}

		public Criteria andIsactiveNotIn(List<String> values) {
			addCriterion("isActive not in", values, "isactive");
			return this;
		}

		public Criteria andIsactiveBetween(String value1, String value2) {
			addCriterion("isActive between", value1, value2, "isactive");
			return this;
		}

		public Criteria andIsactiveNotBetween(String value1, String value2) {
			addCriterion("isActive not between", value1, value2, "isactive");
			return this;
		}
	}
}