package com.et59.cus.domain.entity;

import java.util.Date;

public class BsLeavemessage {

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column bs_leavemessage.id
	 * @abatorgenerated
	 */
	private Long id;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column bs_leavemessage.name
	 * @abatorgenerated
	 */
	private String name;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column bs_leavemessage.message
	 * @abatorgenerated
	 */
	private String message;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column bs_leavemessage.telephone
	 * @abatorgenerated
	 */
	private String telephone;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column bs_leavemessage.email
	 * @abatorgenerated
	 */
	private String email;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column bs_leavemessage.leave_time
	 * @abatorgenerated
	 */
	private Date leaveTime;

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column bs_leavemessage.id
	 * @return  the value of bs_leavemessage.id
	 * @abatorgenerated
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column bs_leavemessage.id
	 * @param id  the value for bs_leavemessage.id
	 * @abatorgenerated
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column bs_leavemessage.name
	 * @return  the value of bs_leavemessage.name
	 * @abatorgenerated
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column bs_leavemessage.name
	 * @param name  the value for bs_leavemessage.name
	 * @abatorgenerated
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column bs_leavemessage.message
	 * @return  the value of bs_leavemessage.message
	 * @abatorgenerated
	 */
	public String getMessage() {
		return message;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column bs_leavemessage.message
	 * @param message  the value for bs_leavemessage.message
	 * @abatorgenerated
	 */
	public void setMessage(String message) {
		this.message = message == null ? null : message.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column bs_leavemessage.telephone
	 * @return  the value of bs_leavemessage.telephone
	 * @abatorgenerated
	 */
	public String getTelephone() {
		return telephone;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column bs_leavemessage.telephone
	 * @param telephone  the value for bs_leavemessage.telephone
	 * @abatorgenerated
	 */
	public void setTelephone(String telephone) {
		this.telephone = telephone == null ? null : telephone.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column bs_leavemessage.email
	 * @return  the value of bs_leavemessage.email
	 * @abatorgenerated
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column bs_leavemessage.email
	 * @param email  the value for bs_leavemessage.email
	 * @abatorgenerated
	 */
	public void setEmail(String email) {
		this.email = email == null ? null : email.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column bs_leavemessage.leave_time
	 * @return  the value of bs_leavemessage.leave_time
	 * @abatorgenerated
	 */
	public Date getLeaveTime() {
		return leaveTime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column bs_leavemessage.leave_time
	 * @param leaveTime  the value for bs_leavemessage.leave_time
	 * @abatorgenerated
	 */
	public void setLeaveTime(Date leaveTime) {
		this.leaveTime = leaveTime;
	}
}