package com.et59.cus.domain.entity;

public class BsMenu {

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column bs_menu.id
	 * @abatorgenerated
	 */
	private Long id;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column bs_menu.text
	 * @abatorgenerated
	 */
	private String text;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column bs_menu.menulevel
	 * @abatorgenerated
	 */
	private Integer menulevel;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column bs_menu.menuurl
	 * @abatorgenerated
	 */
	private String menuurl;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column bs_menu.menuorder
	 * @abatorgenerated
	 */
	private Integer menuorder;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column bs_menu.menuparent
	 * @abatorgenerated
	 */
	private Integer menuparent;

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column bs_menu.id
	 * @return  the value of bs_menu.id
	 * @abatorgenerated
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column bs_menu.id
	 * @param id  the value for bs_menu.id
	 * @abatorgenerated
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column bs_menu.text
	 * @return  the value of bs_menu.text
	 * @abatorgenerated
	 */
	public String getText() {
		return text;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column bs_menu.text
	 * @param text  the value for bs_menu.text
	 * @abatorgenerated
	 */
	public void setText(String text) {
		this.text = text == null ? null : text.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column bs_menu.menulevel
	 * @return  the value of bs_menu.menulevel
	 * @abatorgenerated
	 */
	public Integer getMenulevel() {
		return menulevel;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column bs_menu.menulevel
	 * @param menulevel  the value for bs_menu.menulevel
	 * @abatorgenerated
	 */
	public void setMenulevel(Integer menulevel) {
		this.menulevel = menulevel;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column bs_menu.menuurl
	 * @return  the value of bs_menu.menuurl
	 * @abatorgenerated
	 */
	public String getMenuurl() {
		return menuurl;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column bs_menu.menuurl
	 * @param menuurl  the value for bs_menu.menuurl
	 * @abatorgenerated
	 */
	public void setMenuurl(String menuurl) {
		this.menuurl = menuurl == null ? null : menuurl.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column bs_menu.menuorder
	 * @return  the value of bs_menu.menuorder
	 * @abatorgenerated
	 */
	public Integer getMenuorder() {
		return menuorder;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column bs_menu.menuorder
	 * @param menuorder  the value for bs_menu.menuorder
	 * @abatorgenerated
	 */
	public void setMenuorder(Integer menuorder) {
		this.menuorder = menuorder;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column bs_menu.menuparent
	 * @return  the value of bs_menu.menuparent
	 * @abatorgenerated
	 */
	public Integer getMenuparent() {
		return menuparent;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column bs_menu.menuparent
	 * @param menuparent  the value for bs_menu.menuparent
	 * @abatorgenerated
	 */
	public void setMenuparent(Integer menuparent) {
		this.menuparent = menuparent;
	}
}