package com.et59.cus.domain.entity;

public class BsPagestatic {

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column bs_pagestatic.id
	 * @abatorgenerated
	 */
	private Long id;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column bs_pagestatic.htmname
	 * @abatorgenerated
	 */
	private String htmname;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column bs_pagestatic.dynamicurl
	 * @abatorgenerated
	 */
	private String dynamicurl;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column bs_pagestatic.filepath
	 * @abatorgenerated
	 */
	private String filepath;

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column bs_pagestatic.id
	 * @return  the value of bs_pagestatic.id
	 * @abatorgenerated
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column bs_pagestatic.id
	 * @param id  the value for bs_pagestatic.id
	 * @abatorgenerated
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column bs_pagestatic.htmname
	 * @return  the value of bs_pagestatic.htmname
	 * @abatorgenerated
	 */
	public String getHtmname() {
		return htmname;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column bs_pagestatic.htmname
	 * @param htmname  the value for bs_pagestatic.htmname
	 * @abatorgenerated
	 */
	public void setHtmname(String htmname) {
		this.htmname = htmname == null ? null : htmname.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column bs_pagestatic.dynamicurl
	 * @return  the value of bs_pagestatic.dynamicurl
	 * @abatorgenerated
	 */
	public String getDynamicurl() {
		return dynamicurl;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column bs_pagestatic.dynamicurl
	 * @param dynamicurl  the value for bs_pagestatic.dynamicurl
	 * @abatorgenerated
	 */
	public void setDynamicurl(String dynamicurl) {
		this.dynamicurl = dynamicurl == null ? null : dynamicurl.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column bs_pagestatic.filepath
	 * @return  the value of bs_pagestatic.filepath
	 * @abatorgenerated
	 */
	public String getFilepath() {
		return filepath;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column bs_pagestatic.filepath
	 * @param filepath  the value for bs_pagestatic.filepath
	 * @abatorgenerated
	 */
	public void setFilepath(String filepath) {
		this.filepath = filepath == null ? null : filepath.trim();
	}
}