package com.et59.cus.domain.entity;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Date;

public class BsProductExample {

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database table bs_product
	 * @abatorgenerated
	 */
	protected String orderByClause;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database table bs_product
	 * @abatorgenerated
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_product
	 * @abatorgenerated
	 */
	public BsProductExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_product
	 * @abatorgenerated
	 */
	protected BsProductExample(BsProductExample example) {
		this.orderByClause = example.orderByClause;
		this.oredCriteria = example.oredCriteria;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_product
	 * @abatorgenerated
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_product
	 * @abatorgenerated
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_product
	 * @abatorgenerated
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_product
	 * @abatorgenerated
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_product
	 * @abatorgenerated
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_product
	 * @abatorgenerated
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table bs_product
	 * @abatorgenerated
	 */
	public void clear() {
		oredCriteria.clear();
	}

	/**
	 * This class was generated by Abator for iBATIS. This class corresponds to the database table bs_product
	 * @abatorgenerated
	 */
	public static class Criteria {
		protected List<String> criteriaWithoutValue;
		protected List<Map<String, Object>> criteriaWithSingleValue;
		protected List<Map<String, Object>> criteriaWithListValue;
		protected List<Map<String, Object>> criteriaWithBetweenValue;

		protected Criteria() {
			super();
			criteriaWithoutValue = new ArrayList<String>();
			criteriaWithSingleValue = new ArrayList<Map<String, Object>>();
			criteriaWithListValue = new ArrayList<Map<String, Object>>();
			criteriaWithBetweenValue = new ArrayList<Map<String, Object>>();
		}

		public boolean isValid() {
			return criteriaWithoutValue.size() > 0
					|| criteriaWithSingleValue.size() > 0
					|| criteriaWithListValue.size() > 0
					|| criteriaWithBetweenValue.size() > 0;
		}

		public List<String> getCriteriaWithoutValue() {
			return criteriaWithoutValue;
		}

		public List<Map<String, Object>> getCriteriaWithSingleValue() {
			return criteriaWithSingleValue;
		}

		public List<Map<String, Object>> getCriteriaWithListValue() {
			return criteriaWithListValue;
		}

		public List<Map<String, Object>> getCriteriaWithBetweenValue() {
			return criteriaWithBetweenValue;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteriaWithoutValue.add(condition);
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			Map<String, Object> map = new HashMap<String, Object>();
			map.put("condition", condition);
			map.put("value", value);
			criteriaWithSingleValue.add(map);
		}

		protected void addCriterion(String condition,
				List<? extends Object> values, String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property
						+ " cannot be null or empty");
			}
			Map<String, Object> map = new HashMap<String, Object>();
			map.put("condition", condition);
			map.put("values", values);
			criteriaWithListValue.add(map);
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			List<Object> list = new ArrayList<Object>();
			list.add(value1);
			list.add(value2);
			Map<String, Object> map = new HashMap<String, Object>();
			map.put("condition", condition);
			map.put("values", list);
			criteriaWithBetweenValue.add(map);
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return this;
		}

		public Criteria andIdEqualTo(Integer value) {
			addCriterion("id =", value, "id");
			return this;
		}

		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("id <>", value, "id");
			return this;
		}

		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("id >", value, "id");
			return this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("id >=", value, "id");
			return this;
		}

		public Criteria andIdLessThan(Integer value) {
			addCriterion("id <", value, "id");
			return this;
		}

		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("id <=", value, "id");
			return this;
		}

		public Criteria andIdIn(List<Integer> values) {
			addCriterion("id in", values, "id");
			return this;
		}

		public Criteria andIdNotIn(List<Integer> values) {
			addCriterion("id not in", values, "id");
			return this;
		}

		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("id between", value1, value2, "id");
			return this;
		}

		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("id not between", value1, value2, "id");
			return this;
		}

		public Criteria andProductCodeIsNull() {
			addCriterion("product_code is null");
			return this;
		}

		public Criteria andProductCodeIsNotNull() {
			addCriterion("product_code is not null");
			return this;
		}

		public Criteria andProductCodeEqualTo(String value) {
			addCriterion("product_code =", value, "productCode");
			return this;
		}

		public Criteria andProductCodeNotEqualTo(String value) {
			addCriterion("product_code <>", value, "productCode");
			return this;
		}

		public Criteria andProductCodeGreaterThan(String value) {
			addCriterion("product_code >", value, "productCode");
			return this;
		}

		public Criteria andProductCodeGreaterThanOrEqualTo(String value) {
			addCriterion("product_code >=", value, "productCode");
			return this;
		}

		public Criteria andProductCodeLessThan(String value) {
			addCriterion("product_code <", value, "productCode");
			return this;
		}

		public Criteria andProductCodeLessThanOrEqualTo(String value) {
			addCriterion("product_code <=", value, "productCode");
			return this;
		}

		public Criteria andProductCodeLike(String value) {
			addCriterion("product_code like", value, "productCode");
			return this;
		}

		public Criteria andProductCodeNotLike(String value) {
			addCriterion("product_code not like", value, "productCode");
			return this;
		}

		public Criteria andProductCodeIn(List<String> values) {
			addCriterion("product_code in", values, "productCode");
			return this;
		}

		public Criteria andProductCodeNotIn(List<String> values) {
			addCriterion("product_code not in", values, "productCode");
			return this;
		}

		public Criteria andProductCodeBetween(String value1, String value2) {
			addCriterion("product_code between", value1, value2, "productCode");
			return this;
		}

		public Criteria andProductCodeNotBetween(String value1, String value2) {
			addCriterion("product_code not between", value1, value2,
					"productCode");
			return this;
		}

		public Criteria andProductNameIsNull() {
			addCriterion("product_name is null");
			return this;
		}

		public Criteria andProductNameIsNotNull() {
			addCriterion("product_name is not null");
			return this;
		}

		public Criteria andProductNameEqualTo(String value) {
			addCriterion("product_name =", value, "productName");
			return this;
		}

		public Criteria andProductNameNotEqualTo(String value) {
			addCriterion("product_name <>", value, "productName");
			return this;
		}

		public Criteria andProductNameGreaterThan(String value) {
			addCriterion("product_name >", value, "productName");
			return this;
		}

		public Criteria andProductNameGreaterThanOrEqualTo(String value) {
			addCriterion("product_name >=", value, "productName");
			return this;
		}

		public Criteria andProductNameLessThan(String value) {
			addCriterion("product_name <", value, "productName");
			return this;
		}

		public Criteria andProductNameLessThanOrEqualTo(String value) {
			addCriterion("product_name <=", value, "productName");
			return this;
		}

		public Criteria andProductNameLike(String value) {
			addCriterion("product_name like", value, "productName");
			return this;
		}

		public Criteria andProductNameNotLike(String value) {
			addCriterion("product_name not like", value, "productName");
			return this;
		}

		public Criteria andProductNameIn(List<String> values) {
			addCriterion("product_name in", values, "productName");
			return this;
		}

		public Criteria andProductNameNotIn(List<String> values) {
			addCriterion("product_name not in", values, "productName");
			return this;
		}

		public Criteria andProductNameBetween(String value1, String value2) {
			addCriterion("product_name between", value1, value2, "productName");
			return this;
		}

		public Criteria andProductNameNotBetween(String value1, String value2) {
			addCriterion("product_name not between", value1, value2,
					"productName");
			return this;
		}

		public Criteria andProductPriceIsNull() {
			addCriterion("product_price is null");
			return this;
		}

		public Criteria andProductPriceIsNotNull() {
			addCriterion("product_price is not null");
			return this;
		}

		public Criteria andProductPriceEqualTo(BigDecimal value) {
			addCriterion("product_price =", value, "productPrice");
			return this;
		}

		public Criteria andProductPriceNotEqualTo(BigDecimal value) {
			addCriterion("product_price <>", value, "productPrice");
			return this;
		}

		public Criteria andProductPriceGreaterThan(BigDecimal value) {
			addCriterion("product_price >", value, "productPrice");
			return this;
		}

		public Criteria andProductPriceGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("product_price >=", value, "productPrice");
			return this;
		}

		public Criteria andProductPriceLessThan(BigDecimal value) {
			addCriterion("product_price <", value, "productPrice");
			return this;
		}

		public Criteria andProductPriceLessThanOrEqualTo(BigDecimal value) {
			addCriterion("product_price <=", value, "productPrice");
			return this;
		}

		public Criteria andProductPriceIn(List<BigDecimal> values) {
			addCriterion("product_price in", values, "productPrice");
			return this;
		}

		public Criteria andProductPriceNotIn(List<BigDecimal> values) {
			addCriterion("product_price not in", values, "productPrice");
			return this;
		}

		public Criteria andProductPriceBetween(BigDecimal value1,
				BigDecimal value2) {
			addCriterion("product_price between", value1, value2,
					"productPrice");
			return this;
		}

		public Criteria andProductPriceNotBetween(BigDecimal value1,
				BigDecimal value2) {
			addCriterion("product_price not between", value1, value2,
					"productPrice");
			return this;
		}

		public Criteria andProductImageUrlIsNull() {
			addCriterion("product_image_url is null");
			return this;
		}

		public Criteria andProductImageUrlIsNotNull() {
			addCriterion("product_image_url is not null");
			return this;
		}

		public Criteria andProductImageUrlEqualTo(String value) {
			addCriterion("product_image_url =", value, "productImageUrl");
			return this;
		}

		public Criteria andProductImageUrlNotEqualTo(String value) {
			addCriterion("product_image_url <>", value, "productImageUrl");
			return this;
		}

		public Criteria andProductImageUrlGreaterThan(String value) {
			addCriterion("product_image_url >", value, "productImageUrl");
			return this;
		}

		public Criteria andProductImageUrlGreaterThanOrEqualTo(String value) {
			addCriterion("product_image_url >=", value, "productImageUrl");
			return this;
		}

		public Criteria andProductImageUrlLessThan(String value) {
			addCriterion("product_image_url <", value, "productImageUrl");
			return this;
		}

		public Criteria andProductImageUrlLessThanOrEqualTo(String value) {
			addCriterion("product_image_url <=", value, "productImageUrl");
			return this;
		}

		public Criteria andProductImageUrlLike(String value) {
			addCriterion("product_image_url like", value, "productImageUrl");
			return this;
		}

		public Criteria andProductImageUrlNotLike(String value) {
			addCriterion("product_image_url not like", value, "productImageUrl");
			return this;
		}

		public Criteria andProductImageUrlIn(List<String> values) {
			addCriterion("product_image_url in", values, "productImageUrl");
			return this;
		}

		public Criteria andProductImageUrlNotIn(List<String> values) {
			addCriterion("product_image_url not in", values, "productImageUrl");
			return this;
		}

		public Criteria andProductImageUrlBetween(String value1, String value2) {
			addCriterion("product_image_url between", value1, value2,
					"productImageUrl");
			return this;
		}

		public Criteria andProductImageUrlNotBetween(String value1,
				String value2) {
			addCriterion("product_image_url not between", value1, value2,
					"productImageUrl");
			return this;
		}

		public Criteria andProductInfoIsNull() {
			addCriterion("product_info is null");
			return this;
		}

		public Criteria andProductInfoIsNotNull() {
			addCriterion("product_info is not null");
			return this;
		}

		public Criteria andProductInfoEqualTo(String value) {
			addCriterion("product_info =", value, "productInfo");
			return this;
		}

		public Criteria andProductInfoNotEqualTo(String value) {
			addCriterion("product_info <>", value, "productInfo");
			return this;
		}

		public Criteria andProductInfoGreaterThan(String value) {
			addCriterion("product_info >", value, "productInfo");
			return this;
		}

		public Criteria andProductInfoGreaterThanOrEqualTo(String value) {
			addCriterion("product_info >=", value, "productInfo");
			return this;
		}

		public Criteria andProductInfoLessThan(String value) {
			addCriterion("product_info <", value, "productInfo");
			return this;
		}

		public Criteria andProductInfoLessThanOrEqualTo(String value) {
			addCriterion("product_info <=", value, "productInfo");
			return this;
		}

		public Criteria andProductInfoLike(String value) {
			addCriterion("product_info like", value, "productInfo");
			return this;
		}

		public Criteria andProductInfoNotLike(String value) {
			addCriterion("product_info not like", value, "productInfo");
			return this;
		}

		public Criteria andProductInfoIn(List<String> values) {
			addCriterion("product_info in", values, "productInfo");
			return this;
		}

		public Criteria andProductInfoNotIn(List<String> values) {
			addCriterion("product_info not in", values, "productInfo");
			return this;
		}

		public Criteria andProductInfoBetween(String value1, String value2) {
			addCriterion("product_info between", value1, value2, "productInfo");
			return this;
		}

		public Criteria andProductInfoNotBetween(String value1, String value2) {
			addCriterion("product_info not between", value1, value2,
					"productInfo");
			return this;
		}

		public Criteria andProductcategoryCodeIsNull() {
			addCriterion("productcategory_code is null");
			return this;
		}

		public Criteria andProductcategoryCodeIsNotNull() {
			addCriterion("productcategory_code is not null");
			return this;
		}

		public Criteria andProductcategoryCodeEqualTo(String value) {
			addCriterion("productcategory_code =", value, "productcategoryCode");
			return this;
		}

		public Criteria andProductcategoryCodeNotEqualTo(String value) {
			addCriterion("productcategory_code <>", value,
					"productcategoryCode");
			return this;
		}

		public Criteria andProductcategoryCodeGreaterThan(String value) {
			addCriterion("productcategory_code >", value, "productcategoryCode");
			return this;
		}

		public Criteria andProductcategoryCodeGreaterThanOrEqualTo(String value) {
			addCriterion("productcategory_code >=", value,
					"productcategoryCode");
			return this;
		}

		public Criteria andProductcategoryCodeLessThan(String value) {
			addCriterion("productcategory_code <", value, "productcategoryCode");
			return this;
		}

		public Criteria andProductcategoryCodeLessThanOrEqualTo(String value) {
			addCriterion("productcategory_code <=", value,
					"productcategoryCode");
			return this;
		}

		public Criteria andProductcategoryCodeLike(String value) {
			addCriterion("productcategory_code like", value,
					"productcategoryCode");
			return this;
		}

		public Criteria andProductcategoryCodeNotLike(String value) {
			addCriterion("productcategory_code not like", value,
					"productcategoryCode");
			return this;
		}

		public Criteria andProductcategoryCodeIn(List<String> values) {
			addCriterion("productcategory_code in", values,
					"productcategoryCode");
			return this;
		}

		public Criteria andProductcategoryCodeNotIn(List<String> values) {
			addCriterion("productcategory_code not in", values,
					"productcategoryCode");
			return this;
		}

		public Criteria andProductcategoryCodeBetween(String value1,
				String value2) {
			addCriterion("productcategory_code between", value1, value2,
					"productcategoryCode");
			return this;
		}

		public Criteria andProductcategoryCodeNotBetween(String value1,
				String value2) {
			addCriterion("productcategory_code not between", value1, value2,
					"productcategoryCode");
			return this;
		}

		public Criteria andSupplierCodeIsNull() {
			addCriterion("supplier_code is null");
			return this;
		}

		public Criteria andSupplierCodeIsNotNull() {
			addCriterion("supplier_code is not null");
			return this;
		}

		public Criteria andSupplierCodeEqualTo(String value) {
			addCriterion("supplier_code =", value, "supplierCode");
			return this;
		}

		public Criteria andSupplierCodeNotEqualTo(String value) {
			addCriterion("supplier_code <>", value, "supplierCode");
			return this;
		}

		public Criteria andSupplierCodeGreaterThan(String value) {
			addCriterion("supplier_code >", value, "supplierCode");
			return this;
		}

		public Criteria andSupplierCodeGreaterThanOrEqualTo(String value) {
			addCriterion("supplier_code >=", value, "supplierCode");
			return this;
		}

		public Criteria andSupplierCodeLessThan(String value) {
			addCriterion("supplier_code <", value, "supplierCode");
			return this;
		}

		public Criteria andSupplierCodeLessThanOrEqualTo(String value) {
			addCriterion("supplier_code <=", value, "supplierCode");
			return this;
		}

		public Criteria andSupplierCodeLike(String value) {
			addCriterion("supplier_code like", value, "supplierCode");
			return this;
		}

		public Criteria andSupplierCodeNotLike(String value) {
			addCriterion("supplier_code not like", value, "supplierCode");
			return this;
		}

		public Criteria andSupplierCodeIn(List<String> values) {
			addCriterion("supplier_code in", values, "supplierCode");
			return this;
		}

		public Criteria andSupplierCodeNotIn(List<String> values) {
			addCriterion("supplier_code not in", values, "supplierCode");
			return this;
		}

		public Criteria andSupplierCodeBetween(String value1, String value2) {
			addCriterion("supplier_code between", value1, value2,
					"supplierCode");
			return this;
		}

		public Criteria andSupplierCodeNotBetween(String value1, String value2) {
			addCriterion("supplier_code not between", value1, value2,
					"supplierCode");
			return this;
		}

		public Criteria andIsacticeIsNull() {
			addCriterion("isactice is null");
			return this;
		}

		public Criteria andIsacticeIsNotNull() {
			addCriterion("isactice is not null");
			return this;
		}

		public Criteria andIsacticeEqualTo(String value) {
			addCriterion("isactice =", value, "isactice");
			return this;
		}

		public Criteria andIsacticeNotEqualTo(String value) {
			addCriterion("isactice <>", value, "isactice");
			return this;
		}

		public Criteria andIsacticeGreaterThan(String value) {
			addCriterion("isactice >", value, "isactice");
			return this;
		}

		public Criteria andIsacticeGreaterThanOrEqualTo(String value) {
			addCriterion("isactice >=", value, "isactice");
			return this;
		}

		public Criteria andIsacticeLessThan(String value) {
			addCriterion("isactice <", value, "isactice");
			return this;
		}

		public Criteria andIsacticeLessThanOrEqualTo(String value) {
			addCriterion("isactice <=", value, "isactice");
			return this;
		}

		public Criteria andIsacticeLike(String value) {
			addCriterion("isactice like", value, "isactice");
			return this;
		}

		public Criteria andIsacticeNotLike(String value) {
			addCriterion("isactice not like", value, "isactice");
			return this;
		}

		public Criteria andIsacticeIn(List<String> values) {
			addCriterion("isactice in", values, "isactice");
			return this;
		}

		public Criteria andIsacticeNotIn(List<String> values) {
			addCriterion("isactice not in", values, "isactice");
			return this;
		}

		public Criteria andIsacticeBetween(String value1, String value2) {
			addCriterion("isactice between", value1, value2, "isactice");
			return this;
		}

		public Criteria andIsacticeNotBetween(String value1, String value2) {
			addCriterion("isactice not between", value1, value2, "isactice");
			return this;
		}

		public Criteria andCreatedateIsNull() {
			addCriterion("createdate is null");
			return this;
		}

		public Criteria andCreatedateIsNotNull() {
			addCriterion("createdate is not null");
			return this;
		}

		public Criteria andCreatedateEqualTo(Date value) {
			addCriterion("createdate =", value, "createdate");
			return this;
		}

		public Criteria andCreatedateNotEqualTo(Date value) {
			addCriterion("createdate <>", value, "createdate");
			return this;
		}

		public Criteria andCreatedateGreaterThan(Date value) {
			addCriterion("createdate >", value, "createdate");
			return this;
		}

		public Criteria andCreatedateGreaterThanOrEqualTo(Date value) {
			addCriterion("createdate >=", value, "createdate");
			return this;
		}

		public Criteria andCreatedateLessThan(Date value) {
			addCriterion("createdate <", value, "createdate");
			return this;
		}

		public Criteria andCreatedateLessThanOrEqualTo(Date value) {
			addCriterion("createdate <=", value, "createdate");
			return this;
		}

		public Criteria andCreatedateIn(List<Date> values) {
			addCriterion("createdate in", values, "createdate");
			return this;
		}

		public Criteria andCreatedateNotIn(List<Date> values) {
			addCriterion("createdate not in", values, "createdate");
			return this;
		}

		public Criteria andCreatedateBetween(Date value1, Date value2) {
			addCriterion("createdate between", value1, value2, "createdate");
			return this;
		}

		public Criteria andCreatedateNotBetween(Date value1, Date value2) {
			addCriterion("createdate not between", value1, value2, "createdate");
			return this;
		}
	}
}