package com.et59.cus.domain.entity;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class BsUserservice implements Serializable {

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column bs_userservice.id
	 * @abatorgenerated
	 */
	private Integer id;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column bs_userservice.user_id
	 * @abatorgenerated
	 */
	private String userId;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column bs_userservice.product_name
	 * @abatorgenerated
	 */
	private String productName;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column bs_userservice.product_price
	 * @abatorgenerated
	 */
	private BigDecimal productPrice;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column bs_userservice.product_code
	 * @abatorgenerated
	 */
	private String productCode;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column bs_userservice.service_end_time
	 * @abatorgenerated
	 */
	private Date serviceEndTime;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column bs_userservice.order_iccard
	 * @abatorgenerated
	 */
	private String orderIccard;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column bs_userservice.product_id
	 * @abatorgenerated
	 */
	private Long productId;

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column bs_userservice.id
	 * @return  the value of bs_userservice.id
	 * @abatorgenerated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column bs_userservice.id
	 * @param id  the value for bs_userservice.id
	 * @abatorgenerated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column bs_userservice.user_id
	 * @return  the value of bs_userservice.user_id
	 * @abatorgenerated
	 */
	public String getUserId() {
		return userId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column bs_userservice.user_id
	 * @param userId  the value for bs_userservice.user_id
	 * @abatorgenerated
	 */
	public void setUserId(String userId) {
		this.userId = userId == null ? null : userId.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column bs_userservice.product_name
	 * @return  the value of bs_userservice.product_name
	 * @abatorgenerated
	 */
	public String getProductName() {
		return productName;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column bs_userservice.product_name
	 * @param productName  the value for bs_userservice.product_name
	 * @abatorgenerated
	 */
	public void setProductName(String productName) {
		this.productName = productName == null ? null : productName.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column bs_userservice.product_price
	 * @return  the value of bs_userservice.product_price
	 * @abatorgenerated
	 */
	public BigDecimal getProductPrice() {
		return productPrice;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column bs_userservice.product_price
	 * @param productPrice  the value for bs_userservice.product_price
	 * @abatorgenerated
	 */
	public void setProductPrice(BigDecimal productPrice) {
		this.productPrice = productPrice;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column bs_userservice.product_code
	 * @return  the value of bs_userservice.product_code
	 * @abatorgenerated
	 */
	public String getProductCode() {
		return productCode;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column bs_userservice.product_code
	 * @param productCode  the value for bs_userservice.product_code
	 * @abatorgenerated
	 */
	public void setProductCode(String productCode) {
		this.productCode = productCode == null ? null : productCode.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column bs_userservice.service_end_time
	 * @return  the value of bs_userservice.service_end_time
	 * @abatorgenerated
	 */
	public Date getServiceEndTime() {
		return serviceEndTime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column bs_userservice.service_end_time
	 * @param serviceEndTime  the value for bs_userservice.service_end_time
	 * @abatorgenerated
	 */
	public void setServiceEndTime(Date serviceEndTime) {
		this.serviceEndTime = serviceEndTime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column bs_userservice.order_iccard
	 * @return  the value of bs_userservice.order_iccard
	 * @abatorgenerated
	 */
	public String getOrderIccard() {
		return orderIccard;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column bs_userservice.order_iccard
	 * @param orderIccard  the value for bs_userservice.order_iccard
	 * @abatorgenerated
	 */
	public void setOrderIccard(String orderIccard) {
		this.orderIccard = orderIccard == null ? null : orderIccard.trim();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column bs_userservice.product_id
	 * @return  the value of bs_userservice.product_id
	 * @abatorgenerated
	 */
	public Long getProductId() {
		return productId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column bs_userservice.product_id
	 * @param productId  the value for bs_userservice.product_id
	 * @abatorgenerated
	 */
	public void setProductId(Long productId) {
		this.productId = productId;
	}
}