package com.et59.cus.domain.entity;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class OpenApiExample {

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database table open_api
	 * @abatorgenerated
	 */
	protected String orderByClause;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database table open_api
	 * @abatorgenerated
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table open_api
	 * @abatorgenerated
	 */
	public OpenApiExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table open_api
	 * @abatorgenerated
	 */
	protected OpenApiExample(OpenApiExample example) {
		this.orderByClause = example.orderByClause;
		this.oredCriteria = example.oredCriteria;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table open_api
	 * @abatorgenerated
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table open_api
	 * @abatorgenerated
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table open_api
	 * @abatorgenerated
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table open_api
	 * @abatorgenerated
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table open_api
	 * @abatorgenerated
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table open_api
	 * @abatorgenerated
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds to the database table open_api
	 * @abatorgenerated
	 */
	public void clear() {
		oredCriteria.clear();
	}

	/**
	 * This class was generated by Abator for iBATIS. This class corresponds to the database table open_api
	 * @abatorgenerated
	 */
	public static class Criteria {
		protected List<String> criteriaWithoutValue;
		protected List<Map<String, Object>> criteriaWithSingleValue;
		protected List<Map<String, Object>> criteriaWithListValue;
		protected List<Map<String, Object>> criteriaWithBetweenValue;

		protected Criteria() {
			super();
			criteriaWithoutValue = new ArrayList<String>();
			criteriaWithSingleValue = new ArrayList<Map<String, Object>>();
			criteriaWithListValue = new ArrayList<Map<String, Object>>();
			criteriaWithBetweenValue = new ArrayList<Map<String, Object>>();
		}

		public boolean isValid() {
			return criteriaWithoutValue.size() > 0
					|| criteriaWithSingleValue.size() > 0
					|| criteriaWithListValue.size() > 0
					|| criteriaWithBetweenValue.size() > 0;
		}

		public List<String> getCriteriaWithoutValue() {
			return criteriaWithoutValue;
		}

		public List<Map<String, Object>> getCriteriaWithSingleValue() {
			return criteriaWithSingleValue;
		}

		public List<Map<String, Object>> getCriteriaWithListValue() {
			return criteriaWithListValue;
		}

		public List<Map<String, Object>> getCriteriaWithBetweenValue() {
			return criteriaWithBetweenValue;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteriaWithoutValue.add(condition);
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			Map<String, Object> map = new HashMap<String, Object>();
			map.put("condition", condition);
			map.put("value", value);
			criteriaWithSingleValue.add(map);
		}

		protected void addCriterion(String condition,
				List<? extends Object> values, String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property
						+ " cannot be null or empty");
			}
			Map<String, Object> map = new HashMap<String, Object>();
			map.put("condition", condition);
			map.put("values", values);
			criteriaWithListValue.add(map);
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			List<Object> list = new ArrayList<Object>();
			list.add(value1);
			list.add(value2);
			Map<String, Object> map = new HashMap<String, Object>();
			map.put("condition", condition);
			map.put("values", list);
			criteriaWithBetweenValue.add(map);
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return this;
		}

		public Criteria andIdEqualTo(Long value) {
			addCriterion("id =", value, "id");
			return this;
		}

		public Criteria andIdNotEqualTo(Long value) {
			addCriterion("id <>", value, "id");
			return this;
		}

		public Criteria andIdGreaterThan(Long value) {
			addCriterion("id >", value, "id");
			return this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Long value) {
			addCriterion("id >=", value, "id");
			return this;
		}

		public Criteria andIdLessThan(Long value) {
			addCriterion("id <", value, "id");
			return this;
		}

		public Criteria andIdLessThanOrEqualTo(Long value) {
			addCriterion("id <=", value, "id");
			return this;
		}

		public Criteria andIdIn(List<Long> values) {
			addCriterion("id in", values, "id");
			return this;
		}

		public Criteria andIdNotIn(List<Long> values) {
			addCriterion("id not in", values, "id");
			return this;
		}

		public Criteria andIdBetween(Long value1, Long value2) {
			addCriterion("id between", value1, value2, "id");
			return this;
		}

		public Criteria andIdNotBetween(Long value1, Long value2) {
			addCriterion("id not between", value1, value2, "id");
			return this;
		}

		public Criteria andTextIsNull() {
			addCriterion("text is null");
			return this;
		}

		public Criteria andTextIsNotNull() {
			addCriterion("text is not null");
			return this;
		}

		public Criteria andTextEqualTo(String value) {
			addCriterion("text =", value, "text");
			return this;
		}

		public Criteria andTextNotEqualTo(String value) {
			addCriterion("text <>", value, "text");
			return this;
		}

		public Criteria andTextGreaterThan(String value) {
			addCriterion("text >", value, "text");
			return this;
		}

		public Criteria andTextGreaterThanOrEqualTo(String value) {
			addCriterion("text >=", value, "text");
			return this;
		}

		public Criteria andTextLessThan(String value) {
			addCriterion("text <", value, "text");
			return this;
		}

		public Criteria andTextLessThanOrEqualTo(String value) {
			addCriterion("text <=", value, "text");
			return this;
		}

		public Criteria andTextLike(String value) {
			addCriterion("text like", value, "text");
			return this;
		}

		public Criteria andTextNotLike(String value) {
			addCriterion("text not like", value, "text");
			return this;
		}

		public Criteria andTextIn(List<String> values) {
			addCriterion("text in", values, "text");
			return this;
		}

		public Criteria andTextNotIn(List<String> values) {
			addCriterion("text not in", values, "text");
			return this;
		}

		public Criteria andTextBetween(String value1, String value2) {
			addCriterion("text between", value1, value2, "text");
			return this;
		}

		public Criteria andTextNotBetween(String value1, String value2) {
			addCriterion("text not between", value1, value2, "text");
			return this;
		}

		public Criteria andApiurlIsNull() {
			addCriterion("apiurl is null");
			return this;
		}

		public Criteria andApiurlIsNotNull() {
			addCriterion("apiurl is not null");
			return this;
		}

		public Criteria andApiurlEqualTo(String value) {
			addCriterion("apiurl =", value, "apiurl");
			return this;
		}

		public Criteria andApiurlNotEqualTo(String value) {
			addCriterion("apiurl <>", value, "apiurl");
			return this;
		}

		public Criteria andApiurlGreaterThan(String value) {
			addCriterion("apiurl >", value, "apiurl");
			return this;
		}

		public Criteria andApiurlGreaterThanOrEqualTo(String value) {
			addCriterion("apiurl >=", value, "apiurl");
			return this;
		}

		public Criteria andApiurlLessThan(String value) {
			addCriterion("apiurl <", value, "apiurl");
			return this;
		}

		public Criteria andApiurlLessThanOrEqualTo(String value) {
			addCriterion("apiurl <=", value, "apiurl");
			return this;
		}

		public Criteria andApiurlLike(String value) {
			addCriterion("apiurl like", value, "apiurl");
			return this;
		}

		public Criteria andApiurlNotLike(String value) {
			addCriterion("apiurl not like", value, "apiurl");
			return this;
		}

		public Criteria andApiurlIn(List<String> values) {
			addCriterion("apiurl in", values, "apiurl");
			return this;
		}

		public Criteria andApiurlNotIn(List<String> values) {
			addCriterion("apiurl not in", values, "apiurl");
			return this;
		}

		public Criteria andApiurlBetween(String value1, String value2) {
			addCriterion("apiurl between", value1, value2, "apiurl");
			return this;
		}

		public Criteria andApiurlNotBetween(String value1, String value2) {
			addCriterion("apiurl not between", value1, value2, "apiurl");
			return this;
		}

		public Criteria andApitypeIsNull() {
			addCriterion("apitype is null");
			return this;
		}

		public Criteria andApitypeIsNotNull() {
			addCriterion("apitype is not null");
			return this;
		}

		public Criteria andApitypeEqualTo(String value) {
			addCriterion("apitype =", value, "apitype");
			return this;
		}

		public Criteria andApitypeNotEqualTo(String value) {
			addCriterion("apitype <>", value, "apitype");
			return this;
		}

		public Criteria andApitypeGreaterThan(String value) {
			addCriterion("apitype >", value, "apitype");
			return this;
		}

		public Criteria andApitypeGreaterThanOrEqualTo(String value) {
			addCriterion("apitype >=", value, "apitype");
			return this;
		}

		public Criteria andApitypeLessThan(String value) {
			addCriterion("apitype <", value, "apitype");
			return this;
		}

		public Criteria andApitypeLessThanOrEqualTo(String value) {
			addCriterion("apitype <=", value, "apitype");
			return this;
		}

		public Criteria andApitypeLike(String value) {
			addCriterion("apitype like", value, "apitype");
			return this;
		}

		public Criteria andApitypeNotLike(String value) {
			addCriterion("apitype not like", value, "apitype");
			return this;
		}

		public Criteria andApitypeIn(List<String> values) {
			addCriterion("apitype in", values, "apitype");
			return this;
		}

		public Criteria andApitypeNotIn(List<String> values) {
			addCriterion("apitype not in", values, "apitype");
			return this;
		}

		public Criteria andApitypeBetween(String value1, String value2) {
			addCriterion("apitype between", value1, value2, "apitype");
			return this;
		}

		public Criteria andApitypeNotBetween(String value1, String value2) {
			addCriterion("apitype not between", value1, value2, "apitype");
			return this;
		}

		public Criteria andHttptypeIsNull() {
			addCriterion("httptype is null");
			return this;
		}

		public Criteria andHttptypeIsNotNull() {
			addCriterion("httptype is not null");
			return this;
		}

		public Criteria andHttptypeEqualTo(String value) {
			addCriterion("httptype =", value, "httptype");
			return this;
		}

		public Criteria andHttptypeNotEqualTo(String value) {
			addCriterion("httptype <>", value, "httptype");
			return this;
		}

		public Criteria andHttptypeGreaterThan(String value) {
			addCriterion("httptype >", value, "httptype");
			return this;
		}

		public Criteria andHttptypeGreaterThanOrEqualTo(String value) {
			addCriterion("httptype >=", value, "httptype");
			return this;
		}

		public Criteria andHttptypeLessThan(String value) {
			addCriterion("httptype <", value, "httptype");
			return this;
		}

		public Criteria andHttptypeLessThanOrEqualTo(String value) {
			addCriterion("httptype <=", value, "httptype");
			return this;
		}

		public Criteria andHttptypeLike(String value) {
			addCriterion("httptype like", value, "httptype");
			return this;
		}

		public Criteria andHttptypeNotLike(String value) {
			addCriterion("httptype not like", value, "httptype");
			return this;
		}

		public Criteria andHttptypeIn(List<String> values) {
			addCriterion("httptype in", values, "httptype");
			return this;
		}

		public Criteria andHttptypeNotIn(List<String> values) {
			addCriterion("httptype not in", values, "httptype");
			return this;
		}

		public Criteria andHttptypeBetween(String value1, String value2) {
			addCriterion("httptype between", value1, value2, "httptype");
			return this;
		}

		public Criteria andHttptypeNotBetween(String value1, String value2) {
			addCriterion("httptype not between", value1, value2, "httptype");
			return this;
		}

		public Criteria andParentIsNull() {
			addCriterion("parent is null");
			return this;
		}

		public Criteria andParentIsNotNull() {
			addCriterion("parent is not null");
			return this;
		}

		public Criteria andParentEqualTo(Long value) {
			addCriterion("parent =", value, "parent");
			return this;
		}

		public Criteria andParentNotEqualTo(Long value) {
			addCriterion("parent <>", value, "parent");
			return this;
		}

		public Criteria andParentGreaterThan(Long value) {
			addCriterion("parent >", value, "parent");
			return this;
		}

		public Criteria andParentGreaterThanOrEqualTo(Long value) {
			addCriterion("parent >=", value, "parent");
			return this;
		}

		public Criteria andParentLessThan(Long value) {
			addCriterion("parent <", value, "parent");
			return this;
		}

		public Criteria andParentLessThanOrEqualTo(Long value) {
			addCriterion("parent <=", value, "parent");
			return this;
		}

		public Criteria andParentIn(List<Long> values) {
			addCriterion("parent in", values, "parent");
			return this;
		}

		public Criteria andParentNotIn(List<Long> values) {
			addCriterion("parent not in", values, "parent");
			return this;
		}

		public Criteria andParentBetween(Long value1, Long value2) {
			addCriterion("parent between", value1, value2, "parent");
			return this;
		}

		public Criteria andParentNotBetween(Long value1, Long value2) {
			addCriterion("parent not between", value1, value2, "parent");
			return this;
		}
	}
}