package com.et59.cus.domain.entity;

public class TDepartment {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t_department.departmentId
	 * @ibatorgenerated  Thu Mar 26 17:53:45 CST 2015
	 */
	private Long departmentid;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t_department.departmentType
	 * @ibatorgenerated  Thu Mar 26 17:53:45 CST 2015
	 */
	private String departmenttype;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t_department.departmentName
	 * @ibatorgenerated  Thu Mar 26 17:53:45 CST 2015
	 */
	private String departmentname;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t_department.departmentPlanForOne
	 * @ibatorgenerated  Thu Mar 26 17:53:45 CST 2015
	 */
	private Long departmentplanforone;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t_department.departmentPlanForTwo
	 * @ibatorgenerated  Thu Mar 26 17:53:45 CST 2015
	 */
	private Long departmentplanfortwo;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t_department.departmentPlanForThree
	 * @ibatorgenerated  Thu Mar 26 17:53:45 CST 2015
	 */
	private Long departmentplanforthree;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t_department.departmentPlanForFour
	 * @ibatorgenerated  Thu Mar 26 17:53:45 CST 2015
	 */
	private Long departmentplanforfour;

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_department.departmentId
	 * @return  the value of t_department.departmentId
	 * @ibatorgenerated  Thu Mar 26 17:53:45 CST 2015
	 */
	public Long getDepartmentid() {
		return departmentid;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_department.departmentId
	 * @param departmentid  the value for t_department.departmentId
	 * @ibatorgenerated  Thu Mar 26 17:53:45 CST 2015
	 */
	public void setDepartmentid(Long departmentid) {
		this.departmentid = departmentid;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_department.departmentType
	 * @return  the value of t_department.departmentType
	 * @ibatorgenerated  Thu Mar 26 17:53:45 CST 2015
	 */
	public String getDepartmenttype() {
		return departmenttype;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_department.departmentType
	 * @param departmenttype  the value for t_department.departmentType
	 * @ibatorgenerated  Thu Mar 26 17:53:45 CST 2015
	 */
	public void setDepartmenttype(String departmenttype) {
		this.departmenttype = departmenttype;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_department.departmentName
	 * @return  the value of t_department.departmentName
	 * @ibatorgenerated  Thu Mar 26 17:53:45 CST 2015
	 */
	public String getDepartmentname() {
		return departmentname;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_department.departmentName
	 * @param departmentname  the value for t_department.departmentName
	 * @ibatorgenerated  Thu Mar 26 17:53:45 CST 2015
	 */
	public void setDepartmentname(String departmentname) {
		this.departmentname = departmentname;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_department.departmentPlanForOne
	 * @return  the value of t_department.departmentPlanForOne
	 * @ibatorgenerated  Thu Mar 26 17:53:45 CST 2015
	 */
	public Long getDepartmentplanforone() {
		return departmentplanforone;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_department.departmentPlanForOne
	 * @param departmentplanforone  the value for t_department.departmentPlanForOne
	 * @ibatorgenerated  Thu Mar 26 17:53:45 CST 2015
	 */
	public void setDepartmentplanforone(Long departmentplanforone) {
		this.departmentplanforone = departmentplanforone;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_department.departmentPlanForTwo
	 * @return  the value of t_department.departmentPlanForTwo
	 * @ibatorgenerated  Thu Mar 26 17:53:45 CST 2015
	 */
	public Long getDepartmentplanfortwo() {
		return departmentplanfortwo;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_department.departmentPlanForTwo
	 * @param departmentplanfortwo  the value for t_department.departmentPlanForTwo
	 * @ibatorgenerated  Thu Mar 26 17:53:45 CST 2015
	 */
	public void setDepartmentplanfortwo(Long departmentplanfortwo) {
		this.departmentplanfortwo = departmentplanfortwo;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_department.departmentPlanForThree
	 * @return  the value of t_department.departmentPlanForThree
	 * @ibatorgenerated  Thu Mar 26 17:53:45 CST 2015
	 */
	public Long getDepartmentplanforthree() {
		return departmentplanforthree;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_department.departmentPlanForThree
	 * @param departmentplanforthree  the value for t_department.departmentPlanForThree
	 * @ibatorgenerated  Thu Mar 26 17:53:45 CST 2015
	 */
	public void setDepartmentplanforthree(Long departmentplanforthree) {
		this.departmentplanforthree = departmentplanforthree;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_department.departmentPlanForFour
	 * @return  the value of t_department.departmentPlanForFour
	 * @ibatorgenerated  Thu Mar 26 17:53:45 CST 2015
	 */
	public Long getDepartmentplanforfour() {
		return departmentplanforfour;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_department.departmentPlanForFour
	 * @param departmentplanforfour  the value for t_department.departmentPlanForFour
	 * @ibatorgenerated  Thu Mar 26 17:53:45 CST 2015
	 */
	public void setDepartmentplanforfour(Long departmentplanforfour) {
		this.departmentplanforfour = departmentplanforfour;
	}
}