package com.et59.cus.domain.entity;

public class TDictionary {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t_dictionary.dictionaryid
	 * @ibatorgenerated  Sun Feb 22 22:16:26 CST 2015
	 */
	private Integer dictionaryid;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t_dictionary.dictionarycode
	 * @ibatorgenerated  Sun Feb 22 22:16:26 CST 2015
	 */
	private String dictionarycode;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t_dictionary.dictionaryvalue
	 * @ibatorgenerated  Sun Feb 22 22:16:26 CST 2015
	 */
	private String dictionaryvalue;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t_dictionary.dictionaryType
	 * @ibatorgenerated  Sun Feb 22 22:16:26 CST 2015
	 */
	private String dictionarytype;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column t_dictionary.dictionaryremark
	 * @ibatorgenerated  Sun Feb 22 22:16:26 CST 2015
	 */
	private String dictionaryremark;

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_dictionary.dictionaryid
	 * @return  the value of t_dictionary.dictionaryid
	 * @ibatorgenerated  Sun Feb 22 22:16:26 CST 2015
	 */
	public Integer getDictionaryid() {
		return dictionaryid;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_dictionary.dictionaryid
	 * @param dictionaryid  the value for t_dictionary.dictionaryid
	 * @ibatorgenerated  Sun Feb 22 22:16:26 CST 2015
	 */
	public void setDictionaryid(Integer dictionaryid) {
		this.dictionaryid = dictionaryid;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_dictionary.dictionarycode
	 * @return  the value of t_dictionary.dictionarycode
	 * @ibatorgenerated  Sun Feb 22 22:16:26 CST 2015
	 */
	public String getDictionarycode() {
		return dictionarycode;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_dictionary.dictionarycode
	 * @param dictionarycode  the value for t_dictionary.dictionarycode
	 * @ibatorgenerated  Sun Feb 22 22:16:26 CST 2015
	 */
	public void setDictionarycode(String dictionarycode) {
		this.dictionarycode = dictionarycode;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_dictionary.dictionaryvalue
	 * @return  the value of t_dictionary.dictionaryvalue
	 * @ibatorgenerated  Sun Feb 22 22:16:26 CST 2015
	 */
	public String getDictionaryvalue() {
		return dictionaryvalue;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_dictionary.dictionaryvalue
	 * @param dictionaryvalue  the value for t_dictionary.dictionaryvalue
	 * @ibatorgenerated  Sun Feb 22 22:16:26 CST 2015
	 */
	public void setDictionaryvalue(String dictionaryvalue) {
		this.dictionaryvalue = dictionaryvalue;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_dictionary.dictionaryType
	 * @return  the value of t_dictionary.dictionaryType
	 * @ibatorgenerated  Sun Feb 22 22:16:26 CST 2015
	 */
	public String getDictionarytype() {
		return dictionarytype;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_dictionary.dictionaryType
	 * @param dictionarytype  the value for t_dictionary.dictionaryType
	 * @ibatorgenerated  Sun Feb 22 22:16:26 CST 2015
	 */
	public void setDictionarytype(String dictionarytype) {
		this.dictionarytype = dictionarytype;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column t_dictionary.dictionaryremark
	 * @return  the value of t_dictionary.dictionaryremark
	 * @ibatorgenerated  Sun Feb 22 22:16:26 CST 2015
	 */
	public String getDictionaryremark() {
		return dictionaryremark;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column t_dictionary.dictionaryremark
	 * @param dictionaryremark  the value for t_dictionary.dictionaryremark
	 * @ibatorgenerated  Sun Feb 22 22:16:26 CST 2015
	 */
	public void setDictionaryremark(String dictionaryremark) {
		this.dictionaryremark = dictionaryremark;
	}
}