package com.et59.cus.domain.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class TDownloadExample {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database table t_download
	 * @ibatorgenerated  Thu Mar 05 17:12:45 CST 2015
	 */
	protected String orderByClause;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database table t_download
	 * @ibatorgenerated  Thu Mar 05 17:12:45 CST 2015
	 */
	protected List oredCriteria;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_download
	 * @ibatorgenerated  Thu Mar 05 17:12:45 CST 2015
	 */
	public TDownloadExample() {
		oredCriteria = new ArrayList();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_download
	 * @ibatorgenerated  Thu Mar 05 17:12:45 CST 2015
	 */
	protected TDownloadExample(TDownloadExample example) {
		this.orderByClause = example.orderByClause;
		this.oredCriteria = example.oredCriteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_download
	 * @ibatorgenerated  Thu Mar 05 17:12:45 CST 2015
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_download
	 * @ibatorgenerated  Thu Mar 05 17:12:45 CST 2015
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_download
	 * @ibatorgenerated  Thu Mar 05 17:12:45 CST 2015
	 */
	public List getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_download
	 * @ibatorgenerated  Thu Mar 05 17:12:45 CST 2015
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_download
	 * @ibatorgenerated  Thu Mar 05 17:12:45 CST 2015
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_download
	 * @ibatorgenerated  Thu Mar 05 17:12:45 CST 2015
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_download
	 * @ibatorgenerated  Thu Mar 05 17:12:45 CST 2015
	 */
	public void clear() {
		oredCriteria.clear();
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table t_download
	 * @ibatorgenerated  Thu Mar 05 17:12:45 CST 2015
	 */
	public static class Criteria {
		protected List criteriaWithoutValue;
		protected List criteriaWithSingleValue;
		protected List criteriaWithListValue;
		protected List criteriaWithBetweenValue;

		protected Criteria() {
			super();
			criteriaWithoutValue = new ArrayList();
			criteriaWithSingleValue = new ArrayList();
			criteriaWithListValue = new ArrayList();
			criteriaWithBetweenValue = new ArrayList();
		}

		public boolean isValid() {
			return criteriaWithoutValue.size() > 0
					|| criteriaWithSingleValue.size() > 0
					|| criteriaWithListValue.size() > 0
					|| criteriaWithBetweenValue.size() > 0;
		}

		public List getCriteriaWithoutValue() {
			return criteriaWithoutValue;
		}

		public List getCriteriaWithSingleValue() {
			return criteriaWithSingleValue;
		}

		public List getCriteriaWithListValue() {
			return criteriaWithListValue;
		}

		public List getCriteriaWithBetweenValue() {
			return criteriaWithBetweenValue;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteriaWithoutValue.add(condition);
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("value", value);
			criteriaWithSingleValue.add(map);
		}

		protected void addCriterion(String condition, List values,
				String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property
						+ " cannot be null or empty");
			}
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("values", values);
			criteriaWithListValue.add(map);
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			List list = new ArrayList();
			list.add(value1);
			list.add(value2);
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("values", list);
			criteriaWithBetweenValue.add(map);
		}

		public Criteria andDownloadidIsNull() {
			addCriterion("downloadid is null");
			return this;
		}

		public Criteria andDownloadidIsNotNull() {
			addCriterion("downloadid is not null");
			return this;
		}

		public Criteria andDownloadidEqualTo(Long value) {
			addCriterion("downloadid =", value, "downloadid");
			return this;
		}

		public Criteria andDownloadidNotEqualTo(Long value) {
			addCriterion("downloadid <>", value, "downloadid");
			return this;
		}

		public Criteria andDownloadidGreaterThan(Long value) {
			addCriterion("downloadid >", value, "downloadid");
			return this;
		}

		public Criteria andDownloadidGreaterThanOrEqualTo(Long value) {
			addCriterion("downloadid >=", value, "downloadid");
			return this;
		}

		public Criteria andDownloadidLessThan(Long value) {
			addCriterion("downloadid <", value, "downloadid");
			return this;
		}

		public Criteria andDownloadidLessThanOrEqualTo(Long value) {
			addCriterion("downloadid <=", value, "downloadid");
			return this;
		}

		public Criteria andDownloadidIn(List values) {
			addCriterion("downloadid in", values, "downloadid");
			return this;
		}

		public Criteria andDownloadidNotIn(List values) {
			addCriterion("downloadid not in", values, "downloadid");
			return this;
		}

		public Criteria andDownloadidBetween(Long value1, Long value2) {
			addCriterion("downloadid between", value1, value2, "downloadid");
			return this;
		}

		public Criteria andDownloadidNotBetween(Long value1, Long value2) {
			addCriterion("downloadid not between", value1, value2, "downloadid");
			return this;
		}

		public Criteria andFilenameIsNull() {
			addCriterion("filename is null");
			return this;
		}

		public Criteria andFilenameIsNotNull() {
			addCriterion("filename is not null");
			return this;
		}

		public Criteria andFilenameEqualTo(String value) {
			addCriterion("filename =", value, "filename");
			return this;
		}

		public Criteria andFilenameNotEqualTo(String value) {
			addCriterion("filename <>", value, "filename");
			return this;
		}

		public Criteria andFilenameGreaterThan(String value) {
			addCriterion("filename >", value, "filename");
			return this;
		}

		public Criteria andFilenameGreaterThanOrEqualTo(String value) {
			addCriterion("filename >=", value, "filename");
			return this;
		}

		public Criteria andFilenameLessThan(String value) {
			addCriterion("filename <", value, "filename");
			return this;
		}

		public Criteria andFilenameLessThanOrEqualTo(String value) {
			addCriterion("filename <=", value, "filename");
			return this;
		}

		public Criteria andFilenameLike(String value) {
			addCriterion("filename like", value, "filename");
			return this;
		}

		public Criteria andFilenameNotLike(String value) {
			addCriterion("filename not like", value, "filename");
			return this;
		}

		public Criteria andFilenameIn(List values) {
			addCriterion("filename in", values, "filename");
			return this;
		}

		public Criteria andFilenameNotIn(List values) {
			addCriterion("filename not in", values, "filename");
			return this;
		}

		public Criteria andFilenameBetween(String value1, String value2) {
			addCriterion("filename between", value1, value2, "filename");
			return this;
		}

		public Criteria andFilenameNotBetween(String value1, String value2) {
			addCriterion("filename not between", value1, value2, "filename");
			return this;
		}

		public Criteria andFileshowpathIsNull() {
			addCriterion("fileshowpath is null");
			return this;
		}

		public Criteria andFileshowpathIsNotNull() {
			addCriterion("fileshowpath is not null");
			return this;
		}

		public Criteria andFileshowpathEqualTo(String value) {
			addCriterion("fileshowpath =", value, "fileshowpath");
			return this;
		}

		public Criteria andFileshowpathNotEqualTo(String value) {
			addCriterion("fileshowpath <>", value, "fileshowpath");
			return this;
		}

		public Criteria andFileshowpathGreaterThan(String value) {
			addCriterion("fileshowpath >", value, "fileshowpath");
			return this;
		}

		public Criteria andFileshowpathGreaterThanOrEqualTo(String value) {
			addCriterion("fileshowpath >=", value, "fileshowpath");
			return this;
		}

		public Criteria andFileshowpathLessThan(String value) {
			addCriterion("fileshowpath <", value, "fileshowpath");
			return this;
		}

		public Criteria andFileshowpathLessThanOrEqualTo(String value) {
			addCriterion("fileshowpath <=", value, "fileshowpath");
			return this;
		}

		public Criteria andFileshowpathLike(String value) {
			addCriterion("fileshowpath like", value, "fileshowpath");
			return this;
		}

		public Criteria andFileshowpathNotLike(String value) {
			addCriterion("fileshowpath not like", value, "fileshowpath");
			return this;
		}

		public Criteria andFileshowpathIn(List values) {
			addCriterion("fileshowpath in", values, "fileshowpath");
			return this;
		}

		public Criteria andFileshowpathNotIn(List values) {
			addCriterion("fileshowpath not in", values, "fileshowpath");
			return this;
		}

		public Criteria andFileshowpathBetween(String value1, String value2) {
			addCriterion("fileshowpath between", value1, value2, "fileshowpath");
			return this;
		}

		public Criteria andFileshowpathNotBetween(String value1, String value2) {
			addCriterion("fileshowpath not between", value1, value2,
					"fileshowpath");
			return this;
		}

		public Criteria andFilepathIsNull() {
			addCriterion("filepath is null");
			return this;
		}

		public Criteria andFilepathIsNotNull() {
			addCriterion("filepath is not null");
			return this;
		}

		public Criteria andFilepathEqualTo(String value) {
			addCriterion("filepath =", value, "filepath");
			return this;
		}

		public Criteria andFilepathNotEqualTo(String value) {
			addCriterion("filepath <>", value, "filepath");
			return this;
		}

		public Criteria andFilepathGreaterThan(String value) {
			addCriterion("filepath >", value, "filepath");
			return this;
		}

		public Criteria andFilepathGreaterThanOrEqualTo(String value) {
			addCriterion("filepath >=", value, "filepath");
			return this;
		}

		public Criteria andFilepathLessThan(String value) {
			addCriterion("filepath <", value, "filepath");
			return this;
		}

		public Criteria andFilepathLessThanOrEqualTo(String value) {
			addCriterion("filepath <=", value, "filepath");
			return this;
		}

		public Criteria andFilepathLike(String value) {
			addCriterion("filepath like", value, "filepath");
			return this;
		}

		public Criteria andFilepathNotLike(String value) {
			addCriterion("filepath not like", value, "filepath");
			return this;
		}

		public Criteria andFilepathIn(List values) {
			addCriterion("filepath in", values, "filepath");
			return this;
		}

		public Criteria andFilepathNotIn(List values) {
			addCriterion("filepath not in", values, "filepath");
			return this;
		}

		public Criteria andFilepathBetween(String value1, String value2) {
			addCriterion("filepath between", value1, value2, "filepath");
			return this;
		}

		public Criteria andFilepathNotBetween(String value1, String value2) {
			addCriterion("filepath not between", value1, value2, "filepath");
			return this;
		}

		public Criteria andFileisvalidIsNull() {
			addCriterion("fileisvalid is null");
			return this;
		}

		public Criteria andFileisvalidIsNotNull() {
			addCriterion("fileisvalid is not null");
			return this;
		}

		public Criteria andFileisvalidEqualTo(String value) {
			addCriterion("fileisvalid =", value, "fileisvalid");
			return this;
		}

		public Criteria andFileisvalidNotEqualTo(String value) {
			addCriterion("fileisvalid <>", value, "fileisvalid");
			return this;
		}

		public Criteria andFileisvalidGreaterThan(String value) {
			addCriterion("fileisvalid >", value, "fileisvalid");
			return this;
		}

		public Criteria andFileisvalidGreaterThanOrEqualTo(String value) {
			addCriterion("fileisvalid >=", value, "fileisvalid");
			return this;
		}

		public Criteria andFileisvalidLessThan(String value) {
			addCriterion("fileisvalid <", value, "fileisvalid");
			return this;
		}

		public Criteria andFileisvalidLessThanOrEqualTo(String value) {
			addCriterion("fileisvalid <=", value, "fileisvalid");
			return this;
		}

		public Criteria andFileisvalidLike(String value) {
			addCriterion("fileisvalid like", value, "fileisvalid");
			return this;
		}

		public Criteria andFileisvalidNotLike(String value) {
			addCriterion("fileisvalid not like", value, "fileisvalid");
			return this;
		}

		public Criteria andFileisvalidIn(List values) {
			addCriterion("fileisvalid in", values, "fileisvalid");
			return this;
		}

		public Criteria andFileisvalidNotIn(List values) {
			addCriterion("fileisvalid not in", values, "fileisvalid");
			return this;
		}

		public Criteria andFileisvalidBetween(String value1, String value2) {
			addCriterion("fileisvalid between", value1, value2, "fileisvalid");
			return this;
		}

		public Criteria andFileisvalidNotBetween(String value1, String value2) {
			addCriterion("fileisvalid not between", value1, value2,
					"fileisvalid");
			return this;
		}

		public Criteria andCreatedateIsNull() {
			addCriterion("createdate is null");
			return this;
		}

		public Criteria andCreatedateIsNotNull() {
			addCriterion("createdate is not null");
			return this;
		}

		public Criteria andCreatedateEqualTo(String value) {
			addCriterion("createdate =", value, "createdate");
			return this;
		}

		public Criteria andCreatedateNotEqualTo(String value) {
			addCriterion("createdate <>", value, "createdate");
			return this;
		}

		public Criteria andCreatedateGreaterThan(String value) {
			addCriterion("createdate >", value, "createdate");
			return this;
		}

		public Criteria andCreatedateGreaterThanOrEqualTo(String value) {
			addCriterion("createdate >=", value, "createdate");
			return this;
		}

		public Criteria andCreatedateLessThan(String value) {
			addCriterion("createdate <", value, "createdate");
			return this;
		}

		public Criteria andCreatedateLessThanOrEqualTo(String value) {
			addCriterion("createdate <=", value, "createdate");
			return this;
		}

		public Criteria andCreatedateLike(String value) {
			addCriterion("createdate like", value, "createdate");
			return this;
		}

		public Criteria andCreatedateNotLike(String value) {
			addCriterion("createdate not like", value, "createdate");
			return this;
		}

		public Criteria andCreatedateIn(List values) {
			addCriterion("createdate in", values, "createdate");
			return this;
		}

		public Criteria andCreatedateNotIn(List values) {
			addCriterion("createdate not in", values, "createdate");
			return this;
		}

		public Criteria andCreatedateBetween(String value1, String value2) {
			addCriterion("createdate between", value1, value2, "createdate");
			return this;
		}

		public Criteria andCreatedateNotBetween(String value1, String value2) {
			addCriterion("createdate not between", value1, value2, "createdate");
			return this;
		}

		public Criteria andAuthorIsNull() {
			addCriterion("author is null");
			return this;
		}

		public Criteria andAuthorIsNotNull() {
			addCriterion("author is not null");
			return this;
		}

		public Criteria andAuthorEqualTo(String value) {
			addCriterion("author =", value, "author");
			return this;
		}

		public Criteria andAuthorNotEqualTo(String value) {
			addCriterion("author <>", value, "author");
			return this;
		}

		public Criteria andAuthorGreaterThan(String value) {
			addCriterion("author >", value, "author");
			return this;
		}

		public Criteria andAuthorGreaterThanOrEqualTo(String value) {
			addCriterion("author >=", value, "author");
			return this;
		}

		public Criteria andAuthorLessThan(String value) {
			addCriterion("author <", value, "author");
			return this;
		}

		public Criteria andAuthorLessThanOrEqualTo(String value) {
			addCriterion("author <=", value, "author");
			return this;
		}

		public Criteria andAuthorLike(String value) {
			addCriterion("author like", value, "author");
			return this;
		}

		public Criteria andAuthorNotLike(String value) {
			addCriterion("author not like", value, "author");
			return this;
		}

		public Criteria andAuthorIn(List values) {
			addCriterion("author in", values, "author");
			return this;
		}

		public Criteria andAuthorNotIn(List values) {
			addCriterion("author not in", values, "author");
			return this;
		}

		public Criteria andAuthorBetween(String value1, String value2) {
			addCriterion("author between", value1, value2, "author");
			return this;
		}

		public Criteria andAuthorNotBetween(String value1, String value2) {
			addCriterion("author not between", value1, value2, "author");
			return this;
		}

		public Criteria andDirectionsIsNull() {
			addCriterion("directions is null");
			return this;
		}

		public Criteria andDirectionsIsNotNull() {
			addCriterion("directions is not null");
			return this;
		}

		public Criteria andDirectionsEqualTo(String value) {
			addCriterion("directions =", value, "directions");
			return this;
		}

		public Criteria andDirectionsNotEqualTo(String value) {
			addCriterion("directions <>", value, "directions");
			return this;
		}

		public Criteria andDirectionsGreaterThan(String value) {
			addCriterion("directions >", value, "directions");
			return this;
		}

		public Criteria andDirectionsGreaterThanOrEqualTo(String value) {
			addCriterion("directions >=", value, "directions");
			return this;
		}

		public Criteria andDirectionsLessThan(String value) {
			addCriterion("directions <", value, "directions");
			return this;
		}

		public Criteria andDirectionsLessThanOrEqualTo(String value) {
			addCriterion("directions <=", value, "directions");
			return this;
		}

		public Criteria andDirectionsLike(String value) {
			addCriterion("directions like", value, "directions");
			return this;
		}

		public Criteria andDirectionsNotLike(String value) {
			addCriterion("directions not like", value, "directions");
			return this;
		}

		public Criteria andDirectionsIn(List values) {
			addCriterion("directions in", values, "directions");
			return this;
		}

		public Criteria andDirectionsNotIn(List values) {
			addCriterion("directions not in", values, "directions");
			return this;
		}

		public Criteria andDirectionsBetween(String value1, String value2) {
			addCriterion("directions between", value1, value2, "directions");
			return this;
		}

		public Criteria andDirectionsNotBetween(String value1, String value2) {
			addCriterion("directions not between", value1, value2, "directions");
			return this;
		}

		public Criteria andInfotypeIsNull() {
			addCriterion("infotype is null");
			return this;
		}

		public Criteria andInfotypeIsNotNull() {
			addCriterion("infotype is not null");
			return this;
		}

		public Criteria andInfotypeEqualTo(String value) {
			addCriterion("infotype =", value, "infotype");
			return this;
		}

		public Criteria andInfotypeNotEqualTo(String value) {
			addCriterion("infotype <>", value, "infotype");
			return this;
		}

		public Criteria andInfotypeGreaterThan(String value) {
			addCriterion("infotype >", value, "infotype");
			return this;
		}

		public Criteria andInfotypeGreaterThanOrEqualTo(String value) {
			addCriterion("infotype >=", value, "infotype");
			return this;
		}

		public Criteria andInfotypeLessThan(String value) {
			addCriterion("infotype <", value, "infotype");
			return this;
		}

		public Criteria andInfotypeLessThanOrEqualTo(String value) {
			addCriterion("infotype <=", value, "infotype");
			return this;
		}

		public Criteria andInfotypeLike(String value) {
			addCriterion("infotype like", value, "infotype");
			return this;
		}

		public Criteria andInfotypeNotLike(String value) {
			addCriterion("infotype not like", value, "infotype");
			return this;
		}

		public Criteria andInfotypeIn(List values) {
			addCriterion("infotype in", values, "infotype");
			return this;
		}

		public Criteria andInfotypeNotIn(List values) {
			addCriterion("infotype not in", values, "infotype");
			return this;
		}

		public Criteria andInfotypeBetween(String value1, String value2) {
			addCriterion("infotype between", value1, value2, "infotype");
			return this;
		}

		public Criteria andInfotypeNotBetween(String value1, String value2) {
			addCriterion("infotype not between", value1, value2, "infotype");
			return this;
		}

		public Criteria andFiletypeIsNull() {
			addCriterion("fileType is null");
			return this;
		}

		public Criteria andFiletypeIsNotNull() {
			addCriterion("fileType is not null");
			return this;
		}

		public Criteria andFiletypeEqualTo(String value) {
			addCriterion("fileType =", value, "filetype");
			return this;
		}

		public Criteria andFiletypeNotEqualTo(String value) {
			addCriterion("fileType <>", value, "filetype");
			return this;
		}

		public Criteria andFiletypeGreaterThan(String value) {
			addCriterion("fileType >", value, "filetype");
			return this;
		}

		public Criteria andFiletypeGreaterThanOrEqualTo(String value) {
			addCriterion("fileType >=", value, "filetype");
			return this;
		}

		public Criteria andFiletypeLessThan(String value) {
			addCriterion("fileType <", value, "filetype");
			return this;
		}

		public Criteria andFiletypeLessThanOrEqualTo(String value) {
			addCriterion("fileType <=", value, "filetype");
			return this;
		}

		public Criteria andFiletypeLike(String value) {
			addCriterion("fileType like", value, "filetype");
			return this;
		}

		public Criteria andFiletypeNotLike(String value) {
			addCriterion("fileType not like", value, "filetype");
			return this;
		}

		public Criteria andFiletypeIn(List values) {
			addCriterion("fileType in", values, "filetype");
			return this;
		}

		public Criteria andFiletypeNotIn(List values) {
			addCriterion("fileType not in", values, "filetype");
			return this;
		}

		public Criteria andFiletypeBetween(String value1, String value2) {
			addCriterion("fileType between", value1, value2, "filetype");
			return this;
		}

		public Criteria andFiletypeNotBetween(String value1, String value2) {
			addCriterion("fileType not between", value1, value2, "filetype");
			return this;
		}
	}
}