package com.et59.cus.domain.entity;


public class TTeacher {

	// /**
	// * This method was generated by Apache iBATIS ibator. This method returns
	// * the value of the database column t_teacher.department
	// *
	// * @return the value of t_teacher.department
	// * @ibatorgenerated Mon Feb 23 13:41:18 CST 2015
	// */
	// public Integer getDepartment() {
	// return department;
	// }
	//
	// /**
	// * This method was generated by Apache iBATIS ibator. This method sets the
	// * value of the database column t_teacher.department
	// *
	// * @param department
	// * the value for t_teacher.department
	// * @ibatorgenerated Mon Feb 23 13:41:18 CST 2015
	// */
	// public void setDepartment(Integer department) {
	// this.department = department;
	// }

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds
	 * to the database column t_teacher.id
	 * 
	 * @ibatorgenerated Mon Mar 09 15:40:33 CST 2015
	 */
	private Long id;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds
	 * to the database column t_teacher.sex
	 * 
	 * @ibatorgenerated Mon Mar 09 15:40:33 CST 2015
	 */
	private String sex;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds
	 * to the database column t_teacher.teachername
	 * 
	 * @ibatorgenerated Mon Mar 09 15:40:33 CST 2015
	 */
	private String teachername;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds
	 * to the database column t_teacher.title
	 * 
	 * @ibatorgenerated Mon Mar 09 15:40:33 CST 2015
	 */
	private String title;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds
	 * to the database column t_teacher.college
	 * 
	 * @ibatorgenerated Mon Mar 09 15:40:33 CST 2015
	 */
	private String college;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds
	 * to the database column t_teacher.department
	 * 
	 * @ibatorgenerated Mon Mar 09 15:40:33 CST 2015
	 */
	private String department;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds
	 * to the database column t_teacher.collegename
	 * 
	 * @ibatorgenerated Mon Mar 09 15:40:33 CST 2015
	 */
	private String collegename;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds
	 * to the database column t_teacher.departmentname
	 * 
	 * @ibatorgenerated Mon Mar 09 15:40:33 CST 2015
	 */
	private String departmentname;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds
	 * to the database column t_teacher.phone
	 * 
	 * @ibatorgenerated Mon Mar 09 15:40:33 CST 2015
	 */
	private String phone;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds
	 * to the database column t_teacher.picpath
	 * 
	 * @ibatorgenerated Mon Mar 09 15:40:33 CST 2015
	 */
	private String picpath;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds
	 * to the database column t_teacher.content
	 * 
	 * @ibatorgenerated Mon Mar 09 15:40:33 CST 2015
	 */
	private String content;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds
	 * to the database column t_teacher.isshow
	 * 
	 * @ibatorgenerated Mon Mar 09 15:40:33 CST 2015
	 */
	private String isshow;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds
	 * to the database column t_teacher.birthday
	 * 
	 * @ibatorgenerated Mon Mar 09 15:40:33 CST 2015
	 */
	private String birthday;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds
	 * to the database column t_teacher.job
	 * 
	 * @ibatorgenerated Mon Mar 09 15:40:33 CST 2015
	 */
	private String job;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds
	 * to the database column t_teacher.tutorType
	 * 
	 * @ibatorgenerated Mon Mar 09 15:40:33 CST 2015
	 */
	private int tutortype;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds
	 * to the database column t_teacher.introduction
	 * 
	 * @ibatorgenerated Mon Mar 09 15:40:33 CST 2015
	 */
	private String introduction;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds
	 * to the database column t_teacher.iimageURLl
	 * 
	 * @ibatorgenerated Mon Mar 09 15:40:33 CST 2015
	 */
	private String iimageurll;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds
	 * to the database column t_teacher.titlename
	 * 
	 * @ibatorgenerated Mon Mar 09 15:40:33 CST 2015
	 */
	private String titlename;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds
	 * to the database column t_teacher.jobname
	 * 
	 * @ibatorgenerated Mon Mar 09 15:40:33 CST 2015
	 */
	private String jobname;

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column t_teacher.id
	 * 
	 * @return the value of t_teacher.id
	 * @ibatorgenerated Mon Mar 09 15:40:33 CST 2015
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column t_teacher.id
	 * 
	 * @param id
	 *            the value for t_teacher.id
	 * @ibatorgenerated Mon Mar 09 15:40:33 CST 2015
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column t_teacher.sex
	 * 
	 * @return the value of t_teacher.sex
	 * @ibatorgenerated Mon Mar 09 15:40:33 CST 2015
	 */
	public String getSex() {
		return sex;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column t_teacher.sex
	 * 
	 * @param sex
	 *            the value for t_teacher.sex
	 * @ibatorgenerated Mon Mar 09 15:40:33 CST 2015
	 */
	public void setSex(String sex) {
		this.sex = sex;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column t_teacher.teachername
	 * 
	 * @return the value of t_teacher.teachername
	 * @ibatorgenerated Mon Mar 09 15:40:33 CST 2015
	 */
	public String getTeachername() {
		return teachername;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column t_teacher.teachername
	 * 
	 * @param teachername
	 *            the value for t_teacher.teachername
	 * @ibatorgenerated Mon Mar 09 15:40:33 CST 2015
	 */
	public void setTeachername(String teachername) {
		this.teachername = teachername;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column t_teacher.title
	 * 
	 * @return the value of t_teacher.title
	 * @ibatorgenerated Mon Mar 09 15:40:33 CST 2015
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column t_teacher.title
	 * 
	 * @param title
	 *            the value for t_teacher.title
	 * @ibatorgenerated Mon Mar 09 15:40:33 CST 2015
	 */
	public void setTitle(String title) {
		this.title = title;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column t_teacher.college
	 * 
	 * @return the value of t_teacher.college
	 * @ibatorgenerated Mon Mar 09 15:40:33 CST 2015
	 */
	public String getCollege() {
		return college;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column t_teacher.college
	 * 
	 * @param college
	 *            the value for t_teacher.college
	 * @ibatorgenerated Mon Mar 09 15:40:33 CST 2015
	 */
	public void setCollege(String college) {
		this.college = college;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column t_teacher.department
	 * 
	 * @return the value of t_teacher.department
	 * @ibatorgenerated Mon Mar 09 15:40:33 CST 2015
	 */
	public String getDepartment() {
		return department;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column t_teacher.department
	 * 
	 * @param department
	 *            the value for t_teacher.department
	 * @ibatorgenerated Mon Mar 09 15:40:33 CST 2015
	 */
	public void setDepartment(String department) {
		this.department = department;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column t_teacher.collegename
	 * 
	 * @return the value of t_teacher.collegename
	 * @ibatorgenerated Mon Mar 09 15:40:33 CST 2015
	 */
	public String getCollegename() {
		return collegename;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column t_teacher.collegename
	 * 
	 * @param collegename
	 *            the value for t_teacher.collegename
	 * @ibatorgenerated Mon Mar 09 15:40:33 CST 2015
	 */
	public void setCollegename(String collegename) {
		this.collegename = collegename;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column t_teacher.departmentname
	 * 
	 * @return the value of t_teacher.departmentname
	 * @ibatorgenerated Mon Mar 09 15:40:33 CST 2015
	 */
	public String getDepartmentname() {
		return departmentname;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column t_teacher.departmentname
	 * 
	 * @param departmentname
	 *            the value for t_teacher.departmentname
	 * @ibatorgenerated Mon Mar 09 15:40:33 CST 2015
	 */
	public void setDepartmentname(String departmentname) {
		this.departmentname = departmentname;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column t_teacher.phone
	 * 
	 * @return the value of t_teacher.phone
	 * @ibatorgenerated Mon Mar 09 15:40:33 CST 2015
	 */
	public String getPhone() {
		return phone;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column t_teacher.phone
	 * 
	 * @param phone
	 *            the value for t_teacher.phone
	 * @ibatorgenerated Mon Mar 09 15:40:33 CST 2015
	 */
	public void setPhone(String phone) {
		this.phone = phone;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column t_teacher.picpath
	 * 
	 * @return the value of t_teacher.picpath
	 * @ibatorgenerated Mon Mar 09 15:40:33 CST 2015
	 */
	public String getPicpath() {
		return picpath;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column t_teacher.picpath
	 * 
	 * @param picpath
	 *            the value for t_teacher.picpath
	 * @ibatorgenerated Mon Mar 09 15:40:33 CST 2015
	 */
	public void setPicpath(String picpath) {
		this.picpath = picpath;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column t_teacher.content
	 * 
	 * @return the value of t_teacher.content
	 * @ibatorgenerated Mon Mar 09 15:40:33 CST 2015
	 */
	public String getContent() {
		return content;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column t_teacher.content
	 * 
	 * @param content
	 *            the value for t_teacher.content
	 * @ibatorgenerated Mon Mar 09 15:40:33 CST 2015
	 */
	public void setContent(String content) {
		this.content = content;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column t_teacher.isshow
	 * 
	 * @return the value of t_teacher.isshow
	 * @ibatorgenerated Mon Mar 09 15:40:33 CST 2015
	 */
	public String getIsshow() {
		return isshow;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column t_teacher.isshow
	 * 
	 * @param isshow
	 *            the value for t_teacher.isshow
	 * @ibatorgenerated Mon Mar 09 15:40:33 CST 2015
	 */
	public void setIsshow(String isshow) {
		this.isshow = isshow;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column t_teacher.birthday
	 * 
	 * @return the value of t_teacher.birthday
	 * @ibatorgenerated Mon Mar 09 15:40:33 CST 2015
	 */
	public String getBirthday() {
		return birthday;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column t_teacher.birthday
	 * 
	 * @param birthday
	 *            the value for t_teacher.birthday
	 * @ibatorgenerated Mon Mar 09 15:40:33 CST 2015
	 */
	public void setBirthday(String birthday) {
		this.birthday = birthday;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column t_teacher.job
	 * 
	 * @return the value of t_teacher.job
	 * @ibatorgenerated Mon Mar 09 15:40:33 CST 2015
	 */
	public String getJob() {
		return job;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column t_teacher.job
	 * 
	 * @param job
	 *            the value for t_teacher.job
	 * @ibatorgenerated Mon Mar 09 15:40:33 CST 2015
	 */
	public void setJob(String job) {
		this.job = job;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column t_teacher.introduction
	 * 
	 * @return the value of t_teacher.introduction
	 * @ibatorgenerated Mon Mar 09 15:40:33 CST 2015
	 */
	public String getIntroduction() {
		return introduction;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column t_teacher.introduction
	 * 
	 * @param introduction
	 *            the value for t_teacher.introduction
	 * @ibatorgenerated Mon Mar 09 15:40:33 CST 2015
	 */
	public void setIntroduction(String introduction) {
		this.introduction = introduction;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column t_teacher.iimageURLl
	 * 
	 * @return the value of t_teacher.iimageURLl
	 * @ibatorgenerated Mon Mar 09 15:40:33 CST 2015
	 */
	public String getIimageurll() {
		return iimageurll;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column t_teacher.iimageURLl
	 * 
	 * @param iimageurll
	 *            the value for t_teacher.iimageURLl
	 * @ibatorgenerated Mon Mar 09 15:40:33 CST 2015
	 */
	public void setIimageurll(String iimageurll) {
		this.iimageurll = iimageurll;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column t_teacher.titlename
	 * 
	 * @return the value of t_teacher.titlename
	 * @ibatorgenerated Mon Mar 09 15:40:33 CST 2015
	 */
	public String getTitlename() {
		return titlename;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column t_teacher.titlename
	 * 
	 * @param titlename
	 *            the value for t_teacher.titlename
	 * @ibatorgenerated Mon Mar 09 15:40:33 CST 2015
	 */
	public void setTitlename(String titlename) {
		this.titlename = titlename;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns
	 * the value of the database column t_teacher.jobname
	 * 
	 * @return the value of t_teacher.jobname
	 * @ibatorgenerated Mon Mar 09 15:40:33 CST 2015
	 */
	public String getJobname() {
		return jobname;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the
	 * value of the database column t_teacher.jobname
	 * 
	 * @param jobname
	 *            the value for t_teacher.jobname
	 * @ibatorgenerated Mon Mar 09 15:40:33 CST 2015
	 */
	public void setJobname(String jobname) {
		this.jobname = jobname;
	}

	public int getTutortype() {
		return tutortype;
	}

	public void setTutortype(int tutortype) {
		this.tutortype = tutortype;
	}

}