package com.et59.cus.domain.entity;

public class TTeacherPrizeKey {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_teacher_prize.prizeId
     *
     * @ibatorgenerated Tue Mar 03 17:43:02 CST 2015
     */
    private Long prizeid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_teacher_prize.teacherId
     *
     * @ibatorgenerated Tue Mar 03 17:43:02 CST 2015
     */
    private Long teacherid;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_teacher_prize.prizeId
     *
     * @return the value of t_teacher_prize.prizeId
     *
     * @ibatorgenerated Tue Mar 03 17:43:02 CST 2015
     */
    public Long getPrizeid() {
        return prizeid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_teacher_prize.prizeId
     *
     * @param prizeid the value for t_teacher_prize.prizeId
     *
     * @ibatorgenerated Tue Mar 03 17:43:02 CST 2015
     */
    public void setPrizeid(Long prizeid) {
        this.prizeid = prizeid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_teacher_prize.teacherId
     *
     * @return the value of t_teacher_prize.teacherId
     *
     * @ibatorgenerated Tue Mar 03 17:43:02 CST 2015
     */
    public Long getTeacherid() {
        return teacherid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_teacher_prize.teacherId
     *
     * @param teacherid the value for t_teacher_prize.teacherId
     *
     * @ibatorgenerated Tue Mar 03 17:43:02 CST 2015
     */
    public void setTeacherid(Long teacherid) {
        this.teacherid = teacherid;
    }
}