package com.et59.cus.domain.entity;

public class TTeacherSubjectKey {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_teacher_subject.subjectId
     *
     * @ibatorgenerated Tue Mar 03 17:43:02 CST 2015
     */
    private Long subjectid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column t_teacher_subject.teacherId
     *
     * @ibatorgenerated Tue Mar 03 17:43:02 CST 2015
     */
    private Long teacherid;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_teacher_subject.subjectId
     *
     * @return the value of t_teacher_subject.subjectId
     *
     * @ibatorgenerated Tue Mar 03 17:43:02 CST 2015
     */
    public Long getSubjectid() {
        return subjectid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_teacher_subject.subjectId
     *
     * @param subjectid the value for t_teacher_subject.subjectId
     *
     * @ibatorgenerated Tue Mar 03 17:43:02 CST 2015
     */
    public void setSubjectid(Long subjectid) {
        this.subjectid = subjectid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column t_teacher_subject.teacherId
     *
     * @return the value of t_teacher_subject.teacherId
     *
     * @ibatorgenerated Tue Mar 03 17:43:02 CST 2015
     */
    public Long getTeacherid() {
        return teacherid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column t_teacher_subject.teacherId
     *
     * @param teacherid the value for t_teacher_subject.teacherId
     *
     * @ibatorgenerated Tue Mar 03 17:43:02 CST 2015
     */
    public void setTeacherid(Long teacherid) {
        this.teacherid = teacherid;
    }
}