package com.et59.cus.domain.entity;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class TTrainingplanExample {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database table t_trainingplan
	 * @ibatorgenerated  Thu Mar 26 17:53:45 CST 2015
	 */
	protected String orderByClause;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database table t_trainingplan
	 * @ibatorgenerated  Thu Mar 26 17:53:45 CST 2015
	 */
	protected List oredCriteria;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_trainingplan
	 * @ibatorgenerated  Thu Mar 26 17:53:45 CST 2015
	 */
	public TTrainingplanExample() {
		oredCriteria = new ArrayList();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_trainingplan
	 * @ibatorgenerated  Thu Mar 26 17:53:45 CST 2015
	 */
	protected TTrainingplanExample(TTrainingplanExample example) {
		this.orderByClause = example.orderByClause;
		this.oredCriteria = example.oredCriteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_trainingplan
	 * @ibatorgenerated  Thu Mar 26 17:53:45 CST 2015
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_trainingplan
	 * @ibatorgenerated  Thu Mar 26 17:53:45 CST 2015
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_trainingplan
	 * @ibatorgenerated  Thu Mar 26 17:53:45 CST 2015
	 */
	public List getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_trainingplan
	 * @ibatorgenerated  Thu Mar 26 17:53:45 CST 2015
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_trainingplan
	 * @ibatorgenerated  Thu Mar 26 17:53:45 CST 2015
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_trainingplan
	 * @ibatorgenerated  Thu Mar 26 17:53:45 CST 2015
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_trainingplan
	 * @ibatorgenerated  Thu Mar 26 17:53:45 CST 2015
	 */
	public void clear() {
		oredCriteria.clear();
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table t_trainingplan
	 * @ibatorgenerated  Thu Mar 26 17:53:45 CST 2015
	 */
	public static class Criteria {
		protected List criteriaWithoutValue;
		protected List criteriaWithSingleValue;
		protected List criteriaWithListValue;
		protected List criteriaWithBetweenValue;

		protected Criteria() {
			super();
			criteriaWithoutValue = new ArrayList();
			criteriaWithSingleValue = new ArrayList();
			criteriaWithListValue = new ArrayList();
			criteriaWithBetweenValue = new ArrayList();
		}

		public boolean isValid() {
			return criteriaWithoutValue.size() > 0
					|| criteriaWithSingleValue.size() > 0
					|| criteriaWithListValue.size() > 0
					|| criteriaWithBetweenValue.size() > 0;
		}

		public List getCriteriaWithoutValue() {
			return criteriaWithoutValue;
		}

		public List getCriteriaWithSingleValue() {
			return criteriaWithSingleValue;
		}

		public List getCriteriaWithListValue() {
			return criteriaWithListValue;
		}

		public List getCriteriaWithBetweenValue() {
			return criteriaWithBetweenValue;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteriaWithoutValue.add(condition);
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("value", value);
			criteriaWithSingleValue.add(map);
		}

		protected void addCriterion(String condition, List values,
				String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property
						+ " cannot be null or empty");
			}
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("values", values);
			criteriaWithListValue.add(map);
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			List list = new ArrayList();
			list.add(value1);
			list.add(value2);
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("values", list);
			criteriaWithBetweenValue.add(map);
		}

		public Criteria andTrainingplanidIsNull() {
			addCriterion("trainingPlanId is null");
			return this;
		}

		public Criteria andTrainingplanidIsNotNull() {
			addCriterion("trainingPlanId is not null");
			return this;
		}

		public Criteria andTrainingplanidEqualTo(Long value) {
			addCriterion("trainingPlanId =", value, "trainingplanid");
			return this;
		}

		public Criteria andTrainingplanidNotEqualTo(Long value) {
			addCriterion("trainingPlanId <>", value, "trainingplanid");
			return this;
		}

		public Criteria andTrainingplanidGreaterThan(Long value) {
			addCriterion("trainingPlanId >", value, "trainingplanid");
			return this;
		}

		public Criteria andTrainingplanidGreaterThanOrEqualTo(Long value) {
			addCriterion("trainingPlanId >=", value, "trainingplanid");
			return this;
		}

		public Criteria andTrainingplanidLessThan(Long value) {
			addCriterion("trainingPlanId <", value, "trainingplanid");
			return this;
		}

		public Criteria andTrainingplanidLessThanOrEqualTo(Long value) {
			addCriterion("trainingPlanId <=", value, "trainingplanid");
			return this;
		}

		public Criteria andTrainingplanidIn(List values) {
			addCriterion("trainingPlanId in", values, "trainingplanid");
			return this;
		}

		public Criteria andTrainingplanidNotIn(List values) {
			addCriterion("trainingPlanId not in", values, "trainingplanid");
			return this;
		}

		public Criteria andTrainingplanidBetween(Long value1, Long value2) {
			addCriterion("trainingPlanId between", value1, value2,
					"trainingplanid");
			return this;
		}

		public Criteria andTrainingplanidNotBetween(Long value1, Long value2) {
			addCriterion("trainingPlanId not between", value1, value2,
					"trainingplanid");
			return this;
		}

		public Criteria andTrainingplandepidIsNull() {
			addCriterion("trainingPlanDepId is null");
			return this;
		}

		public Criteria andTrainingplandepidIsNotNull() {
			addCriterion("trainingPlanDepId is not null");
			return this;
		}

		public Criteria andTrainingplandepidEqualTo(Long value) {
			addCriterion("trainingPlanDepId =", value, "trainingplandepid");
			return this;
		}

		public Criteria andTrainingplandepidNotEqualTo(Long value) {
			addCriterion("trainingPlanDepId <>", value, "trainingplandepid");
			return this;
		}

		public Criteria andTrainingplandepidGreaterThan(Long value) {
			addCriterion("trainingPlanDepId >", value, "trainingplandepid");
			return this;
		}

		public Criteria andTrainingplandepidGreaterThanOrEqualTo(Long value) {
			addCriterion("trainingPlanDepId >=", value, "trainingplandepid");
			return this;
		}

		public Criteria andTrainingplandepidLessThan(Long value) {
			addCriterion("trainingPlanDepId <", value, "trainingplandepid");
			return this;
		}

		public Criteria andTrainingplandepidLessThanOrEqualTo(Long value) {
			addCriterion("trainingPlanDepId <=", value, "trainingplandepid");
			return this;
		}

		public Criteria andTrainingplandepidIn(List values) {
			addCriterion("trainingPlanDepId in", values, "trainingplandepid");
			return this;
		}

		public Criteria andTrainingplandepidNotIn(List values) {
			addCriterion("trainingPlanDepId not in", values,
					"trainingplandepid");
			return this;
		}

		public Criteria andTrainingplandepidBetween(Long value1, Long value2) {
			addCriterion("trainingPlanDepId between", value1, value2,
					"trainingplandepid");
			return this;
		}

		public Criteria andTrainingplandepidNotBetween(Long value1, Long value2) {
			addCriterion("trainingPlanDepId not between", value1, value2,
					"trainingplandepid");
			return this;
		}

		public Criteria andTrainingplantypeIsNull() {
			addCriterion("trainingPlanType is null");
			return this;
		}

		public Criteria andTrainingplantypeIsNotNull() {
			addCriterion("trainingPlanType is not null");
			return this;
		}

		public Criteria andTrainingplantypeEqualTo(String value) {
			addCriterion("trainingPlanType =", value, "trainingplantype");
			return this;
		}

		public Criteria andTrainingplantypeNotEqualTo(String value) {
			addCriterion("trainingPlanType <>", value, "trainingplantype");
			return this;
		}

		public Criteria andTrainingplantypeGreaterThan(String value) {
			addCriterion("trainingPlanType >", value, "trainingplantype");
			return this;
		}

		public Criteria andTrainingplantypeGreaterThanOrEqualTo(String value) {
			addCriterion("trainingPlanType >=", value, "trainingplantype");
			return this;
		}

		public Criteria andTrainingplantypeLessThan(String value) {
			addCriterion("trainingPlanType <", value, "trainingplantype");
			return this;
		}

		public Criteria andTrainingplantypeLessThanOrEqualTo(String value) {
			addCriterion("trainingPlanType <=", value, "trainingplantype");
			return this;
		}

		public Criteria andTrainingplantypeLike(String value) {
			addCriterion("trainingPlanType like", value, "trainingplantype");
			return this;
		}

		public Criteria andTrainingplantypeNotLike(String value) {
			addCriterion("trainingPlanType not like", value, "trainingplantype");
			return this;
		}

		public Criteria andTrainingplantypeIn(List values) {
			addCriterion("trainingPlanType in", values, "trainingplantype");
			return this;
		}

		public Criteria andTrainingplantypeNotIn(List values) {
			addCriterion("trainingPlanType not in", values, "trainingplantype");
			return this;
		}

		public Criteria andTrainingplantypeBetween(String value1, String value2) {
			addCriterion("trainingPlanType between", value1, value2,
					"trainingplantype");
			return this;
		}

		public Criteria andTrainingplantypeNotBetween(String value1,
				String value2) {
			addCriterion("trainingPlanType not between", value1, value2,
					"trainingplantype");
			return this;
		}

		public Criteria andTrplansubidsforoneIsNull() {
			addCriterion("trPlanSubIdsForOne is null");
			return this;
		}

		public Criteria andTrplansubidsforoneIsNotNull() {
			addCriterion("trPlanSubIdsForOne is not null");
			return this;
		}

		public Criteria andTrplansubidsforoneEqualTo(String value) {
			addCriterion("trPlanSubIdsForOne =", value, "trplansubidsforone");
			return this;
		}

		public Criteria andTrplansubidsforoneNotEqualTo(String value) {
			addCriterion("trPlanSubIdsForOne <>", value, "trplansubidsforone");
			return this;
		}

		public Criteria andTrplansubidsforoneGreaterThan(String value) {
			addCriterion("trPlanSubIdsForOne >", value, "trplansubidsforone");
			return this;
		}

		public Criteria andTrplansubidsforoneGreaterThanOrEqualTo(String value) {
			addCriterion("trPlanSubIdsForOne >=", value, "trplansubidsforone");
			return this;
		}

		public Criteria andTrplansubidsforoneLessThan(String value) {
			addCriterion("trPlanSubIdsForOne <", value, "trplansubidsforone");
			return this;
		}

		public Criteria andTrplansubidsforoneLessThanOrEqualTo(String value) {
			addCriterion("trPlanSubIdsForOne <=", value, "trplansubidsforone");
			return this;
		}

		public Criteria andTrplansubidsforoneLike(String value) {
			addCriterion("trPlanSubIdsForOne like", value, "trplansubidsforone");
			return this;
		}

		public Criteria andTrplansubidsforoneNotLike(String value) {
			addCriterion("trPlanSubIdsForOne not like", value,
					"trplansubidsforone");
			return this;
		}

		public Criteria andTrplansubidsforoneIn(List values) {
			addCriterion("trPlanSubIdsForOne in", values, "trplansubidsforone");
			return this;
		}

		public Criteria andTrplansubidsforoneNotIn(List values) {
			addCriterion("trPlanSubIdsForOne not in", values,
					"trplansubidsforone");
			return this;
		}

		public Criteria andTrplansubidsforoneBetween(String value1,
				String value2) {
			addCriterion("trPlanSubIdsForOne between", value1, value2,
					"trplansubidsforone");
			return this;
		}

		public Criteria andTrplansubidsforoneNotBetween(String value1,
				String value2) {
			addCriterion("trPlanSubIdsForOne not between", value1, value2,
					"trplansubidsforone");
			return this;
		}

		public Criteria andTrplansubidsfortwoIsNull() {
			addCriterion("trPlanSubIdsForTwo is null");
			return this;
		}

		public Criteria andTrplansubidsfortwoIsNotNull() {
			addCriterion("trPlanSubIdsForTwo is not null");
			return this;
		}

		public Criteria andTrplansubidsfortwoEqualTo(String value) {
			addCriterion("trPlanSubIdsForTwo =", value, "trplansubidsfortwo");
			return this;
		}

		public Criteria andTrplansubidsfortwoNotEqualTo(String value) {
			addCriterion("trPlanSubIdsForTwo <>", value, "trplansubidsfortwo");
			return this;
		}

		public Criteria andTrplansubidsfortwoGreaterThan(String value) {
			addCriterion("trPlanSubIdsForTwo >", value, "trplansubidsfortwo");
			return this;
		}

		public Criteria andTrplansubidsfortwoGreaterThanOrEqualTo(String value) {
			addCriterion("trPlanSubIdsForTwo >=", value, "trplansubidsfortwo");
			return this;
		}

		public Criteria andTrplansubidsfortwoLessThan(String value) {
			addCriterion("trPlanSubIdsForTwo <", value, "trplansubidsfortwo");
			return this;
		}

		public Criteria andTrplansubidsfortwoLessThanOrEqualTo(String value) {
			addCriterion("trPlanSubIdsForTwo <=", value, "trplansubidsfortwo");
			return this;
		}

		public Criteria andTrplansubidsfortwoLike(String value) {
			addCriterion("trPlanSubIdsForTwo like", value, "trplansubidsfortwo");
			return this;
		}

		public Criteria andTrplansubidsfortwoNotLike(String value) {
			addCriterion("trPlanSubIdsForTwo not like", value,
					"trplansubidsfortwo");
			return this;
		}

		public Criteria andTrplansubidsfortwoIn(List values) {
			addCriterion("trPlanSubIdsForTwo in", values, "trplansubidsfortwo");
			return this;
		}

		public Criteria andTrplansubidsfortwoNotIn(List values) {
			addCriterion("trPlanSubIdsForTwo not in", values,
					"trplansubidsfortwo");
			return this;
		}

		public Criteria andTrplansubidsfortwoBetween(String value1,
				String value2) {
			addCriterion("trPlanSubIdsForTwo between", value1, value2,
					"trplansubidsfortwo");
			return this;
		}

		public Criteria andTrplansubidsfortwoNotBetween(String value1,
				String value2) {
			addCriterion("trPlanSubIdsForTwo not between", value1, value2,
					"trplansubidsfortwo");
			return this;
		}

		public Criteria andTrplansubidsforthreeIsNull() {
			addCriterion("trPlanSubIdsForThree is null");
			return this;
		}

		public Criteria andTrplansubidsforthreeIsNotNull() {
			addCriterion("trPlanSubIdsForThree is not null");
			return this;
		}

		public Criteria andTrplansubidsforthreeEqualTo(String value) {
			addCriterion("trPlanSubIdsForThree =", value,
					"trplansubidsforthree");
			return this;
		}

		public Criteria andTrplansubidsforthreeNotEqualTo(String value) {
			addCriterion("trPlanSubIdsForThree <>", value,
					"trplansubidsforthree");
			return this;
		}

		public Criteria andTrplansubidsforthreeGreaterThan(String value) {
			addCriterion("trPlanSubIdsForThree >", value,
					"trplansubidsforthree");
			return this;
		}

		public Criteria andTrplansubidsforthreeGreaterThanOrEqualTo(String value) {
			addCriterion("trPlanSubIdsForThree >=", value,
					"trplansubidsforthree");
			return this;
		}

		public Criteria andTrplansubidsforthreeLessThan(String value) {
			addCriterion("trPlanSubIdsForThree <", value,
					"trplansubidsforthree");
			return this;
		}

		public Criteria andTrplansubidsforthreeLessThanOrEqualTo(String value) {
			addCriterion("trPlanSubIdsForThree <=", value,
					"trplansubidsforthree");
			return this;
		}

		public Criteria andTrplansubidsforthreeLike(String value) {
			addCriterion("trPlanSubIdsForThree like", value,
					"trplansubidsforthree");
			return this;
		}

		public Criteria andTrplansubidsforthreeNotLike(String value) {
			addCriterion("trPlanSubIdsForThree not like", value,
					"trplansubidsforthree");
			return this;
		}

		public Criteria andTrplansubidsforthreeIn(List values) {
			addCriterion("trPlanSubIdsForThree in", values,
					"trplansubidsforthree");
			return this;
		}

		public Criteria andTrplansubidsforthreeNotIn(List values) {
			addCriterion("trPlanSubIdsForThree not in", values,
					"trplansubidsforthree");
			return this;
		}

		public Criteria andTrplansubidsforthreeBetween(String value1,
				String value2) {
			addCriterion("trPlanSubIdsForThree between", value1, value2,
					"trplansubidsforthree");
			return this;
		}

		public Criteria andTrplansubidsforthreeNotBetween(String value1,
				String value2) {
			addCriterion("trPlanSubIdsForThree not between", value1, value2,
					"trplansubidsforthree");
			return this;
		}

		public Criteria andTrplansubidsforfourIsNull() {
			addCriterion("trPlanSubIdsForFour is null");
			return this;
		}

		public Criteria andTrplansubidsforfourIsNotNull() {
			addCriterion("trPlanSubIdsForFour is not null");
			return this;
		}

		public Criteria andTrplansubidsforfourEqualTo(String value) {
			addCriterion("trPlanSubIdsForFour =", value, "trplansubidsforfour");
			return this;
		}

		public Criteria andTrplansubidsforfourNotEqualTo(String value) {
			addCriterion("trPlanSubIdsForFour <>", value, "trplansubidsforfour");
			return this;
		}

		public Criteria andTrplansubidsforfourGreaterThan(String value) {
			addCriterion("trPlanSubIdsForFour >", value, "trplansubidsforfour");
			return this;
		}

		public Criteria andTrplansubidsforfourGreaterThanOrEqualTo(String value) {
			addCriterion("trPlanSubIdsForFour >=", value, "trplansubidsforfour");
			return this;
		}

		public Criteria andTrplansubidsforfourLessThan(String value) {
			addCriterion("trPlanSubIdsForFour <", value, "trplansubidsforfour");
			return this;
		}

		public Criteria andTrplansubidsforfourLessThanOrEqualTo(String value) {
			addCriterion("trPlanSubIdsForFour <=", value, "trplansubidsforfour");
			return this;
		}

		public Criteria andTrplansubidsforfourLike(String value) {
			addCriterion("trPlanSubIdsForFour like", value,
					"trplansubidsforfour");
			return this;
		}

		public Criteria andTrplansubidsforfourNotLike(String value) {
			addCriterion("trPlanSubIdsForFour not like", value,
					"trplansubidsforfour");
			return this;
		}

		public Criteria andTrplansubidsforfourIn(List values) {
			addCriterion("trPlanSubIdsForFour in", values,
					"trplansubidsforfour");
			return this;
		}

		public Criteria andTrplansubidsforfourNotIn(List values) {
			addCriterion("trPlanSubIdsForFour not in", values,
					"trplansubidsforfour");
			return this;
		}

		public Criteria andTrplansubidsforfourBetween(String value1,
				String value2) {
			addCriterion("trPlanSubIdsForFour between", value1, value2,
					"trplansubidsforfour");
			return this;
		}

		public Criteria andTrplansubidsforfourNotBetween(String value1,
				String value2) {
			addCriterion("trPlanSubIdsForFour not between", value1, value2,
					"trplansubidsforfour");
			return this;
		}

		public Criteria andTrplansubidsforfiveIsNull() {
			addCriterion("trPlanSubIdsForFive is null");
			return this;
		}

		public Criteria andTrplansubidsforfiveIsNotNull() {
			addCriterion("trPlanSubIdsForFive is not null");
			return this;
		}

		public Criteria andTrplansubidsforfiveEqualTo(String value) {
			addCriterion("trPlanSubIdsForFive =", value, "trplansubidsforfive");
			return this;
		}

		public Criteria andTrplansubidsforfiveNotEqualTo(String value) {
			addCriterion("trPlanSubIdsForFive <>", value, "trplansubidsforfive");
			return this;
		}

		public Criteria andTrplansubidsforfiveGreaterThan(String value) {
			addCriterion("trPlanSubIdsForFive >", value, "trplansubidsforfive");
			return this;
		}

		public Criteria andTrplansubidsforfiveGreaterThanOrEqualTo(String value) {
			addCriterion("trPlanSubIdsForFive >=", value, "trplansubidsforfive");
			return this;
		}

		public Criteria andTrplansubidsforfiveLessThan(String value) {
			addCriterion("trPlanSubIdsForFive <", value, "trplansubidsforfive");
			return this;
		}

		public Criteria andTrplansubidsforfiveLessThanOrEqualTo(String value) {
			addCriterion("trPlanSubIdsForFive <=", value, "trplansubidsforfive");
			return this;
		}

		public Criteria andTrplansubidsforfiveLike(String value) {
			addCriterion("trPlanSubIdsForFive like", value,
					"trplansubidsforfive");
			return this;
		}

		public Criteria andTrplansubidsforfiveNotLike(String value) {
			addCriterion("trPlanSubIdsForFive not like", value,
					"trplansubidsforfive");
			return this;
		}

		public Criteria andTrplansubidsforfiveIn(List values) {
			addCriterion("trPlanSubIdsForFive in", values,
					"trplansubidsforfive");
			return this;
		}

		public Criteria andTrplansubidsforfiveNotIn(List values) {
			addCriterion("trPlanSubIdsForFive not in", values,
					"trplansubidsforfive");
			return this;
		}

		public Criteria andTrplansubidsforfiveBetween(String value1,
				String value2) {
			addCriterion("trPlanSubIdsForFive between", value1, value2,
					"trplansubidsforfive");
			return this;
		}

		public Criteria andTrplansubidsforfiveNotBetween(String value1,
				String value2) {
			addCriterion("trPlanSubIdsForFive not between", value1, value2,
					"trplansubidsforfive");
			return this;
		}

		public Criteria andTrplansubidsfosixIsNull() {
			addCriterion("trPlanSubIdsFoSix is null");
			return this;
		}

		public Criteria andTrplansubidsfosixIsNotNull() {
			addCriterion("trPlanSubIdsFoSix is not null");
			return this;
		}

		public Criteria andTrplansubidsfosixEqualTo(String value) {
			addCriterion("trPlanSubIdsFoSix =", value, "trplansubidsfosix");
			return this;
		}

		public Criteria andTrplansubidsfosixNotEqualTo(String value) {
			addCriterion("trPlanSubIdsFoSix <>", value, "trplansubidsfosix");
			return this;
		}

		public Criteria andTrplansubidsfosixGreaterThan(String value) {
			addCriterion("trPlanSubIdsFoSix >", value, "trplansubidsfosix");
			return this;
		}

		public Criteria andTrplansubidsfosixGreaterThanOrEqualTo(String value) {
			addCriterion("trPlanSubIdsFoSix >=", value, "trplansubidsfosix");
			return this;
		}

		public Criteria andTrplansubidsfosixLessThan(String value) {
			addCriterion("trPlanSubIdsFoSix <", value, "trplansubidsfosix");
			return this;
		}

		public Criteria andTrplansubidsfosixLessThanOrEqualTo(String value) {
			addCriterion("trPlanSubIdsFoSix <=", value, "trplansubidsfosix");
			return this;
		}

		public Criteria andTrplansubidsfosixLike(String value) {
			addCriterion("trPlanSubIdsFoSix like", value, "trplansubidsfosix");
			return this;
		}

		public Criteria andTrplansubidsfosixNotLike(String value) {
			addCriterion("trPlanSubIdsFoSix not like", value,
					"trplansubidsfosix");
			return this;
		}

		public Criteria andTrplansubidsfosixIn(List values) {
			addCriterion("trPlanSubIdsFoSix in", values, "trplansubidsfosix");
			return this;
		}

		public Criteria andTrplansubidsfosixNotIn(List values) {
			addCriterion("trPlanSubIdsFoSix not in", values,
					"trplansubidsfosix");
			return this;
		}

		public Criteria andTrplansubidsfosixBetween(String value1, String value2) {
			addCriterion("trPlanSubIdsFoSix between", value1, value2,
					"trplansubidsfosix");
			return this;
		}

		public Criteria andTrplansubidsfosixNotBetween(String value1,
				String value2) {
			addCriterion("trPlanSubIdsFoSix not between", value1, value2,
					"trplansubidsfosix");
			return this;
		}

		public Criteria andTrplansubidsforsevenIsNull() {
			addCriterion("trPlanSubIdsForSeven is null");
			return this;
		}

		public Criteria andTrplansubidsforsevenIsNotNull() {
			addCriterion("trPlanSubIdsForSeven is not null");
			return this;
		}

		public Criteria andTrplansubidsforsevenEqualTo(String value) {
			addCriterion("trPlanSubIdsForSeven =", value,
					"trplansubidsforseven");
			return this;
		}

		public Criteria andTrplansubidsforsevenNotEqualTo(String value) {
			addCriterion("trPlanSubIdsForSeven <>", value,
					"trplansubidsforseven");
			return this;
		}

		public Criteria andTrplansubidsforsevenGreaterThan(String value) {
			addCriterion("trPlanSubIdsForSeven >", value,
					"trplansubidsforseven");
			return this;
		}

		public Criteria andTrplansubidsforsevenGreaterThanOrEqualTo(String value) {
			addCriterion("trPlanSubIdsForSeven >=", value,
					"trplansubidsforseven");
			return this;
		}

		public Criteria andTrplansubidsforsevenLessThan(String value) {
			addCriterion("trPlanSubIdsForSeven <", value,
					"trplansubidsforseven");
			return this;
		}

		public Criteria andTrplansubidsforsevenLessThanOrEqualTo(String value) {
			addCriterion("trPlanSubIdsForSeven <=", value,
					"trplansubidsforseven");
			return this;
		}

		public Criteria andTrplansubidsforsevenLike(String value) {
			addCriterion("trPlanSubIdsForSeven like", value,
					"trplansubidsforseven");
			return this;
		}

		public Criteria andTrplansubidsforsevenNotLike(String value) {
			addCriterion("trPlanSubIdsForSeven not like", value,
					"trplansubidsforseven");
			return this;
		}

		public Criteria andTrplansubidsforsevenIn(List values) {
			addCriterion("trPlanSubIdsForSeven in", values,
					"trplansubidsforseven");
			return this;
		}

		public Criteria andTrplansubidsforsevenNotIn(List values) {
			addCriterion("trPlanSubIdsForSeven not in", values,
					"trplansubidsforseven");
			return this;
		}

		public Criteria andTrplansubidsforsevenBetween(String value1,
				String value2) {
			addCriterion("trPlanSubIdsForSeven between", value1, value2,
					"trplansubidsforseven");
			return this;
		}

		public Criteria andTrplansubidsforsevenNotBetween(String value1,
				String value2) {
			addCriterion("trPlanSubIdsForSeven not between", value1, value2,
					"trplansubidsforseven");
			return this;
		}

		public Criteria andTrplansubidsforeightIsNull() {
			addCriterion("trPlanSubIdsForEight is null");
			return this;
		}

		public Criteria andTrplansubidsforeightIsNotNull() {
			addCriterion("trPlanSubIdsForEight is not null");
			return this;
		}

		public Criteria andTrplansubidsforeightEqualTo(String value) {
			addCriterion("trPlanSubIdsForEight =", value,
					"trplansubidsforeight");
			return this;
		}

		public Criteria andTrplansubidsforeightNotEqualTo(String value) {
			addCriterion("trPlanSubIdsForEight <>", value,
					"trplansubidsforeight");
			return this;
		}

		public Criteria andTrplansubidsforeightGreaterThan(String value) {
			addCriterion("trPlanSubIdsForEight >", value,
					"trplansubidsforeight");
			return this;
		}

		public Criteria andTrplansubidsforeightGreaterThanOrEqualTo(String value) {
			addCriterion("trPlanSubIdsForEight >=", value,
					"trplansubidsforeight");
			return this;
		}

		public Criteria andTrplansubidsforeightLessThan(String value) {
			addCriterion("trPlanSubIdsForEight <", value,
					"trplansubidsforeight");
			return this;
		}

		public Criteria andTrplansubidsforeightLessThanOrEqualTo(String value) {
			addCriterion("trPlanSubIdsForEight <=", value,
					"trplansubidsforeight");
			return this;
		}

		public Criteria andTrplansubidsforeightLike(String value) {
			addCriterion("trPlanSubIdsForEight like", value,
					"trplansubidsforeight");
			return this;
		}

		public Criteria andTrplansubidsforeightNotLike(String value) {
			addCriterion("trPlanSubIdsForEight not like", value,
					"trplansubidsforeight");
			return this;
		}

		public Criteria andTrplansubidsforeightIn(List values) {
			addCriterion("trPlanSubIdsForEight in", values,
					"trplansubidsforeight");
			return this;
		}

		public Criteria andTrplansubidsforeightNotIn(List values) {
			addCriterion("trPlanSubIdsForEight not in", values,
					"trplansubidsforeight");
			return this;
		}

		public Criteria andTrplansubidsforeightBetween(String value1,
				String value2) {
			addCriterion("trPlanSubIdsForEight between", value1, value2,
					"trplansubidsforeight");
			return this;
		}

		public Criteria andTrplansubidsforeightNotBetween(String value1,
				String value2) {
			addCriterion("trPlanSubIdsForEight not between", value1, value2,
					"trplansubidsforeight");
			return this;
		}
	}
}